//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "INetworkStatusMgrExt.h"
#import "IWCDeviceAirKissMgrExt.h"
#import "UITextFieldDelegate.h"

@class MMUIScrollView, NSData, NSString, UIButton, UITextField;

@interface AirKissViewController : MMUIViewController <UITextFieldDelegate, INetworkStatusMgrExt, IWCDeviceAirKissMgrExt>
{
    MMUIScrollView *m_scrollView;
    UITextField *m_password;
    UIButton *m_connectButton;
    NSString *m_ssid;
    _Bool m_isStarted;
    int m_procint;
    int m_dataint;
    id <AirKissViewControllerDelegate> m_delegate;
    NSData *m_key;
}

@property(nonatomic) int m_dataint; // @synthesize m_dataint;
@property(nonatomic) int m_procint; // @synthesize m_procint;
@property(retain, nonatomic) NSData *m_key; // @synthesize m_key;
@property(nonatomic) __weak id <AirKissViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onAirKissEnd:(_Bool)arg1;
- (void)onNetworkStatusChange:(unsigned int)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)onConnect;
- (void)onReturn:(id)arg1;
- (void)onNoWifiCancel;
- (void)onCancel;
- (id)dismissWithAnim;
- (void)initNoWifiView;
- (void)initView;
- (void)reloadView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

