//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface AlbumInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int height; // @dynamic height;
@property(retain, nonatomic) NSString *imageUrl; // @dynamic imageUrl;
@property(retain, nonatomic) NSMutableArray *thumbUrl; // @dynamic thumbUrl;
@property(nonatomic) unsigned int width; // @dynamic width;

@end

