//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding.h"

@class NSString, PublicWifiCache, PublicWifiPageInfo;

@interface APBase : MMObject <WCDBCoding>
{
    NSString *ssid;
    NSString *mac;
    unsigned int opCode;
    PublicWifiCache *cache;
    unsigned int scene;
    NSString *qrCode;
    NSString *mpUrl;
    NSString *mid;
    NSString *checkUrl;
    NSString *sessionKey;
    NSString *password;
    int actionCode;
    unsigned int protocolType;
    int _state;
    NSString *bannerText;
    NSString *showUrl;
    double expiredTime;
    PublicWifiPageInfo *_pageInfo;
}

+ (id)dummyObject;
+ (void)initialize;
@property(retain, nonatomic) PublicWifiPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) unsigned int protocolType; // @synthesize protocolType;
@property(copy, nonatomic) NSString *checkUrl; // @synthesize checkUrl;
@property(copy, nonatomic) NSString *mid; // @synthesize mid;
@property(copy, nonatomic) NSString *mpUrl; // @synthesize mpUrl;
@property(copy, nonatomic) NSString *qrCode; // @synthesize qrCode;
@property(nonatomic) double expiredTime; // @synthesize expiredTime;
@property(copy, nonatomic) NSString *showUrl; // @synthesize showUrl;
@property(copy, nonatomic) NSString *bannerText; // @synthesize bannerText;
@property(nonatomic) int actionCode; // @synthesize actionCode;
@property(nonatomic) unsigned int opCode; // @synthesize opCode;
@property(retain, nonatomic) NSString *mac; // @synthesize mac;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid;
@property(copy, nonatomic) NSString *password; // @synthesize password;
@property(copy, nonatomic) NSString *sessionKey; // @synthesize sessionKey;
@property(nonatomic) unsigned int scene; // @synthesize scene;
@property(nonatomic) __weak PublicWifiCache *cache; // @synthesize cache;
- (void).cxx_destruct;
- (void)handleHomeBarClicked:(id)arg1;
- (_Bool)canStartWithCurrSSID:(id)arg1;
- (void)cancel;
- (void)start;
@property(readonly, copy) NSString *description;
- (id)init;
- (void)dealloc;
- (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long long)getWCDBIndexArrayCount;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const map_0e718273 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_0e718273 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_7a576766 *)getValueNameIndexMap;
- (id)getValueTable;
- (const WCDBCondition_c6db074e *)db_protocolType;
- (const WCDBCondition_22fabacd *)db_checkUrl;
- (const WCDBCondition_22fabacd *)db_mid;
- (const WCDBCondition_22fabacd *)db_mpUrl;
- (const WCDBCondition_22fabacd *)db_qrCode;
- (const WCDBCondition_d49cb843 *)db_expiredTime;
- (const WCDBCondition_22fabacd *)db_showUrl;
- (const WCDBCondition_22fabacd *)db_bannerText;
- (const WCDBCondition_9620f531 *)db_actionCode;
- (const WCDBCondition_c6db074e *)db_opCode;
- (const WCDBCondition_22fabacd *)db_mac;
- (const WCDBCondition_22fabacd *)db_ssid;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

