//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IAppDataExt.h"

@class AppRegisterInfo, MMAnimationTipView, NSString, UIButton, UIImageView, UILabel;

@interface AppIntroViewController : MMUIViewController <IAppDataExt>
{
    UIImageView *m_appIconView;
    UILabel *m_appName;
    UILabel *m_appDes;
    UIButton *m_btnAdd;
    UIButton *m_btnRemove;
    UIButton *m_btnInstall;
    UIImageView *m_desBkgView;
    AppRegisterInfo *m_info;
    MMAnimationTipView *m_tipView;
    _Bool m_bFromRecommand;
}

@property(nonatomic) _Bool m_bFromRecommand; // @synthesize m_bFromRecommand;
@property(retain, nonatomic) MMAnimationTipView *m_tipView; // @synthesize m_tipView;
- (void).cxx_destruct;
- (void)OnAppInfoChanged:(id)arg1;
- (void)OnAppIconChanged:(id)arg1;
- (void)viewDidLoad;
- (void)jumpToInstallApp:(id)arg1;
- (void)removeApp:(id)arg1;
- (void)addApp:(id)arg1;
- (void)dealloc;
- (id)initWithAppInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

