//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMessageNodeView.h"

#import "UIAlertViewDelegate.h"

@class MMProgressView, NSArray, NSString, UILabel, UIView;

@interface AppUrlMessageNodeView : BaseMessageNodeView <UIAlertViewDelegate>
{
    UILabel *m_detailLabel;
    MMProgressView *m_progressView;
    UIView *m_progressBkgView;
    NSArray *m_arrBtnList;
}

+ (_Bool)canCreateMessageNodeViewInstanceWithMessageWrap:(id)arg1;
- (void).cxx_destruct;
- (id)getMoreMainInfomationAccessibilityDescription;
- (void)onMenuItemWillHide;
- (void)onTouchCancel;
- (void)onLongTouch;
- (void)onTouchUpInside;
- (void)onTouchDownRepeat;
- (void)onTouchDown;
- (void)onClearResource;
- (void)onDisappear;
- (void)onClick;
- (void)onMoreOperate:(id)arg1;
- (void)onForward:(id)arg1;
- (void)onFavoriteAdd:(id)arg1;
- (void)showOpearation;
- (void)updateBkgImage:(_Bool)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)resend;
- (void)updateThumbImage;
- (void)updateStatus:(id)arg1;
- (struct CGSize)sizeForFrame:(struct CGRect)arg1;
- (long long)numberOfBtnInNodeViewForShow;
- (void)clickNodeViewBtn:(id)arg1;
- (void)layoutSubviewsInternal;
- (id)getTitleText;
- (id)getFileDetailText;
- (void)genProgressViewWithFrame:(struct CGRect)arg1 andBackgroundFrame:(struct CGRect)arg2;
- (void)initDetailLabel;
- (id)getTitleLabel;
- (id)getDefaultThumbImage;
- (id)genCenterImage:(id)arg1;
- (id)getBackgroundImageHL;
- (id)getBackgroundImage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

