//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol BakChatRecoverNetworkHelperDelegate <NSObject>

@optional
- (void)OnDecryptDataError;
- (void)OnGetChatDataError;
- (void)OnGetChatData:(NSString *)arg1 WithLength:(unsigned int)arg2 InPath:(NSString *)arg3;
- (void)OnGetChatHeadError;
- (void)OnGetChatHead:(NSArray *)arg1 Type:(unsigned int)arg2;
- (void)OnGetChatList:(NSArray *)arg1;
@end

