//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSData, NSMutableDictionary, NSOperationQueue, NSRecursiveLock;

@interface BakChatUploadNetworkHelper : MMObject <PBMessageObserverDelegate>
{
    id <BakChatUploadNetworkDelegate> m_delegate;
    NSOperationQueue *m_operationQueue;
    NSMutableDictionary *m_operationMediaPackageHelperDic;
    NSData *m_oKeyData;
    NSRecursiveLock *m_oKeyDataLock;
    NSMutableDictionary *m_dicConnectionErrorCount;
    unsigned int m_uAllErrorCount;
}

@property(nonatomic) __weak id <BakChatUploadNetworkDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)onEndMessageReturn:(id)arg1;
- (void)onMediaPackageMessageReturn:(id)arg1;
- (void)onMsgPackageMessageReturn:(id)arg1;
- (void)onHeadMessageReturn:(id)arg1;
- (void)uploadBakChatMediaRequest:(id)arg1 packageData:(id)arg2 andOffset:(unsigned int)arg3 andEndFlag:(unsigned int)arg4 withSvrID:(unsigned int)arg5;
- (void)retryUploadMediaPackage:(id)arg1;
- (void)retryUploadMsgPackage:(id)arg1;
- (void)stopUploadBakChat;
- (void)getBakChatUploadEnd:(unsigned int)arg1;
- (void)uploadBakChatMediaPackage:(id)arg1 withSvrID:(unsigned int)arg2 WithKeyData:(id)arg3;
- (void)uploadBakChatMsgPackage:(id)arg1 WithKeyData:(id)arg2;
- (void)getBakChatUploadHead:(int)arg1;
- (void)getBakChatUploadNoEncrypt;
- (void)uploadBakChatMediaFirstCommonPackage:(id)arg1 withSvrID:(unsigned int)arg2;
- (void)uploadBakChatMediaCancelPackage:(id)arg1 withSvrID:(unsigned int)arg2;
- (void)retryUploadAfterFailure;
- (void)dealloc;
- (id)init;

@end

