//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IBakChatRecoverMgrExt.h"
#import "UIAlertViewDelegate.h"

@class BakChatItem, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel;

@interface BakChatListViewController : MMUIViewController <UIAlertViewDelegate, IBakChatRecoverMgrExt>
{
    UIButton *button;
    UILabel *loadLabel;
    UIActivityIndicatorView *activityIndicatorView;
    UILabel *timeLabel;
    UILabel *deviceLabel;
    UILabel *sizeLabel;
    UIImageView *acrossImageView;
    UILabel *noListLabel;
    NSString *m_oPassword;
    unsigned int m_bakChatSelectListStatus;
    BakChatItem *m_bakChatItem;
}

- (void).cxx_destruct;
- (void)addTextFieldToAlert:(id)arg1;
- (id)ConversionUnit:(long long)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)OnGetChatList:(id)arg1;
- (void)OnButtonDoneCancel:(id)arg1;
- (void)OnButtonDone:(id)arg1;
- (void)OnSelectListButtonDone:(id)arg1;
- (void)setListConf;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)showPasswordErrorAlertView;
- (void)showInputPasswordAlertView;
- (void)showEnsureDownloadAlert;
- (void)inHasListStatus;
- (void)inNoListStatus;
- (void)inLoadingStatus;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

