//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject;

@protocol BakChatUploadNetworkDelegate <NSObject>
- (void)OnFailureGetBakChatUploadEnd;
- (void)OnGetBakChatUploadEnd:(unsigned int)arg1;
- (void)OnTryUploadAfterFailureUploadBakChatUploadPackage;
- (void)OnFailureUploadBakChatPackage:(NSObject *)arg1;
- (void)OnSuccessUploadBakChatPackage:(NSObject *)arg1;
- (void)OnFailureGetBakChatUploadHead;
- (void)OnGetBakChatUploadHead:(unsigned int)arg1;

@optional
- (void)OnFailureEncryptData:(NSObject *)arg1;
@end

