//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "BakChatRecoverFileHelperDelegate.h"
#import "BakChatRecoverNetworkHelperDelegate.h"
#import "MMService.h"

@class BakChatRecoverBreakPointStruct, BakChatRecoverFileHelper, BakChatRecoverNetworkHelper, NSOperationQueue, NSRecursiveLock, NSString;

@interface BakChatRecoverMgr : MMService <MMService, BakChatRecoverNetworkHelperDelegate, BakChatRecoverFileHelperDelegate>
{
    BakChatRecoverNetworkHelper *m_bakChatRecoverNetworkHelper;
    BakChatRecoverBreakPointStruct *m_bakChatRecoverBreakPointStruct;
    BakChatRecoverFileHelper *m_bakChatRecoverFileHelper;
    NSRecursiveLock *m_HeadLock;
    NSOperationQueue *m_operationQueue;
    unsigned int m_totalLength;
    unsigned int m_currentLength;
    unsigned int m_svrID;
    _Bool hasMsgPackageList;
    _Bool hasMediaPackageList;
    _Bool isCancel;
    _Bool m_bError;
}

- (void).cxx_destruct;
- (_Bool)onServiceMemoryWarning;
- (void)onServiceTerminate;
- (void)onServiceEnterBackground;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)onMessageRecoverError:(long long)arg1;
- (void)onMessageRecoverDone:(id)arg1;
- (void)onMessageRecoverFileProgress:(id)arg1;
- (void)onMessageRecoverProgress:(id)arg1;
- (void)OnDecryptDataError;
- (void)OnGetChatDataError;
- (void)OnGetChatData:(id)arg1 WithLength:(unsigned int)arg2 InPath:(id)arg3;
- (void)OnGetChatHeadError;
- (void)OnGetChatHead:(id)arg1 Type:(unsigned int)arg2;
- (void)OnGetChatList:(id)arg1;
- (void)cancelDownloadAndRecoverBakChat;
- (void)stopDownloadAndRecoverBakChat;
- (void)stopWithOutPauseCountAddtionInDownloadAndRecoverBakChat;
- (void)continueDownloadBakChat;
- (void)recoverBreakPointStatus;
- (void)recoverCurrentStatus;
- (_Bool)usableBreakPoint;
- (void)startRecoverBakChat;
- (void)startDownloadBakChat:(id)arg1 TotalLength:(unsigned int)arg2 WithPassword:(id)arg3;
- (_Bool)isWorking;
- (void)getBakChatList;
- (void)innerCancelDownloadAndRecoverBakChat;
- (void)innerStartRecover;
- (void)innerStopDownloadAndRecoverBakChat;
- (void)innerCountinueDowloadBakChat;
- (void)innerRecoverBreakPointStatus;
- (void)innerRecoverCurrentStatus;
- (_Bool)innerUsableBreakPoint;
- (void)innerStartDownloadBakChat:(id)arg1;
- (void)startDownload;
- (_Bool)downloadNextPackage;
- (void)OnRestartOnMainThread;
- (void)OnPauseOnMainThread;
- (void)OnRecoverFileProgressOnMainThread:(id)arg1;
- (void)OnRecoverProgressOnMainThread:(id)arg1;
- (void)OnSuccessOnMainThread;
- (void)OnErrorOnMainThread:(id)arg1;
- (void)OnDownloadedOnMainThread;
- (void)OnDownloadProgressOnMainThread:(id)arg1;
- (void)OnGetChatListOnMainThread:(id)arg1;
- (void)updateSavePackage:(id)arg1 WithLength:(unsigned int)arg2 InPath:(id)arg3;
- (void)setBakChatRecoverStatusAndSave:(unsigned int)arg1;
- (id)recoverBreakPointStructWithLock:(id)arg1;
- (void)saveRecoverBreakPointStruct;
- (unsigned int)getPackagesInStatusCount:(unsigned int)arg1;
- (id)getNextClientIDWithReturnType:(unsigned int *)arg1;
- (void)changeStatus:(unsigned int)arg1 WithPath:(id)arg2 OfPackage:(id)arg3;
- (void)addPackages:(id)arg1 WithType:(unsigned int)arg2;
- (void)setBakChatRecoverStatus:(unsigned int)arg1;
- (void)setSvrID:(unsigned int)arg1;
- (void)addCurrentLength:(unsigned int)arg1;
- (void)setTotalLength:(unsigned int)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

