//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BakChatRecoverPacketInfo, BakChatRecoverProgressInfo, NSMutableDictionary, NSMutableSet, NSOperationQueue;

@interface BakChatRecoverFileHelper : NSObject
{
    _Bool m_bRecovering;
    NSOperationQueue *m_operationQueue;
    id <BakChatRecoverFileHelperDelegate> m_delegate;
    BakChatRecoverPacketInfo *m_oldBakPacketInfo;
    NSMutableDictionary *m_dicMediaIDPath;
    NSMutableSet *m_setChatName;
    BakChatRecoverProgressInfo *m_bakChatRecoverProgressInfo;
}

@property(nonatomic) __weak id <BakChatRecoverFileHelperDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (_Bool)StartRecoverMessageInternal:(id)arg1;
- (void)ALLRollback;
- (void)DBRollback;
- (void)FileRollback;
- (_Bool)AddContactListChat;
- (_Bool)RenameMediaFiles;
- (_Bool)addMsgAndFormMediaDictionary:(id)arg1;
- (id)messageWrapFromBakChatMsgItem:(id)arg1;
- (void)convertStatusVideo:(id)arg1 andBakchatMsgItem:(id)arg2;
- (_Bool)handleBufferForBakChatMsgItem:(id)arg1 messageWrap:(id)arg2 bakPacketInfo:(id)arg3;
- (id)onClearVoiceHeadData:(id)arg1;
- (id)pathForMessageWrap:(id)arg1 forBakChatMediaType:(unsigned int)arg2;
- (id)getMediaHeadByMessageWrap:(id)arg1;
- (id)getMediaIDByMessageWrap:(id)arg1;
- (id)getPackagePathNameForMediaID:(id)arg1;
- (void)initPackagePath;
- (void)clearAllOldPackage;
- (void)clearAllMsgAndMediaPackage;
- (void)StopRecoverMessage;
- (void)StartRecoverMessageThread:(id)arg1;
- (void)ReImportData;
- (void)checkOperationExcuting:(id)arg1;
- (void)StartRecoverMessage:(id)arg1;
- (_Bool)isBakChatName:(id)arg1;
- (void)dealloc;
- (id)init;

@end

