//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IBakChatRecoverMgrExt.h"
#import "IdleTimerUtilExt.h"
#import "UIAlertViewDelegate.h"

@class BakChatItem, MMProgressView, NSDate, NSLock, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UITextView;

@interface BakChatDownloadViewController : MMUIViewController <IdleTimerUtilExt, UIAlertViewDelegate, IBakChatRecoverMgrExt>
{
    UIImageView *m_downloadIcon;
    MMProgressView *m_progressView;
    UILabel *m_successLabel;
    UITextView *m_successRemarkLabel;
    UILabel *m_progressLabel;
    UIButton *m_restartButton;
    UIButton *m_cancelButton;
    UIActivityIndicatorView *m_activityIndicatorView;
    long long allSize;
    long long downloadSize;
    BakChatItem *m_bakChatItem;
    NSString *m_oPassword;
    unsigned int m_bakChatDownloadStatus;
    _Bool isNeedReturnAlert;
    _Bool m_immediateStarted;
    _Bool m_bRecovering;
    unsigned int downloadInterval;
    NSDate *startDate;
    unsigned int Time;
    unsigned int DownloadTime;
    NSLock *m_progressLock;
}

- (void).cxx_destruct;
- (void)onIdleTimerUtilVoipQuit;
- (void)OnDecryptError;
- (void)OnPause;
- (void)OnRecoverProcessFileProgress:(unsigned int)arg1 WithTotalCount:(unsigned int)arg2;
- (void)OnRecoverProgress:(unsigned int)arg1 WithTotalCount:(unsigned int)arg2;
- (void)OnSuccess;
- (void)OnDownloaded;
- (void)OnError:(unsigned int)arg1;
- (void)OnDownloadProgress:(unsigned int)arg1 WithTotalSize:(unsigned int)arg2;
- (void)setRecoverFileProgressLabel:(float)arg1;
- (void)setRecoverProgressLable:(float)arg1;
- (void)setDownloadProgressLabel;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)SucessReturnButtonDown:(id)arg1;
- (void)ReturnButtonDown:(id)arg1;
- (void)BackDownloadButtonDown:(id)arg1;
- (void)cancelButtonDone:(id)arg1;
- (void)recoverButtonDone:(id)arg1;
- (void)retryButtonDone:(id)arg1;
- (void)pauseButtonDone:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)loadView;
- (id)initWithBakChatItem:(id)arg1 Password:(id)arg2 WithImmediateContinueStarted:(_Bool)arg3;
- (id)initWithImmediateContinueStarted:(_Bool)arg1;
- (void)inNoListInServer;
- (void)inSuccessStatus;
- (void)inNotKnownErrorStatus;
- (void)inRecoverErrorStatus;
- (void)inRecoverStatus;
- (void)inPauseStatus;
- (void)inDownloadErrorStatus;
- (void)inDownloadStatus;
- (void)SafeSetProgress:(float)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

