//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "FTSJSEventDelegate.h"
#import "FTSWebSearchDataSource.h"
#import "MMSearchBarDelegate.h"
#import "UISearchBarDelegate.h"
#import "UIWebViewDelegate.h"

@class MMSearchBar, MMUISearchBar, MMUIViewController, NSDictionary, NSString, UIImageView, UIWebView, WXSearchJSLogicImpl;

@interface BrandServiceWebSearchController : MMObject <MMSearchBarDelegate, UIWebViewDelegate, FTSJSEventDelegate, FTSWebSearchDataSource, UISearchBarDelegate>
{
    UIWebView *_guideView;
    UIWebView *_resultView;
    UIWebView *_detailWebView;
    MMUIViewController *m_contentVC;
    _Bool _isDetailSearch;
    _Bool _hasLoadResultH5;
    _Bool _bSearchFromHotword;
    unsigned long long _detailSearchType;
    NSDictionary *_jsonForDetailPage;
    NSString *_searchID;
    MMUISearchBar *_searchBarForDetailPage;
    UIImageView *_searchBarWrap;
    UIImageView *_bottomViewShadow;
    double _searchTextFieldNormalWidth;
    _Bool _hasMoving;
    double _moveStartOffset;
    double _moveCurOffset;
    double _moveContentOffsetY;
    unsigned int _searchScene;
    unsigned int _entryFlag;
    MMSearchBar *_searchBar;
    WXSearchJSLogicImpl *_jsGuideViewLogic;
    WXSearchJSLogicImpl *_jsResultViewLogic;
    NSString *_keywordForHomePage;
    NSString *_keywordForDetailPage;
}

@property(retain, nonatomic) NSString *keywordForDetailPage; // @synthesize keywordForDetailPage=_keywordForDetailPage;
@property(retain, nonatomic) NSString *keywordForHomePage; // @synthesize keywordForHomePage=_keywordForHomePage;
@property(retain, nonatomic) WXSearchJSLogicImpl *jsResultViewLogic; // @synthesize jsResultViewLogic=_jsResultViewLogic;
@property(retain, nonatomic) WXSearchJSLogicImpl *jsGuideViewLogic; // @synthesize jsGuideViewLogic=_jsGuideViewLogic;
@property(retain, nonatomic) UIWebView *resultView; // @synthesize resultView=_resultView;
@property(retain, nonatomic) UIWebView *guideView; // @synthesize guideView=_guideView;
@property(nonatomic) unsigned int entryFlag; // @synthesize entryFlag=_entryFlag;
@property(retain, nonatomic) MMSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) unsigned int searchScene; // @synthesize searchScene=_searchScene;
- (void).cxx_destruct;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)onOpenMsgSession:(id)arg1;
- (void)onStartBrandSearch:(id)arg1;
- (void)onOpenBrandContact:(id)arg1 withParams:(id)arg2;
- (void)onLaunchPage:(id)arg1;
- (void)onLaunchDetailPage:(id)arg1;
- (void)onBeginNextPage:(id)arg1;
- (void)onSearchRecmdDataFail;
- (void)onFailReceiveJson;
- (void)onReceiveJson:(id)arg1;
- (id)query;
- (id)detailCache;
- (id)cellForSearchViewTable:(id)arg1 index:(id)arg2;
- (void)didSearchViewTableSelect:(id)arg1;
- (id)viewForHeaderInSection:(long long)arg1 ForSearchViewTable:(id)arg2;
- (double)heightForHeaderInSection:(long long)arg1 ForSearchViewTable:(id)arg2;
- (double)heightForSearchViewTable:(id)arg1;
- (long long)numberOfRowsInSection:(long long)arg1 ForSearchViewTable:(id)arg2;
- (long long)numberOfSectionsForSearchViewTable:(id)arg1;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)clearDetailView;
- (void)onRemoveDetailViewAndSearchWrap;
- (void)animatedPushDetailView;
- (void)cancelMoveDetailView;
- (void)moveDetailViewToRight;
- (void)updateMovingDetailView;
- (void)handlePanGestureForDetailView:(id)arg1;
- (void)willBeginDetailSearch;
- (double)getSearchTextFieldWidth;
- (void)popFromDetailSearch;
- (void)onBackBtnClick;
- (void)onClickSearchButton:(id)arg1;
- (void)asyncSearchForDetail:(id)arg1 businessType:(unsigned long long)arg2 actionType:(unsigned int)arg3;
- (void)asyncSearch:(id)arg1 actionType:(unsigned int)arg2;
- (void)resetSearch;
- (void)onSelectItemWithContactInfo:(id)arg1 andSearchId:(id)arg2;
- (void)onSelectItemWithUrlAddress:(id)arg1;
- (id)getSearchContentViewController;
- (void)mmsearchBarTextDidBeginEditing:(id)arg1;
- (void)mmsearchBarCancelButtonClicked:(id)arg1;
- (void)mmsearchBarSearchButtonClicked:(id)arg1;
- (void)mmSearchBarTextDidChange:(id)arg1;
- (void)mmSearchDisplayControllerDidEndSearch;
- (void)mmSearchDisplayControllerWillEndSearch;
- (void)mmSearchDisplayControllerDidBeginSearch;
- (void)mmSearchDisplayControllerWillBeginSearch;
- (void)hideKeyboard;
- (unsigned int)getGo2ProfileScene;
- (void)viewDidPop;
- (void)resetSearchBarFrame;
- (void)searchBarResignFirstResponder;
- (id)initWithContentViewController:(id)arg1 withEntryFlag:(unsigned int)arg2 withSearchScene:(unsigned int)arg3;
- (id)initWithContentViewController:(id)arg1 withEntryFlag:(unsigned int)arg2;
- (void)showWebview:(id)arg1;
- (void)hideSearchTableResultText;
- (void)enableButton:(id)arg1;
- (void)loadLocalHtmlForDetailPage:(id)arg1;
- (void)tryLoadBSSResult:(id)arg1;
- (void)loadBSSGuideH5;
- (void)initResultView;
- (void)initGuideView;
- (void)initSearchBarWrap;
- (void)initView;
- (void)initSearchBarWithContentVC:(id)arg1;
- (void)initViewWithContentVC:(id)arg1;
- (void)initData;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

