//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CaptureVideoInfo : NSObject
{
    NSString *thumb_path;
    NSString *video_path;
    unsigned int video_time;
    unsigned int video_size;
    unsigned int thumb_size;
    unsigned int m_uiVideoOffset;
    _Bool front_camera;
    unsigned int m_uiVideoSource;
    _Bool m_bForward;
    NSString *m_nsMsgDataUrl;
    NSString *m_nsAesKey;
    NSString *m_msgSource;
    unsigned int thumb_width;
    unsigned int thumb_height;
}

@property(nonatomic) unsigned int thumb_height; // @synthesize thumb_height;
@property(nonatomic) unsigned int thumb_width; // @synthesize thumb_width;
@property(retain, nonatomic) NSString *m_msgSource; // @synthesize m_msgSource;
@property(retain, nonatomic) NSString *m_nsAesKey; // @synthesize m_nsAesKey;
@property(retain, nonatomic) NSString *m_nsMsgDataUrl; // @synthesize m_nsMsgDataUrl;
@property(nonatomic) _Bool m_bForward; // @synthesize m_bForward;
@property(nonatomic) unsigned int m_uiVideoSource; // @synthesize m_uiVideoSource;
@property(nonatomic) _Bool front_camera; // @synthesize front_camera;
@property(nonatomic) unsigned int m_uiVideoOffset; // @synthesize m_uiVideoOffset;
@property(nonatomic) unsigned int thumb_size; // @synthesize thumb_size;
@property(nonatomic) unsigned int video_size; // @synthesize video_size;
@property(nonatomic) unsigned int video_time; // @synthesize video_time;
@property(retain, nonatomic) NSString *video_path; // @synthesize video_path;
@property(retain, nonatomic) NSString *thumb_path; // @synthesize thumb_path;
- (void).cxx_destruct;
- (id)init;

@end

