//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "EmoticonDescMgrExt.h"
#import "IMMLanguageMgrExt.h"
#import "MMConfigMgrExt.h"
#import "MMPackageDownloadMgrExt.h"
#import "MMResPackageMgrExt.h"
#import "MMService.h"

@class CEmoticonDB, NSMutableArray, NSRecursiveLock, NSString;

@interface CEmoticonMgr : MMService <IMMLanguageMgrExt, MMService, MMPackageDownloadMgrExt, MMResPackageMgrExt, EmoticonDescMgrExt, MMConfigMgrExt>
{
    CEmoticonDB *m_oEmoticonDB;
    NSRecursiveLock *m_oLock;
    unsigned int m_uiLastUpdateTime;
    NSMutableArray *m_needRemoveEmoticons;
}

+ (_Bool)isTusijiEmoticonMD5:(id)arg1;
+ (id)genSafeEmoticonImage:(id)arg1;
+ (unsigned int)getIdKeyResolutionLimit;
+ (unsigned int)getIdKeyIdEmoticon;
+ (id)getEmoticonImageByMD5:(id)arg1;
+ (void)RenameEmoticon;
+ (_Bool)IsEmoticonImageExist:(id)arg1;
@property(retain, nonatomic) NSMutableArray *m_needRemoveEmoticons; // @synthesize m_needRemoveEmoticons;
@property(retain, nonatomic) NSRecursiveLock *m_oLock; // @synthesize m_oLock;
- (void).cxx_destruct;
- (void)onMMDynamicConfigUpdated;
- (id)getRecentUsedEmoticonList:(unsigned int)arg1;
- (_Bool)updateEmoticon:(id)arg1 packageId:(id)arg2;
- (_Bool)updateEmoticon:(id)arg1 usedTime:(unsigned int)arg2;
- (id)getCustomEmoticonListWithOutGame;
- (id)getEmoticonListByPackageId:(id)arg1;
- (id)getEmoticonWrapByMd5:(id)arg1;
- (_Bool)AddEmoticonSilently:(id)arg1 Type:(unsigned int)arg2 packageId:(id)arg3 Source:(long long)arg4;
- (id)AddEmoticon:(id)arg1 Type:(unsigned int)arg2 packageId:(id)arg3 Source:(long long)arg4;
- (id)AddEmoticonSilently:(id)arg1 Type:(unsigned int)arg2 Source:(long long)arg3;
- (id)updatedEmoticonArrayForGame:(id)arg1;
- (void)ResetEmoticon;
- (void)ResetEmojiArt;
- (void)onResPackageReady:(id)arg1;
- (void)onPackageListUpdated:(id)arg1;
- (void)CheckUpdate;
- (void)UpdateEmojiArtFromResource;
- (void)UpdateLocalEmojiArtByData:(id)arg1;
- (void)UpdateEmojiArtByXml:(struct XmlReaderNode_t *)arg1;
- (id)GetEmojiCataLogList;
- (void)InitHardCodeEmojiArtList;
- (_Bool)DeleteEmojiByEmoji:(id)arg1;
- (_Bool)AddEmoji:(id)arg1;
- (id)GetEmojiList:(unsigned int)arg1;
- (_Bool)IsCanDelete:(id)arg1;
- (_Bool)CheckEmoticonExist:(id)arg1;
- (id)GetEmoticonByMD5:(id)arg1;
- (_Bool)deleteEmoticonByPid:(id)arg1;
- (void)DeleteEmoticonByListMD5:(id)arg1;
- (_Bool)DeleteEmoticonByMD5:(id)arg1;
- (id)AddEmoticon:(id)arg1 Type:(unsigned int)arg2 ExtInfo:(id)arg3 Source:(long long)arg4;
- (id)AddEmoticon:(id)arg1 Type:(unsigned int)arg2 Source:(long long)arg3;
- (id)checkAndSaveEmoticon:(id)arg1;
- (id)GetEmoticonList;
- (void)InitLocalList;
- (void)hardcodeTusiji;
- (void)CopyPic:(id)arg1 From:(id)arg2;
- (void)AddHardCode:(id)arg1 Type:(unsigned int)arg2 GameType:(unsigned int)arg3 OriginPath:(id)arg4 packageId:(id)arg5;
- (void)InitEmoticonMgr:(id)arg1 Lock:(id)arg2;
- (void)cleanUpNonExistEmoticonList;
- (void)addToCleanUpList:(id)arg1;
- (_Bool)onServiceMemoryWarning;
- (void)onLanguageChange;
- (void)dealloc;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

