//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CEmoticonDB.h"

@interface CEmoticonDB (EmojiDB)
- (void)ResetEmojiArt;
- (void)UpdateCatalogVersion:(unsigned int)arg1 Display:(id)arg2 SvrID:(unsigned int)arg3;
- (void)AddCatalog:(id)arg1 SvrID:(unsigned int)arg2 Version:(unsigned int)arg3 Display:(id)arg4;
- (id)GetEmojiCataLogList;
- (_Bool)IsCataLogExist:(unsigned int)arg1;
- (unsigned int)GetCatalogVersion:(unsigned int)arg1;
- (unsigned int)GetLocalCatalogID:(unsigned int)arg1;
- (_Bool)DeleteEmojiByCatalogID:(unsigned int)arg1;
- (_Bool)DeleteEmojiByEmoji:(id)arg1;
- (_Bool)AddEmoji:(id)arg1;
- (id)GetEmojiList:(unsigned int)arg1;
@end

