//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IMessageWrapExt.h"
#import "IMsgExtendOperation.h"
#import "NSCopying.h"

@class CMessageWrap, NSString;

@interface CExtendInfoOfEmoticon : NSObject <IMessageWrapExt, IMsgExtendOperation, NSCopying>
{
    NSString *m_nsEmoticonMD5;
    unsigned int m_uiEmoticonType;
    unsigned int m_uiGameType;
    unsigned int m_uiGameContent;
    unsigned int m_uiUploadStatus;
    NSString *m_nsEmoticonBelongToProductID;
    CMessageWrap *m_refMessageWrap;
    NSString *m_cdnUrlString;
}

+ (void)CreateExtendInfoWithType:(unsigned int)arg1 retExtendInfo:(id *)arg2;
@property(retain, nonatomic) NSString *m_cdnUrlString; // @synthesize m_cdnUrlString;
@property(copy, nonatomic) NSString *m_nsEmoticonBelongToProductID; // @synthesize m_nsEmoticonBelongToProductID;
@property(nonatomic) unsigned int m_uiUploadStatus; // @synthesize m_uiUploadStatus;
@property(nonatomic) CMessageWrap *m_refMessageWrap; // @synthesize m_refMessageWrap;
@property(nonatomic) unsigned int m_uiGameType; // @synthesize m_uiGameType;
@property(nonatomic) unsigned int m_uiGameContent; // @synthesize m_uiGameContent;
@property(nonatomic) unsigned int m_uiEmoticonType; // @synthesize m_uiEmoticonType;
@property(retain, nonatomic) NSString *m_nsEmoticonMD5; // @synthesize m_nsEmoticonMD5;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (void)UpdateGameInfo:(id)arg1;
- (id)GetGameStatReportString;
- (void)UpdateContent:(id)arg1;
- (id)GetContent;
- (void)ChangeForDisplay;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

