//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ChatMigrationDataProcessMgrDelegate.h"
#import "ChatMigrationGetConnectInfoDelegate.h"
#import "LocalAreaNetworkClientDelegate.h"

@class ChatMigrationDataProcessMgr, ChatMigrationGetConnectInfo, GetConnectInfoResponse, LocalAreaNetworkClient, NSString;

@interface ChatMigrationClientLogic : MMObject <LocalAreaNetworkClientDelegate, ChatMigrationGetConnectInfoDelegate, ChatMigrationDataProcessMgrDelegate>
{
    ChatMigrationDataProcessMgr *m_DataProcMgr;
    LocalAreaNetworkClient *m_NetworkHandle;
    ChatMigrationGetConnectInfo *m_GetConnectInfoHandle;
    GetConnectInfoResponse *m_cacheInfoRes;
    id <ChatMigrationClientLogicDelegate> m_delegate;
    unsigned long long uiChatMigrationTotalSize;
    NSString *nsRemoteWifiName;
}

@property(retain, nonatomic) NSString *nsRemoteWifiName; // @synthesize nsRemoteWifiName;
@property(nonatomic) unsigned long long uiChatMigrationTotalSize; // @synthesize uiChatMigrationTotalSize;
@property(nonatomic) __weak id <ChatMigrationClientLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (_Bool)GetLocalDiskCheckResult:(unsigned long long)arg1;
- (void)onTransferProgress:(unsigned int)arg1 procSize:(unsigned int)arg2;
- (void)onNotifyEvent:(int)arg1;
- (void)onProcError:(int)arg1;
- (void)onSendData:(id)arg1;
- (_Bool)isSameAccount:(id)arg1;
- (void)onGetConnectInfo:(id)arg1;
- (void)onDisconnect;
- (void)onReciveData:(id)arg1 andLength:(unsigned int)arg2;
- (void)GetConnectInfo:(id)arg1;
- (void)StopClientService;
- (void)StartClientService:(id)arg1;
- (_Bool)StartClientServiceWithIP:(id)arg1 andPort:(unsigned short)arg2;
- (_Bool)isEnoughDiskSize:(unsigned long long)arg1;
- (_Bool)isSameNetGateWay:(id)arg1;
- (_Bool)isSameWifi:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

