//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ChatMigrationCreateQRCodeDelegate.h"
#import "ChatMigrationDataProcessMgrDelegate.h"
#import "LocalAreaNetworkServerDelegate.h"

@class ChatMigrationCreateQRCode, ChatMigrationDataProcessMgr, LocalAreaNetworkServer, NSString;

@interface ChatMigrationServerLogic : MMObject <LocalAreaNetworkServerDelegate, ChatMigrationCreateQRCodeDelegate, ChatMigrationDataProcessMgrDelegate>
{
    ChatMigrationDataProcessMgr *m_DataProcMgr;
    LocalAreaNetworkServer *m_NetworkHandle;
    ChatMigrationCreateQRCode *m_GetQRCodeHandle;
    NSString *server_ip;
    unsigned short server_port;
    id <ChatMigrationServerLogicDelegate> m_delegate;
}

@property(nonatomic) __weak id <ChatMigrationServerLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onTransferProgress:(unsigned int)arg1 procSize:(unsigned int)arg2;
- (void)onNotifyEvent:(int)arg1;
- (void)onProcError:(int)arg1;
- (void)onSendData:(id)arg1;
- (void)onGetQRCode:(id)arg1;
- (void)onDisconnect;
- (void)onConnected;
- (void)onReciveData:(id)arg1 andLength:(unsigned int)arg2;
- (void)StopServerService;
- (_Bool)StartServerService;
- (void)GetQRCodeImg;
- (unsigned short)GetServerPort;
- (id)GetServerIP;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

