//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ChatMigrationInspectUtility : NSObject
{
}

+ (void)ShowLocalNotificationWhenChatMigrationWorking;
+ (_Bool)CompareBackupReportInfo:(id)arg1 withRecover:(id)arg2;
+ (void)DebugReportInfo:(id)arg1 isRecover:(_Bool)arg2;
+ (id)currentHotSpotOrWifiSSID;
+ (_Bool)IsOnWifiOrHostSpotMode;
+ (_Bool)IsSameNetGateWay:(id)arg1;
+ (_Bool)IsHotspotActivity;
+ (unsigned long long)GetFreeDiskSpace;
+ (_Bool)IsBatteryChargeAndLevel:(float *)arg1;

@end

