//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class BakChatUploadMediaPackageStruct, BakChatUploadPackageHelperStruct, ChatMigrationBackupChatFileHelper, NSDate, NSMutableArray, NSString;

@interface ChatMigrationBackupChatLogic : MMObject
{
    ChatMigrationBackupChatFileHelper *m_BakChatFileHelper;
    BakChatUploadPackageHelperStruct *m_PkgHelperStruct;
    BakChatUploadMediaPackageStruct *m_LastMediaPkg;
    int iLastMediaPkgEndOffset;
    NSMutableArray *arrBackupPkgFileNames;
    _Bool m_bBackuping;
    NSMutableArray *m_nsUsrNameArray;
    NSDate *startDate;
    unsigned long long uiTotalCount;
    unsigned long long uiTotalSize;
    NSString *nsLastDataId;
    unsigned int uiPackedSize;
    _Bool bRunOnce;
    id <ChatMigrationBackupChatLogicDelegate> m_delegate;
}

+ (unsigned long long)getEachSessionSize:(id)arg1;
+ (unsigned long long)getEmotionTotalSize;
+ (unsigned long long)getDBTotalSize;
+ (id)getAllSessionUserName;
+ (unsigned long long)GetProbablyMigrationSize;
@property(nonatomic) __weak id <ChatMigrationBackupChatLogicDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (_Bool)startBackupTask:(id)arg1 count:(unsigned long long *)arg2 size:(unsigned long long *)arg3;
- (void)dumpPkgToFileAndUpdateCache:(id)arg1 withID:(id)arg2 andOffset:(int)arg3;
- (id)getBackupDataPushPkgFromMediaStruct:(id)arg1 andDataID:(id)arg2 withOffset:(unsigned int)arg3;
- (id)getBackupDataPushPkgFromMsgRequst:(id)arg1 andDataID:(id)arg2;
- (id)packageAllDataToFile;
- (void)getFirstDataWhenPkgReadyAsyn;
- (id)getNextPieceOfData:(id)arg1;
- (id)getFileNameListOfDirPath:(id)arg1;
- (void)cancelBackup;
- (_Bool)getStartBackupInfo:(unsigned long long *)arg1 andSize:(unsigned long long *)arg2;
- (id)getDicOfBackupReportInfo;
- (void)dealloc;
- (id)init;

@end

