//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMessageWrap.h"

@class NSString;

@interface CMessageWrap (Video)
- (id)GetCdnDownloadThumbPathOfVideo;
- (id)GetCdnDownloadPathOfVideo;

// Remaining properties
@property(retain, nonatomic) NSString *m_nsFileParam; // @dynamic m_nsFileParam;
@property(nonatomic) unsigned int m_uiCameraType; // @dynamic m_uiCameraType;
@property(nonatomic) unsigned int m_uiVideoLen; // @dynamic m_uiVideoLen;
@property(nonatomic) unsigned int m_uiVideoOffset; // @dynamic m_uiVideoOffset;
@property(nonatomic) unsigned int m_uiVideoSource; // @dynamic m_uiVideoSource;
@property(nonatomic) unsigned int m_uiVideoTime; // @dynamic m_uiVideoTime;
@end

