//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CMMDB.h"

@interface CMMDB (SendMessage)
- (unsigned int)GetCountOfSendMessage;
- (id)GetSendMessageOnProperty:(const vector_24c76cbd *)arg1 AfterRowId:(unsigned int)arg2;
- (_Bool)InsertSendMessage:(id)arg1 onProperty:(const vector_24c76cbd *)arg2;
- (_Bool)DeleteSendMessageByChatName:(id)arg1 localId:(unsigned int)arg2;
- (_Bool)IsExistInSendMessageByChatName:(id)arg1 localId:(unsigned int)arg2;
@end

