//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

@interface CMMDBResultNew : NSObject
{
    NSMutableDictionary *m_dicResult;
    NSMutableArray *m_arrRef;
}

- (void).cxx_destruct;
- (_Bool)CheckValid;
- (unsigned long long)GetRowCount;
- (unsigned long long)GetColCount;
- (id)GetColValueInRow:(unsigned long long)arg1 inCol:(unsigned long long)arg2;
- (id)GetColValue:(unsigned long long)arg1 col:(id)arg2;
- (_Bool)SaveValueToCol:(id)arg1 ColIndex:(unsigned long long)arg2;
- (void)dealloc;
- (void)SetSizeAndAlloc:(unsigned long long)arg1 arrCol:(id)arg2;
- (id)init;

@end

