//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "FavTagEditViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class FavTagListView, MMScrollView, NSMutableArray, NSMutableDictionary, NSString, UIImageView, UILabel;

@interface ContactsTagFilterDisplayView : MMUIView <FavTagEditViewDelegate, UIScrollViewDelegate>
{
    MMScrollView *m_scrollView;
    UILabel *m_label;
    FavTagListView *m_tagListView;
    id <ContactsTagFilterDisplayViewDelegate> m_delegate;
    UIImageView *m_emptyTagListView;
    NSMutableArray *m_arrFilterEmptyTag;
    NSMutableDictionary *m_dicContactsOfTagName;
    _Bool m_bIsFromMainSearchOrFromContactSearch;
}

@property(retain, nonatomic) UIImageView *m_emptyTagListView; // @synthesize m_emptyTagListView;
@property(nonatomic) _Bool m_bIsFromMainSearchOrFromContactSearch; // @synthesize m_bIsFromMainSearchOrFromContactSearch;
@property(nonatomic) __weak id <ContactsTagFilterDisplayViewDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)onTagHighLight:(id)arg1;
- (void)updateEmptyView;
- (void)showContentView;
- (void)hideContentView;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)GetContactsWithTagName:(id)arg1;
- (void)removeTagList;
- (void)updateTagList;
- (_Bool)canShow;
- (void)ontap;
- (void)initView;
- (void)layoutSubviews;
- (void)addBlurEffectForView:(id)arg1 atPoint:(struct CGPoint)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

