//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@class NSString;

@interface CQQGroupWrap : NSObject <NSCoding, NSCopying>
{
    unsigned int m_uiGroupId;
    NSString *m_nsGroupName;
    NSString *m_nsGroupMD5;
    unsigned int m_uiMemberNum;
    unsigned int m_uiWeixinNum;
    _Bool m_bNeedReloadFriend;
}

@property(nonatomic) _Bool m_bNeedReloadFriend; // @synthesize m_bNeedReloadFriend;
@property(nonatomic) unsigned int m_uiWeixinNum; // @synthesize m_uiWeixinNum;
@property(nonatomic) unsigned int m_uiMemberNum; // @synthesize m_uiMemberNum;
@property(retain, nonatomic) NSString *m_nsGroupMD5; // @synthesize m_nsGroupMD5;
@property(retain, nonatomic) NSString *m_nsGroupName; // @synthesize m_nsGroupName;
@property(nonatomic) unsigned int m_uiGroupId; // @synthesize m_uiGroupId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;

@end

