//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface DeviceRankItem : MMObject
{
    unsigned int uiRankNum;
    NSString *nsRankId;
    NSString *nsRankTitle;
}

@property(nonatomic) unsigned int uiRankNum; // @synthesize uiRankNum;
@property(retain, nonatomic) NSString *nsRankTitle; // @synthesize nsRankTitle;
@property(retain, nonatomic) NSString *nsRankId; // @synthesize nsRankId;
- (void).cxx_destruct;

@end

