//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSArray, NSString;

@interface DeviceRankDetailResonse : MMObject
{
    unsigned int uiDayScore;
    NSString *nsCoverUrl;
    NSString *nsMotto;
    NSString *nsDayScoreTitle;
    NSArray *aryRankList;
    NSArray *aryScoreDescList;
    NSString *nsSource;
    NSArray *_affectedUserList;
    NSString *_shareUrl;
    NSString *_shareTitle;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
@property(retain, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) NSArray *affectedUserList; // @synthesize affectedUserList=_affectedUserList;
@property(retain, nonatomic) NSString *nsSource; // @synthesize nsSource;
@property(retain, nonatomic) NSArray *aryScoreDescList; // @synthesize aryScoreDescList;
@property(retain, nonatomic) NSArray *aryRankList; // @synthesize aryRankList;
@property(nonatomic) unsigned int uiDayScore; // @synthesize uiDayScore;
@property(retain, nonatomic) NSString *nsDayScoreTitle; // @synthesize nsDayScoreTitle;
@property(retain, nonatomic) NSString *nsMotto; // @synthesize nsMotto;
@property(retain, nonatomic) NSString *nsCoverUrl; // @synthesize nsCoverUrl;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

@end

