//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface EmoticonCustomReportData : MMObject
{
}

+ (void)ReportCustomEmoticonCountWhenStartRecover:(unsigned long long)arg1;
+ (void)ReportEmoticonCustomManageEditClick;
+ (void)ReportEmoticonCustomManageAddClick;
+ (void)ReportManualStopSync;
+ (void)ReportAutoStartSync;
+ (void)ReportHasEmoticonToSync;
+ (void)ReportConfirmStartSyncAtCellNetwork;
+ (void)ReportManualStartSyncAtCellNetwork;
+ (void)ReportCustomEmoticonStoreClick;
+ (void)ReportEmoticonFreeClick;
+ (void)ReportEmoticonNewClick;
+ (void)ReportEmoticonBrowserBannerClick;
+ (void)ReportCustomEmoticonManageIconClick;
+ (void)ReportCustomEmoticonTabClick;

@end

