//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface EmoticonStoreListCache : MMObject <PBCoding>
{
    NSMutableArray *itemList;
    NSMutableArray *m_adArray;
    NSMutableArray *m_coolCellArray;
    unsigned int m_topHotNum;
}

+ (void)initialize;
@property(nonatomic) unsigned int m_topHotNum; // @synthesize m_topHotNum;
@property(retain, nonatomic) NSMutableArray *m_coolCellArray; // @synthesize m_coolCellArray;
@property(retain, nonatomic) NSMutableArray *m_adArray; // @synthesize m_adArray;
@property(retain, nonatomic) NSMutableArray *itemList; // @synthesize itemList;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

