//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface EmoticonStoreReportData : MMObject
{
}

+ (void)markReportSendEmoticonFromNowUseButton;
+ (void)changeToolViewStateToNoneEmoticon;
+ (void)changeEmoticonBoardIndex;
+ (void)ReportSendEmoticonFromNowUseButton:(id)arg1;
+ (void)ReportClickNowUseButton:(id)arg1;
+ (void)ReportClickCollectionCellForReqType:(unsigned int)arg1;
+ (void)ReportClickEmoticonNew;
+ (void)ReportClickEmoticonFromDesc:(id)arg1;
+ (void)ReportShowDescToEmoticon:(id)arg1;
+ (void)ReportClickEmoticonShareFromTimeline:(id)arg1;
+ (void)ReportClickEmoticonShareFromMessage:(id)arg1;
+ (void)ReportEmoticonShareToTimeline:(id)arg1;
+ (void)ReportEmoticonShareToFriends:(id)arg1;

@end

