//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class EmoticonStoreItem, NSString;

@interface EmoticonStoreAd : MMObject <PBCoding>
{
    NSString *imageUrl;
    struct CGSize imageSize;
    EmoticonStoreItem *storeItem;
    NSString *stripUrl;
    NSString *title;
    NSString *locateUrlString;
    NSString *secondUrlString;
    unsigned int id;
}

+ (id)StoreAdFromBannerSet:(id)arg1;
+ (id)StoreAdFromBanner:(id)arg1;
+ (void)initialize;
@property(retain, nonatomic) NSString *secondUrlString; // @synthesize secondUrlString;
@property(nonatomic) unsigned int id; // @synthesize id;
@property(retain, nonatomic) NSString *locateUrlString; // @synthesize locateUrlString;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *stripUrl; // @synthesize stripUrl;
@property(retain, nonatomic) EmoticonStoreItem *storeItem; // @synthesize storeItem;
@property(nonatomic) struct CGSize imageSize; // @synthesize imageSize;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl;
- (void).cxx_destruct;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

