//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

@class NSArray;

@interface EncryptGuideViewController : MMUIViewController
{
    NSArray *m_oSessionNameArray;
    _Bool m_allSelected;
}

- (void).cxx_destruct;
- (void)uploadButtonDone:(id)arg1;
- (void)encryptButtonDone:(id)arg1;
- (void)ReturnButtonDown:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)initView;
- (void)dealloc;
- (id)initWithContactsArray:(id)arg1 allSelected:(_Bool)arg2;

@end

