//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EnterpriseMsgUtil : NSObject
{
}

+ (id)FormImageMsg:(id)arg1 withImage:(id)arg2;
+ (id)FormTextMsg:(id)arg1 withText:(id)arg2;

@end

