//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMBaseSessionCellData.h"

@interface EnterpriseSessionCellData : MMBaseSessionCellData
{
}

- (id)textForMsgLabelWithMessage:(id)arg1;
- (void)updateHeadViewInfo:(id)arg1;
- (void)updateNameLabelText:(id)arg1;
- (void)updateMsgLabelTextForEnterpriseMsg:(id)arg1;
- (void)updateWithEnterpriseSessionInfo:(id)arg1;
- (void)updateWithBaseSessionInfo:(id)arg1;

@end

