//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface EnterpriseUtil : MMObject
{
}

+ (id)convertSvrFullBizChat2EnterpirseContact:(id)arg1;
+ (id)getEnterpriseChatBrandUserName:(id)arg1;
+ (_Bool)isChatRoomMsg:(id)arg1;
+ (id)batchConvertEnterpriseMsgDBItem2MsgWrap:(id)arg1;
+ (id)convertEnterpriseMsgDBItem2MsgWrap:(id)arg1;
+ (id)convertMsgWrap2EnterpriseDBItem:(id)arg1 brandUserName:(id)arg2;
+ (id)getEnterpriseChatCachePath;

@end

