//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "EnterpriseMemberViewDelegate.h"
#import "IEnterpriseGroupMgrExt.h"
#import "MMWebViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class CEnterpriseContact, MMTableViewInfo, MMTitleView, NSMutableArray, NSString;

@interface EnterpriseContactInfoViewController : MMUIViewController <EnterpriseMemberViewDelegate, MMWebViewDelegate, WCActionSheetDelegate, IEnterpriseGroupMgrExt>
{
    CEnterpriseContact *m_enterpriseContact;
    MMTableViewInfo *m_tableViewInfo;
    NSMutableArray *m_memberDataItemList;
    _Bool m_isMuteChanged;
    _Bool m_isFavoriteChanged;
    NSMutableArray *m_memberViewList;
    _Bool m_isChatStatusNotifyOpen;
    _Bool m_isFavorite;
    MMTitleView *m_titleView;
    unsigned int m_perColCnt;
    _Bool m_isDeleteButtonHidden;
}

- (void).cxx_destruct;
- (void)onUpdateEnterpriseGroupSetting:(id)arg1 errorCode:(int)arg2;
- (void)onUpdateEnterpriseGroupName:(id)arg1 errorCode:(int)arg2;
- (void)onUpdateEnterpriseGroupMemberList:(id)arg1 errorCode:(int)arg2;
- (void)onCreateEnterpriseGroup:(id)arg1 errorCode:(int)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)updateLocalContact:(id)arg1;
- (void)onWebViewWillClose:(id)arg1;
- (void)switchDeleteButtonHidden;
- (void)updateDeleteButtonHidden:(_Bool)arg1;
- (void)resetDeleteButtonHidden;
- (void)onEnterpriseMemberViewAdd:(id)arg1;
- (void)onEnterpriseMemberViewDelete:(id)arg1;
- (void)onEnterpriseMemberHeadImageLongPress:(id)arg1;
- (void)onEnterpriseMemberHeadImageClick:(id)arg1;
- (void)quitChatRoom;
- (void)onQuit:(id)arg1;
- (void)updateContactSetting;
- (void)makeMemberCell:(id)arg1 CellInfo:(id)arg2;
- (id)makeMemberListSection;
- (void)setChatRoomTopic:(id)arg1;
- (void)setFavStatus:(id)arg1;
- (void)setMuteStatus:(id)arg1;
- (void)showChangeTopicCell;
- (id)makeSettingSection;
- (id)makeChatRoomSection;
- (void)updateFooterView;
- (void)reloadTableData;
- (void)initView;
- (void)initData;
- (void)updateTitleView;
- (void)initTitleView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithEnterpriseContact:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

