//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMsgExt.h"
#import "INewSendMsgMgrExt.h"
#import "MMService.h"
#import "MessageWrapImgDelegate.h"
#import "OpenDownloadCDNMgrDelegate.h"
#import "UploadImageCDNMgrDelegate.h"

@class DownloadImageCDNMgr, MessagePatternCacheMgr, NSMutableDictionary, NSString, OpenDownloadCDNMgr, ThumbDownloadMgr, UploadImageCDNMgr;

@interface EnterpriseMsgMgr : MMService <MMService, MessageWrapImgDelegate, INewSendMsgMgrExt, UploadImageCDNMgrDelegate, OpenDownloadCDNMgrDelegate, IMsgExt>
{
    NSMutableDictionary *m_dicMsgDB;
    MessagePatternCacheMgr *m_oMessagePatternMgr;
    UploadImageCDNMgr *m_oUploadImageCdnMgr;
    DownloadImageCDNMgr *m_oDownloadImageCdnMgr;
    ThumbDownloadMgr *m_oThumbDownloadMgr;
    OpenDownloadCDNMgr *m_oOpenDownloadCDNMgr;
}

- (void).cxx_destruct;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)onDownOpenMsgModMsg:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3;
- (void)onUploadImageCheckQQ;
- (void)onUploadImageModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)onUploadImageModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3;
- (void)onNewSendMsg:(id)arg1 status:(unsigned int)arg2;
- (void)onModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3;
- (id)onGetMsg:(id)arg1 LocalID:(unsigned int)arg2 Wrap:(id)arg3;
- (void)onGetBigImageErrorWithWrap:(id)arg1;
- (void)onGetBigImageResultWithWrap:(id)arg1 image:(id)arg2 imageData:(id)arg3 isSaveImgOK:(_Bool *)arg4;
- (void)onUploadImageRequestWithWrap:(id)arg1;
- (void)CheckMessageStatus:(id)arg1 Msg:(id)arg2;
- (_Bool)InAppAttachDownloading:(id)arg1 MsgWrap:(id)arg2 AttachId:(id)arg3;
- (_Bool)IsImageMsgUploadIng:(id)arg1;
- (_Bool)isMsgWrapAtMe:(id)arg1;
- (void)HandleMsgList:(id)arg1 MsgList:(id)arg2;
- (void)mainThreadNotifyToExt:(id)arg1;
- (void)asyncOnDelMsg:(id)arg1 DelAll:(_Bool)arg2 brandUserName:(id)arg3;
- (void)asyncOnDelMsg:(id)arg1 brandUserName:(id)arg2;
- (void)asyncOnDelMsg:(id)arg1 MsgWrap:(id)arg2 brandUserName:(id)arg3;
- (void)asyncOnCheckQQ;
- (void)asyncOnAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2 Brand:(id)arg3;
- (void)asyncOnAddMsgForSession:(id)arg1 MsgWrap:(id)arg2 NewMsgArriveNotify:(_Bool)arg3 Brand:(id)arg4;
- (void)asyncOnAddMsgForSession:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)asyncOnModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)asyncOnAddMsg:(id)arg1 MsgWrap:(id)arg2 brand:(id)arg3;
- (void)asyncOnUnReadChange:(id)arg1 Brand:(id)arg2;
- (_Bool)InAppAttachDownloading:(id)arg1 MsgWrap:(id)arg2;
- (void)StopDownloadAppAttach:(id)arg1 MsgWrap:(id)arg2;
- (void)StartDownloadAppAttach:(id)arg1 MsgWrap:(id)arg2;
- (unsigned int)GetDownloadThumbStatus:(id)arg1;
- (_Bool)StartDownloadThumb:(id)arg1;
- (unsigned int)GetUploadPercent:(id)arg1;
- (unsigned int)GetDownloadImageTotalLen:(id)arg1;
- (unsigned int)GetDownloadImagePartLen:(id)arg1;
- (void)StopDownloadImage:(id)arg1 Brand:(id)arg2;
- (void)StartDownloadImage:(id)arg1 HD:(_Bool)arg2;
- (unsigned int)GetImgOrVideoMsgCount:(id)arg1 Brand:(id)arg2;
- (unsigned int)GetImgOrVideoMsgCount:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Brand:(id)arg4;
- (id)GetImgOrVideoNextMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Brand:(id)arg4;
- (id)GetImgOrVideoLastMsg:(id)arg1 Brand:(id)arg2;
- (id)GetImgOrVideoLastMsg:(id)arg1 FromID:(unsigned int)arg2 CreateTime:(unsigned int)arg3 Brand:(id)arg4;
- (id)GetImgAndVideoMsgList:(id)arg1 Brand:(id)arg2;
- (void)DelMsgPatten:(id)arg1;
- (void)AddMsgPattern:(id)arg1;
- (id)GetMsg:(id)arg1 LocalID:(unsigned int)arg2;
- (id)GetMsg:(id)arg1 LocalID:(unsigned int)arg2 Brand:(id)arg3;
- (id)GetEnterpriseMsgSource:(id)arg1;
- (unsigned int)GetUnReadCount:(id)arg1 Brand:(id)arg2;
- (id)GetFirstUnreadMsg:(id)arg1 Brand:(id)arg2;
- (id)GetLastMsg:(id)arg1 Brand:(id)arg2;
- (void)ResendMsg:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)ModMsgWithoutNotify:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)ModMsgByBitSet:(id)arg1 MsgWrap:(id)arg2 BitSet:(unsigned int)arg3 Brand:(id)arg4;
- (void)ModMsg:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)DelMsg:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)DelMsg:(id)arg1 MsgList:(id)arg2 DelAll:(_Bool)arg3 Brand:(id)arg4;
- (void)ClearUnReadForSync:(id)arg1 Brand:(id)arg2 CreateTime:(unsigned int)arg3;
- (void)ClearUnRead:(id)arg1 FromID:(unsigned int)arg2 ToID:(unsigned int)arg3 Brand:(id)arg4;
- (id)GetDownMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(unsigned int)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5 Brand:(id)arg6;
- (id)GetMsgByCreateTime:(id)arg1 FromID:(unsigned int)arg2 FromCreateTime:(unsigned int)arg3 Limit:(unsigned int)arg4 LeftCount:(unsigned int *)arg5 Brand:(id)arg6;
- (id)GetMsg:(id)arg1 FromID:(unsigned int)arg2 Limit:(unsigned int)arg3 LeftCount:(unsigned int *)arg4 LeftUnreadCount:(unsigned int *)arg5 Brand:(id)arg6;
- (void)AddMsg:(id)arg1 MsgWrap:(id)arg2 Brand:(id)arg3;
- (void)BatchAddEnterpriseMsgList:(id)arg1;
- (_Bool)SaveMsgThumb:(id)arg1 MsgWrap:(id)arg2;
- (_Bool)SaveMesImg:(id)arg1 MsgWrap:(id)arg2;
- (id)getMsgDB:(id)arg1;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

