//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CBaseContact, EnterpriseSessionSelectViewController;

@protocol EnterpriseSessionSelectViewControllerDelegate <NSObject>
- (void)OnEnterpriseSelectSession:(CBaseContact *)arg1 EnterpriseSessionSelectController:(EnterpriseSessionSelectViewController *)arg2;
@end

