//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIWindow.h"

#import "SightPlayerViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class FavSightFullScreenViewController, NSString, SightPlayerView, SimpleSightInfo, UILabel;

@interface FavSightWindow : MMUIWindow <WCActionSheetDelegate, SightPlayerViewDelegate>
{
    FavSightFullScreenViewController *m_viewController;
    SimpleSightInfo *m_sightInfo;
    SightPlayerView *m_playerView;
    UILabel *_tipsLabel;
    int _fullPlayTimes;
    _Bool _supportLandscape;
}

@property(nonatomic) _Bool supportLandscape; // @synthesize supportLandscape=_supportLandscape;
- (void).cxx_destruct;
- (_Bool)onPlayEnd:(_Bool)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)exitFullScreen:(id)arg1;
- (void)longPressFullScreenWindow:(id)arg1;
- (void)playSight;
- (void)layoutSubviews;
- (id)initWithSightInfo:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 sightInfo:(id)arg2;
- (void)internalInitWithSightInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

