//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "SightIconViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class CAGradientLayer, FavSightWindow, NSString, SightIconView, SightPlayerView, SimpleSightInfo;

@interface FavSightView : MMUIView <SightIconViewDelegate, WCActionSheetDelegate>
{
    SimpleSightInfo *m_sightInfo;
    FavSightWindow *m_sightWindow;
    SightPlayerView *m_playerView;
    id <FavSightViewDelegate> m_delegate;
    SightIconView *m_progressView;
    _Bool bIsSyncComplete;
    int m_currMaskType;
    _Bool fullScreenMode;
    CAGradientLayer *m_layer;
    _Bool _supportLandscape;
}

@property(nonatomic) _Bool supportLandscape; // @synthesize supportLandscape=_supportLandscape;
@property(retain, nonatomic) SightPlayerView *m_playerView; // @synthesize m_playerView;
@property(nonatomic) __weak id <FavSightViewDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onProgressEnd;
- (void)initCoverMask;
- (void)layoutSubviews;
- (void)setDownFail;
- (void)setDownFinsh;
- (void)setFinishedLength:(int)arg1 TotalLength:(int)arg2;
- (void)showCoverMask:(int)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)fullScreenPlay:(id)arg1;
- (void)onClickSight;
- (void)initView;
- (void)resize:(struct CGSize)arg1;
- (void)initPlayerView;
- (struct CGSize)getSightSizeWithMaxSize:(struct CGSize)arg1;
- (double)getSightHeight;
- (void)dealloc;
- (id)initWithFavDataSource:(id)arg1;
- (id)initWithSimpleSightInfo:(id)arg1 fullScreenMode:(_Bool)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

