//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingBaseViewController.h"

@class UISwitch;

@interface FeatureInfoLogViewController : SettingBaseViewController
{
    UISwitch *_featureInfoSwitch;
}

- (void).cxx_destruct;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)makeSwitchCell:(id)arg1 colName:(id)arg2 action:(SEL)arg3 on:(_Bool)arg4;
- (void)onFeatureLogSwitchChanged:(id)arg1;
- (void)viewDidLoad;
- (void)initView;
- (void)dealloc;

@end

