//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "FavForwardConfirmViewDelegate.h"
#import "IMsgRevokeExt.h"
#import "SessionSelectControllerDelegate.h"
#import "UIAlertViewDelegate.h"

@class CContact, CMessageWrap, FavForwardConfirmView, MMLoadingView, NSMutableArray, NSString, SessionSelectController;

@interface ForwardMessageLogicController : MMObject <FavForwardConfirmViewDelegate, SessionSelectControllerDelegate, IMsgRevokeExt, UIAlertViewDelegate>
{
    id <ForwardMessageLogicDelegate> m_delegate;
    CMessageWrap *m_messageWrap;
    NSMutableArray *m_msgList;
    CContact *m_toContact;
    int m_forwardScene;
    FavForwardConfirmView *m_favForwardConfirmView;
    MMLoadingView *m_loadingView;
    _Bool m_isPresent;
    SessionSelectController *m_sessionSelectController;
}

@property(nonatomic) int forwardScene; // @synthesize forwardScene=m_forwardScene;
@property(retain, nonatomic) CContact *toContact; // @synthesize toContact=m_toContact;
@property(retain, nonatomic) CMessageWrap *messageWrap; // @synthesize messageWrap=m_messageWrap;
@property(nonatomic) __weak id <ForwardMessageLogicDelegate> delegate; // @synthesize delegate=m_delegate;
- (void).cxx_destruct;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)OnMultiMsgForwardSendWithType:(unsigned long long)arg1;
- (void)OnFavItemForwardCancel;
- (void)OnFavItemForwardSend;
- (void)OnSelectSessionForRecord:(id)arg1;
- (void)OnSelectSessionReturn:(id)arg1;
- (void)dismissViewController;
- (void)showTips;
- (void)showContactSelectViewController;
- (void)forwardMultiMsgList:(id)arg1 andMessage:(id)arg2;
- (void)forwardMsgList:(id)arg1;
- (void)forwardMessage:(id)arg1 isPresent:(_Bool)arg2;
- (void)distributeMessage:(id)arg1 isPresent:(_Bool)arg2;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

