//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface FTSDetailPageSearchTask : MMObject
{
    NSString *_searchText;
    unsigned long long _bussinessType;
    NSString *_uniqueKey;
    unsigned int _offset;
}

@property(nonatomic) unsigned int offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *uniqueKey; // @synthesize uniqueKey=_uniqueKey;
@property(nonatomic) unsigned long long bussinessType; // @synthesize bussinessType=_bussinessType;
@property(retain, nonatomic) NSString *searchText; // @synthesize searchText=_searchText;
- (void).cxx_destruct;
- (id)init;
- (void)updateUniqueKey;

@end

