//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString, WCDataBase, WCDataBaseTable;

@interface FTSDB : NSObject
{
    NSString *_tokenizerName;
    WCDataBase *m_db;
    WCDataBaseTable *m_tableFav;
    NSDictionary *m_dicTableMessage;
    WCDataBaseTable *m_tableMsgUserNameID;
}

@property(retain, nonatomic) WCDataBaseTable *m_tableMsgUserNameID; // @synthesize m_tableMsgUserNameID;
@property(retain, nonatomic) NSDictionary *m_dicTableMessage; // @synthesize m_dicTableMessage;
@property(retain, nonatomic) WCDataBaseTable *m_tableFav; // @synthesize m_tableFav;
@property(retain, nonatomic) WCDataBase *m_db; // @synthesize m_db;
@property(readonly, nonatomic) NSString *tokenizerName; // @synthesize tokenizerName=_tokenizerName;
- (void).cxx_destruct;
- (void)closeDBBeforeInit;
- (void)closeDB;
- (_Bool)reloadDB;
- (_Bool)initDB;
- (void)dealloc;
- (id)init;

@end

