//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface FTSLogItem : NSObject
{
    int searchScene;
    int clickType;
    unsigned long long row;
    int clickSubType;
    unsigned long long bussinessRow;
    NSString *searchId;
    unsigned long long docId;
}

@property(nonatomic) unsigned long long docId; // @synthesize docId;
@property(retain, nonatomic) NSString *searchId; // @synthesize searchId;
@property(nonatomic) unsigned long long bussinessRow; // @synthesize bussinessRow;
@property(nonatomic) int clickSubType; // @synthesize clickSubType;
@property(nonatomic) unsigned long long row; // @synthesize row;
@property(nonatomic) int clickType; // @synthesize clickType;
@property(nonatomic) int searchScene; // @synthesize searchScene;
- (void).cxx_destruct;
- (id)genStatStringForSubSearch;
- (id)genStatString;
- (id)init;

@end

