//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FTSResultView.h"

#import "IFTSOnlineSearchMgr.h"

@class NSMutableArray, NSString;

@interface FTSOnlineDetailView : FTSResultView <IFTSOnlineSearchMgr>
{
    unsigned long long m_bussinessType;
    id <WCCommentDetailViewControllerFBDelegate> _wcCommentDelegate;
    NSMutableArray *_arrSnsCellInfo;
}

@property(retain, nonatomic) NSMutableArray *m_arrSnsCellInfo; // @synthesize m_arrSnsCellInfo=_arrSnsCellInfo;
@property(nonatomic) __weak id <WCCommentDetailViewControllerFBDelegate> m_wcCommentDelegate; // @synthesize m_wcCommentDelegate=_wcCommentDelegate;
- (void).cxx_destruct;
- (void)onFTSDetailPageResultChanged:(unsigned long long)arg1;
- (_Bool)hasSearchDone:(id)arg1;
- (id)getSearchArray:(id)arg1;
- (id)getSnsCellInfo:(unsigned int)arg1;
- (void)openTimeline:(id)arg1;
- (void)openPOI:(id)arg1;
- (void)openBrandFeeds:(id)arg1;
- (void)openBrandContactInfo:(id)arg1;
- (void)hideKeyboard;
- (void)pop;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)onLoadMore;
- (void)handleTextChanged:(id)arg1 immediately:(_Bool)arg2;
- (void)delaySearch:(id)arg1 slowMode:(_Bool)arg2;
- (void)delaySearchImp:(id)arg1;
- (id)getEmptyTipSuffix:(unsigned long long)arg1;
- (id)getSearchBarPlaceHolder:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithBussinessType:(unsigned long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

