//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "LocationRetrieveDelegate.h"
#import "PBMessageObserverDelegate.h"

@class CLLocation, FTSDetailPageSearchTask, LocationRetriever, NSMutableDictionary, NSString;

@interface FTSOnlineSearchMgr : MMObject <PBMessageObserverDelegate, LocationRetrieveDelegate>
{
    _Bool _isWorkingForHomePage;
    unsigned int _homePageEventId;
    NSString *_homePageSearchTextNow;
    NSMutableDictionary *_dicHomePageSearch;
    NSString *_newestHomePageSearchText;
    _Bool _isWorkingForDetailPage;
    unsigned int _detailPageEventId;
    FTSDetailPageSearchTask *_detailPageSearchTaskNow;
    NSMutableDictionary *_dicDetailPageSearch;
    NSString *_newestDetailPageSearchText;
    LocationRetriever *_locationRetriver;
    CLLocation *_location;
    unsigned int _safeRequestCnt;
    int _scene;
    NSMutableDictionary *_dicMatchUserList;
}

@property(retain, nonatomic) NSMutableDictionary *dicMatchUserList; // @synthesize dicMatchUserList=_dicMatchUserList;
@property(nonatomic) int scene; // @synthesize scene=_scene;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(retain, nonatomic) LocationRetriever *locationRetriver; // @synthesize locationRetriver=_locationRetriver;
@property(nonatomic) _Bool isWorkingForDetailPage; // @synthesize isWorkingForDetailPage=_isWorkingForDetailPage;
@property(retain, nonatomic) NSString *newestDetailPageSearchText; // @synthesize newestDetailPageSearchText=_newestDetailPageSearchText;
@property(retain, nonatomic) NSString *newestHomePageSearchText; // @synthesize newestHomePageSearchText=_newestHomePageSearchText;
- (void).cxx_destruct;
- (void)onRetrieveLocationTimeOut:(id)arg1;
- (void)onRetrieveLocationError:(int)arg1;
- (void)onRetrieveLocationOK:(id)arg1;
- (void)stopRetrievingLocation;
- (void)startRetrievingLocation;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (id)getBussinessItemForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2 index:(unsigned long long)arg3;
- (id)getBussinessResultForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (id)getBussinessItemsForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (unsigned long long)countOfBussinessItemForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (_Bool)hasSearchDoneForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (void)responseForSearchDetailPageResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)cancelSearchForDetailPage;
- (void)searchForDetailPage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (void)trySearchForDetailPage;
- (_Bool)shouldCarryUserList:(id)arg1;
- (_Bool)canSearchBussiness:(unsigned long long)arg1;
- (id)getBussinessResultForHomePage:(id)arg1 bussinessType:(unsigned long long)arg2;
- (id)getBussinessResultForHomePage:(id)arg1 index:(unsigned long long)arg2;
- (unsigned long long)countOfBussinessResultForHomePage:(id)arg1;
- (_Bool)hasSearchDoneForHomePage:(id)arg1;
- (void)responseForSearchHomePageResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)cancelSearchForHomePage;
- (void)searchForHomePage:(id)arg1;
- (void)trySearchForHomePage;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

