//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class MMUILabel, UIImageView, UIView;

@interface FTSWebSearchCell : UITableViewCell
{
    UIImageView *_searchIcon;
    UIView *_labelContentView;
    MMUILabel *_labelLeft;
    MMUILabel *_keyLabel;
    MMUILabel *_subTitleLabel;
}

+ (double)getCellHeight;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)updateWord:(id)arg1;
- (void)initView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

