//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface FTSWebSearchUtil : MMObject
{
}

+ (_Bool)isSameResourceSrc:(id)arg1;
+ (_Bool)setUpdateH5ResourceSrc:(id)arg1;
+ (id)getUpdateH5ResourceSrc;
+ (void)removeGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (void)removeAllGuideData;
+ (id)getSearchGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (_Bool)cacheGuideData:(id)arg1 forScene:(unsigned int)arg2 andVersion:(unsigned int)arg3;
+ (_Bool)shouldUpdateGuideDataForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (id)pathForGuideCacheForScene:(unsigned int)arg1 andVersion:(unsigned int)arg2;
+ (id)pathForGuideCacheForScene:(unsigned int)arg1;
+ (id)pathForGuideCache;
+ (id)pathForUpdatedSearchGuideH5;
+ (id)pathForDefaultSearchGuideH5;
+ (id)pathForGuideCacheDir;
+ (id)makeDictionaryFromPath:(id)arg1;
+ (void)reloadDownloadConfig;
+ (void)reloadDefaultConfig;
+ (unsigned int)getVersionForUpdateH5;
+ (unsigned int)getVersionForDefaultH5;
+ (id)pathForUpdatedGuidePage;
+ (id)pathForUpdatedH5;
+ (id)pathForUpdatedH5Dir;
+ (id)pathForH5Root;
+ (id)pathForDefaultH5;
+ (id)pathForGuideH5;
+ (id)pathForMainH5;
+ (unsigned int)getVersion;
+ (_Bool)isUpdatedGuidePageExist;
+ (_Bool)isUpdatedH5Exist;

@end

