//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMSnsGameListCellView, NSString, SnsGameMsg;

@protocol GameMsgCellViewDelegate <NSObject>
- (void)onTouchDefaultView:(SnsGameMsg *)arg1;
- (void)onImageClicked:(SnsGameMsg *)arg1 originView:(MMSnsGameListCellView *)arg2;
- (void)onActionBtnClicked:(SnsGameMsg *)arg1;
- (void)onUrlClicked:(NSString *)arg1 gameMsgItem:(SnsGameMsg *)arg2;
- (void)onAppNameClicked:(NSString *)arg1 gameMsgItem:(SnsGameMsg *)arg2;
@end

