//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "MMWebImageViewDelegate.h"

@class GameCenterGameAdInfo, MMWebImageView, NSString, UIButton, UILabel, UIView;

@interface GameCenterAdView : MMUIView <MMWebImageViewDelegate>
{
    MMWebImageView *_backgroundImageView;
    UIButton *_gameInfoButton;
    UIView *_friendInfoView;
    UIButton *_downloadButton;
    MMWebImageView *_gameInfoBackgroundView;
    MMWebImageView *_downloadButtonBackgroundView;
    MMWebImageView *_downloadButtonHighlightedBackgroundView;
    MMWebImageView *_iconView;
    UILabel *_nameLabel;
    UILabel *_descLabel;
    UILabel *_remarkLabel;
    GameCenterGameAdInfo *_gameAdInfo;
    id <GameCenterAdViewDelegate> _delegate;
}

@property(nonatomic) __weak id <GameCenterAdViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GameCenterGameAdInfo *gameAdInfo; // @synthesize gameAdInfo=_gameAdInfo;
- (void).cxx_destruct;
- (void)onLoadImageOK:(id)arg1;
- (void)onDownloadButtonClicked;
- (void)onGameInfoButtonClicked;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (double)downloadButtonCenterY;
- (double)gameInfoViewCenterY;
- (void)resizeBackgroundImageView;
- (void)layoutContent;
- (id)createGameInfoButtonWithFrame:(struct CGRect)arg1;
- (void)reloadData;
- (void)initializeSubviews;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

