//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface GameDebugPropertyItem : NSObject
{
    NSString *_label;
    unsigned long long _type;
    long long _value;
    id _valueObject;
}

@property(retain, nonatomic) id valueObject; // @synthesize valueObject=_valueObject;
@property(nonatomic) long long value; // @synthesize value=_value;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (_Bool)showInWebView;
- (id)text;
- (id)initWithLabel:(id)arg1 object:(id)arg2 type:(unsigned long long)arg3;
- (id)initWithLabel:(id)arg1 value:(long long)arg2 type:(unsigned long long)arg3;

@end

