//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface GameCenterMsgTips : MMObject <PBCoding>
{
    unsigned int newCount;
    unsigned int lastUpdateTime;
}

+ (void)initialize;
@property(nonatomic) unsigned int lastUpdateTime; // @synthesize lastUpdateTime;
@property(nonatomic) unsigned int newCount; // @synthesize newCount;
- (id)pathForGameCenterMsgTips;
- (void)loadGameCenterMsgTipsFromCache;
- (void)saveGameCenterMsgTipsToCache;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

