//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class WCDataBase, WCDataBaseTable;

@interface GameCenterDB : MMObject
{
    WCDataBase *_dbBase;
    WCDataBaseTable *_normalMsgTable;
    WCDataBaseTable *_wxTeamMsgTable;
}

- (void).cxx_destruct;
- (_Bool)setWXTeamAllMsgRead;
- (unsigned int)insertOrUpdateWXTeamMsg:(id)arg1;
- (id)getWXTeamMsgFromLocalID:(unsigned int)arg1 maxCount:(_Bool)arg2;
- (unsigned int)getWXTeamMsgUnreadCount;
- (void)setNormalAllMsgRead;
- (unsigned int)insertOrUpdateNormalMsg:(id)arg1;
- (id)getNormalMsgFormLocalID:(unsigned int)arg1 maxCount:(_Bool)arg2;
- (unsigned int)getNormalMsgUnreadCount;
- (void)dealloc;
- (id)init;

@end

