//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class NSString;

@interface GameCenterGameVideoItem : MMObject <PBCoding>
{
    NSString *videoURL;
    NSString *thumbnailURL;
}

+ (void)initialize;
@property(retain, nonatomic) NSString *thumbnailURL; // @synthesize thumbnailURL;
@property(retain, nonatomic) NSString *videoURL; // @synthesize videoURL;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)isValid;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

