//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface GameEntryNotifyInfo : MMObject
{
    unsigned int _validUntil;
    NSString *_appID;
    NSString *_notifyIconURL;
    NSString *_notifyText;
    unsigned long long _notifyType;
}

@property(readonly, nonatomic) unsigned int validUntil; // @synthesize validUntil=_validUntil;
@property(nonatomic) unsigned long long notifyType; // @synthesize notifyType=_notifyType;
@property(retain, nonatomic) NSString *notifyText; // @synthesize notifyText=_notifyText;
@property(retain, nonatomic) NSString *notifyIconURL; // @synthesize notifyIconURL=_notifyIconURL;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (void)setValidUntilWithExpireInterval:(unsigned int)arg1;
- (void)dealloc;

@end

