//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBCoding.h"

@class GameCenterNewFeedItem, GameCenterUserInfo, NSArray, NSString;

@interface GameCenterHomeData : MMObject <PBCoding>
{
    _Bool bShowLibraryEntrance;
    _Bool bShowProfile;
    _Bool searchEntry;
    _Bool showNearestFeeds;
    GameCenterUserInfo *userInfo;
    NSArray *recentGames;
    NSArray *feedItems;
    NSString *feedsTitle;
    NSString *promotionTitle;
    NSArray *promotedGames;
    NSString *libraryURL;
    NSString *giftURL;
    NSString *welcomeMessage;
    NSString *giftEntranceTitle;
    NSString *libraryEntranceTitle;
    NSString *searchPlaceholder;
    NSString *productID;
    GameCenterNewFeedItem *feedNewItem;
    NSArray *activeAppIdList;
    NSArray *keyGameList;
}

+ (void)initialize;
@property(retain, nonatomic) NSArray *keyGameList; // @synthesize keyGameList;
@property(retain, nonatomic) NSArray *activeAppIdList; // @synthesize activeAppIdList;
@property(nonatomic) _Bool showNearestFeeds; // @synthesize showNearestFeeds;
@property(retain, nonatomic) GameCenterNewFeedItem *feedNewItem; // @synthesize feedNewItem;
@property(retain, nonatomic) NSString *productID; // @synthesize productID;
@property(retain, nonatomic) NSString *searchPlaceholder; // @synthesize searchPlaceholder;
@property(nonatomic) _Bool searchEntry; // @synthesize searchEntry;
@property(retain, nonatomic) NSString *libraryEntranceTitle; // @synthesize libraryEntranceTitle;
@property(retain, nonatomic) NSString *giftEntranceTitle; // @synthesize giftEntranceTitle;
@property(retain, nonatomic) NSString *welcomeMessage; // @synthesize welcomeMessage;
@property(nonatomic) _Bool bShowProfile; // @synthesize bShowProfile;
@property(retain, nonatomic) NSString *giftURL; // @synthesize giftURL;
@property(nonatomic) _Bool bShowLibraryEntrance; // @synthesize bShowLibraryEntrance;
@property(retain, nonatomic) NSString *libraryURL; // @synthesize libraryURL;
@property(retain, nonatomic) NSArray *promotedGames; // @synthesize promotedGames;
@property(retain, nonatomic) NSString *promotionTitle; // @synthesize promotionTitle;
@property(retain, nonatomic) NSString *feedsTitle; // @synthesize feedsTitle;
@property(retain, nonatomic) NSArray *feedItems; // @synthesize feedItems;
@property(retain, nonatomic) NSArray *recentGames; // @synthesize recentGames;
@property(retain, nonatomic) GameCenterUserInfo *userInfo; // @synthesize userInfo;
- (void).cxx_destruct;
- (void)dealloc;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

