//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIWindow.h"

#import "GameCenterAdViewDelegate.h"

@class GameCenterAdView, GameCenterGameAdInfo, NSString;

@interface GameCenterPopAdView : MMUIWindow <GameCenterAdViewDelegate>
{
    GameCenterAdView *_adView;
    id <GameCenterPopAdViewDelegate> _userDelegate;
    GameCenterGameAdInfo *_gameAdInfo;
}

@property(retain, nonatomic) GameCenterGameAdInfo *gameAdInfo; // @synthesize gameAdInfo=_gameAdInfo;
@property(nonatomic) __weak id <GameCenterPopAdViewDelegate> userDelegate; // @synthesize userDelegate=_userDelegate;
- (void).cxx_destruct;
- (void)onGameInfoButtonClicked;
- (void)onDownloadButtonClicked;
- (void)closeButtonPressed;
- (id)initializeCloseButtonWithAdViewFrame:(struct CGRect)arg1;
- (void)initAdView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

