//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface GameCenterMsgGiftInfo : NSObject <PBCoding>
{
    _Bool shouldShowGameCenterEntry;
    _Bool shouldShowGiftCenterEntry;
    unsigned int expiredTime;
    unsigned int createTime;
    unsigned int displayCount;
    NSString *noticeID;
    NSString *appID;
}

+ (void)initialize;
@property(nonatomic) unsigned int displayCount; // @synthesize displayCount;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
@property(nonatomic) unsigned int createTime; // @synthesize createTime;
@property(retain, nonatomic) NSString *noticeID; // @synthesize noticeID;
@property(nonatomic) _Bool shouldShowGiftCenterEntry; // @synthesize shouldShowGiftCenterEntry;
@property(nonatomic) _Bool shouldShowGameCenterEntry; // @synthesize shouldShowGameCenterEntry;
@property(nonatomic) unsigned int expiredTime; // @synthesize expiredTime;
- (void).cxx_destruct;
- (_Bool)isValid;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

