//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface GameMsgBubbleInfo : MMObject
{
    unsigned int _createTime;
    unsigned int _expiredTime;
    NSString *_appID;
    NSString *_iconURL;
    NSString *_bubbleText;
    unsigned long long _actionType;
}

@property(nonatomic) unsigned int expiredTime; // @synthesize expiredTime=_expiredTime;
@property(nonatomic) unsigned int createTime; // @synthesize createTime=_createTime;
@property(nonatomic) unsigned long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *bubbleText; // @synthesize bubbleText=_bubbleText;
@property(retain, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(retain, nonatomic) NSString *appID; // @synthesize appID=_appID;
- (void).cxx_destruct;
- (_Bool)isValid;
- (void)dealloc;

@end

