//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCDBCoding.h"

@class NSMutableArray, NSString;

@interface GameCenterMsg : MMObject <WCDBCoding>
{
    unsigned int localID;
    unsigned int status;
    unsigned int createTime;
    unsigned int msgType;
    unsigned int msgActionType;
    unsigned int groupID;
    unsigned long long svr64ID;
    NSString *imageURL;
    NSString *title;
    NSString *subTitle;
    NSString *mediaUrl;
    NSMutableArray *subMsgList;
    NSString *timeTitle;
    NSString *leftTitle;
    NSString *rightTitle;
    NSString *webUrl;
    NSString *appID;
}

+ (id)dummyObject;
+ (void)initialize;
@property(retain, nonatomic) NSString *appID; // @synthesize appID;
@property(retain, nonatomic) NSString *webUrl; // @synthesize webUrl;
@property(retain, nonatomic) NSString *rightTitle; // @synthesize rightTitle;
@property(retain, nonatomic) NSString *leftTitle; // @synthesize leftTitle;
@property(retain, nonatomic) NSString *timeTitle; // @synthesize timeTitle;
@property(retain, nonatomic) NSMutableArray *subMsgList; // @synthesize subMsgList;
@property(retain, nonatomic) NSString *mediaUrl; // @synthesize mediaUrl;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) NSString *imageURL; // @synthesize imageURL;
@property(nonatomic) unsigned int groupID; // @synthesize groupID;
@property(nonatomic) unsigned int msgActionType; // @synthesize msgActionType;
@property(nonatomic) unsigned int msgType; // @synthesize msgType;
@property(nonatomic) unsigned int createTime; // @synthesize createTime;
@property(nonatomic) unsigned long long svr64ID; // @synthesize svr64ID;
@property(nonatomic) unsigned int status; // @synthesize status;
@property(nonatomic) unsigned int localID; // @synthesize localID;
- (void).cxx_destruct;
- (void)parseMsgXML:(id)arg1;
- (void)dealloc;
- (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long long)getWCDBIndexArrayCount;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const map_0e718273 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_0e718273 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_7a576766 *)getValueNameIndexMap;
- (id)getValueTable;
- (const WCDBCondition_22fabacd *)db_appID;
- (const WCDBCondition_22fabacd *)db_webUrl;
- (const WCDBCondition_22fabacd *)db_rightTitle;
- (const WCDBCondition_22fabacd *)db_leftTitle;
- (const WCDBCondition_22fabacd *)db_timeTitle;
- (const WCDBCondition_22fabacd *)db_mediaUrl;
- (const WCDBCondition_22fabacd *)db_subTitle;
- (const WCDBCondition_22fabacd *)db_title;
- (const WCDBCondition_22fabacd *)db_imageURL;
- (const WCDBCondition_c6db074e *)db_groupID;
- (const WCDBCondition_c6db074e *)db_msgActionType;
- (const WCDBCondition_c6db074e *)db_msgType;
- (const WCDBCondition_c6db074e *)db_createTime;
- (const WCDBCondition_7786cbb5 *)db_svr64ID;
- (const WCDBCondition_c6db074e *)db_status;
- (const WCDBCondition_c6db074e *)db_localID;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

