//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBase, WCDataBaseTable;

@interface GameMsgDB : NSObject
{
    WCDataBase *m_db;
    WCDataBaseTable *m_table;
}

@property(retain, nonatomic) WCDataBaseTable *m_table; // @synthesize m_table;
@property(retain, nonatomic) WCDataBase *m_db; // @synthesize m_db;
- (void).cxx_destruct;
- (id)getMsgByMsgType:(unsigned long long)arg1 appID:(id)arg2 beginTime:(unsigned long long)arg3 maxCount:(unsigned long long)arg4;
- (id)DBContext;
- (id)getXmlContentByLocalMsgID:(unsigned int)arg1;
- (_Bool)deleteAllVisibleMsgs;
- (_Bool)updateDisplayCount:(id)arg1 to:(unsigned int)arg2;
- (_Bool)setAllBubbleMsgRead;
- (id)getLastUnreadBubbleMsg;
- (id)getGameMsgByPushMsgID:(id)arg1;
- (_Bool)clearTheEarlyMsg;
- (_Bool)hasUnreadMessages;
- (_Bool)getTheEarlyMsgIDs:(id)arg1;
- (id)getLastUnreadMsg;
- (id)getUnreadMsgList;
- (_Bool)setAllMsgRead;
- (unsigned int)getUnreadMessageCount;
- (_Bool)setMsgStatusDeletedByMsgID:(unsigned int)arg1;
- (_Bool)getDeletedMsgIDList:(id)arg1;
- (id)getGameMsgByMsgID:(unsigned int)arg1;
- (_Bool)getNextPageNeedBatchGetMsgIDList:(id)arg1 byCurMinUpdateTime:(unsigned int)arg2;
- (_Bool)getNextPageMsgList:(id)arg1 byCurMinUpdateTime:(unsigned int)arg2 HasSmaller:(_Bool *)arg3;
- (_Bool)getNeedBatchGetMsgIDList:(id)arg1 byMinUpdateTime:(unsigned int)arg2;
- (_Bool)getFirstPageNeedBatchGetMsgIDList:(id)arg1;
- (_Bool)getFirstPageMsgList:(id)arg1;
- (_Bool)insertMsg:(id)arg1 XMLObject:(id)arg2;
- (_Bool)deleteGameMsgByLocalMsgID:(unsigned int)arg1;
- (_Bool)deleteGameMsgByMsgID:(unsigned int)arg1;
- (void)setSnsGameMsg:(id)arg1 withGameMsgDBItem:(id)arg2;
- (void)closeDBBeforeInit;
- (void)closeDB;
- (_Bool)initDB;
- (void)reloadDataBase;
- (void)dealloc;
- (id)init;

@end

