//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "GameCenterAdViewDelegate.h"

@class GameCenterGameAdInfo, NSString, NSTimer;

@interface GameCenterAdViewController : MMUIViewController <GameCenterAdViewDelegate>
{
    GameCenterGameAdInfo *_gameAdInfo;
    NSTimer *_dismissTimer;
    id <GameCenterAdViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <GameCenterAdViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stopDismissTimer;
- (void)autoDismiss;
- (void)startDismissTimerWithInterval:(double)arg1;
- (void)onDownloadButtonClicked;
- (void)onGameInfoButtonClicked;
- (void)onCancel;
- (void)initializeSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithGameAdInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

