//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BakChatUploadMessage, NSMutableDictionary;

@protocol IBakChatUploadMgrExt <NSObject>

@optional
- (void)OnGetSessionSize:(NSMutableDictionary *)arg1;
- (void)OnBakChatUploadMessage:(BakChatUploadMessage *)arg1;
@end

