//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@protocol IBakChatRecoverMgrExt <NSObject>

@optional
- (void)OnDecryptError;
- (void)OnCancel;
- (void)OnRecoverProcessFileProgress:(unsigned int)arg1 WithTotalCount:(unsigned int)arg2;
- (void)OnRecoverProgress:(unsigned int)arg1 WithTotalCount:(unsigned int)arg2;
- (void)OnSuccess;
- (void)OnError:(unsigned int)arg1;
- (void)OnRestart;
- (void)OnPause;
- (void)OnDownloaded;
- (void)OnDownloadProgress:(unsigned int)arg1 WithTotalSize:(unsigned int)arg2;
- (void)OnGetChatList:(NSArray *)arg1;
@end

