//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString;

@protocol IDeviceRankSnsMgrExt

@optional
- (void)onGotUserRankList:(NSString *)arg1 aryUserRankList:(NSArray *)arg2 aryLikeMeList:(NSArray *)arg3 aryAffectedUserList:(NSArray *)arg4 championCoverUrl:(NSString *)arg5 championMotto:(NSString *)arg6 jumpChampionUrl:(NSString *)arg7 shareUrl:(NSString *)arg8 isCacheExist:(_Bool)arg9 shareTitle:(NSString *)arg10 err:(int)arg11;
- (void)onLikeFriendRank:(NSString *)arg1 err:(int)arg2;
@end

