//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSMutableArray, NSString;

@protocol IGameFacadeExt

@optional
- (void)onGetUserRankListFail:(unsigned int)arg1 appID:(NSString *)arg2;
- (void)onGetUserRankListSuccess:(NSString *)arg1 count:(unsigned long long)arg2 hasReportScore:(_Bool)arg3;
- (void)onGetNextPageGameMsgList:(NSArray *)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3;
- (void)onGetFirstPageGameMsgList:(NSArray *)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3 HasBatchGetting:(_Bool)arg4;
- (void)onGameEntryChanged;
- (void)onGameAdInfoChanged;
- (void)onGameGiftInfoChanged;
- (void)onNewGameMsgsUpdate:(NSArray *)arg1;
- (void)onGameNewAppCountChanged;
- (void)onGameMessageUnReadCountChanged;
- (void)onGotBizAppInfo;
- (void)onUpdateGamePersonalInfoList;
- (void)onGotGameIntroList:(NSMutableArray *)arg1 errType:(int)arg2;
@end

