//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GameCenterDetailInfo, GameCenterHomeData, GameCenterWebResourceListInfo, GameLibraryAppInfo, GameMoreGameInfo, NSArray, NSString;

@protocol IGameCenterExt <NSObject>

@optional
- (void)onGameSetBlockState:(_Bool)arg1 appID:(NSString *)arg2 error:(long long)arg3;
- (void)onGameGetBlockState:(_Bool)arg1 appID:(NSString *)arg2 error:(long long)arg3;
- (void)onGameSearchEntryStatusChange:(_Bool)arg1 placeholder:(NSString *)arg2;
- (void)onGameSearchSmartBox:(NSString *)arg1 returnKeywords:(NSArray *)arg2 error:(long long)arg3;
- (void)onGameSearchFinishedWithResultGroups:(NSArray *)arg1 searchWithText:(NSString *)arg2 error:(long long)arg3;
- (void)onGetAllGameList:(NSArray *)arg1 error:(long long)arg2;
- (void)onSubscribeNewGameWithAppID:(NSString *)arg1 alertTitle:(NSString *)arg2 message:(NSString *)arg3 error:(long long)arg4;
- (void)onGetMoreGameList:(GameMoreGameInfo *)arg1 classifyID:(NSString *)arg2 errCode:(int)arg3;
- (void)onGetLibGameList:(GameLibraryAppInfo *)arg1 errCode:(int)arg2;
- (void)onUpdateGameList:(NSArray *)arg1 type:(unsigned long long)arg2 error:(long long)arg3 hasMore:(_Bool)arg4;
- (void)onGetNextPageOfGameList:(NSArray *)arg1 type:(unsigned long long)arg2 error:(long long)arg3 hasMore:(_Bool)arg4;
- (void)onNewGameAdChanged;
- (void)onGetUserRankListFail:(unsigned int)arg1 appID:(NSString *)arg2;
- (void)onGetUserRankListSuccess:(NSString *)arg1 count:(unsigned long long)arg2 hasReportScore:(_Bool)arg3;
- (void)onGetGameResourceListInfo:(GameCenterWebResourceListInfo *)arg1 appID:(NSString *)arg2 offset:(unsigned long long)arg3;
- (void)onGetUpList:(NSArray *)arg1 appID:(NSString *)arg2 errCode:(int)arg3;
- (void)onUpFriend:(NSString *)arg1 appID:(NSString *)arg2 errCode:(int)arg3;
- (void)onGetGameDetailInfo:(GameCenterDetailInfo *)arg1 errCode:(long long)arg2;
- (void)onFetchGameCenterHomeData:(GameCenterHomeData *)arg1 error:(long long)arg2;
@end

