//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface LinkSpreadUtil : MMObject
{
}

+ (void)logLinkSpead:(id)arg1 currId:(id)arg2 preUserName:(id)arg3 preChatUserName:(id)arg4 currUrl:(id)arg5 preMsgIndex:(unsigned int)arg6;
+ (void)logLinkSpead:(id)arg1 currId:(id)arg2 preUserName:(id)arg3 preChatUserName:(id)arg4 currUrl:(id)arg5 preMsgIndex:(unsigned int)arg6 currChatName:(id)arg7 currChatTitle:(id)arg8 currChatMemberCount:(unsigned int)arg9 sendAppMsgScene:(unsigned int)arg10;
+ (void)logLinkSpead:(id)arg1;
+ (id)getDicStatParas:(id)arg1 currUrl:(id)arg2 preMsgIndex:(unsigned int)arg3 sendMsgScene:(int)arg4;

@end

