//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMLoadingView, MMTableView, NSArray, NSString;

@interface ListQQFriendGroupViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, PBMessageObserverDelegate, UIAlertViewDelegate>
{
    MMTableView *m_tableView;
    MMLoadingView *m_loadingView;
    unsigned int m_uiViewControllerType;
    NSArray *m_arrQQGroupWrap;
}

@property(retain, nonatomic) NSArray *m_arrQQGroupWrap; // @synthesize m_arrQQGroupWrap;
- (void).cxx_destruct;
- (void)dealloc;
- (id)init;
- (id)initWithVCType:(unsigned int)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initView;
- (void)initData;
- (void)LoadQQGroup;
- (void)SaveQQGroup;
- (void)CheckQQGroupNeedReload:(id)arg1;
- (void)LoadQQGroupNetworkEvent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

