//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIActionSheet.h"

#import "UIActionSheetDelegate.h"

@class NSMutableArray, NSString, UIView;

@interface MMActionSheet : MMUIActionSheet <UIActionSheetDelegate>
{
    NSString *_cancelButtonTitle;
    NSMutableArray *_buttonTitleList;
    UIView *_pannelView;
    UIView *_titleView;
    id <UIActionSheetDelegate> _delegateEx;
    NSString *_titleEx;
    long long _destructiveButtonIndexEx;
    long long _firstOtherButtonIndexEx;
    long long _cancelButtonIndexEx;
    long long _m_lastOrientation;
}

+ (_Bool)isUseIOS6StyleActionsheetForIOS7;
+ (long long)getActionSheetWidth;
@property(nonatomic) long long m_lastOrientation; // @synthesize m_lastOrientation=_m_lastOrientation;
@property(nonatomic) long long cancelButtonIndexEx; // @synthesize cancelButtonIndexEx=_cancelButtonIndexEx;
@property(nonatomic) long long firstOtherButtonIndexEx; // @synthesize firstOtherButtonIndexEx=_firstOtherButtonIndexEx;
@property(nonatomic) long long destructiveButtonIndexEx; // @synthesize destructiveButtonIndexEx=_destructiveButtonIndexEx;
@property(copy, nonatomic) NSString *titleEx; // @synthesize titleEx=_titleEx;
@property(nonatomic) __weak id <UIActionSheetDelegate> delegateEx; // @synthesize delegateEx=_delegateEx;
@property(retain, nonatomic) UIView *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) UIView *pannelView; // @synthesize pannelView=_pannelView;
@property(retain, nonatomic) NSMutableArray *buttonTitleList; // @synthesize buttonTitleList=_buttonTitleList;
@property(retain, nonatomic) NSString *cancelButtonTitle; // @synthesize cancelButtonTitle=_cancelButtonTitle;
- (void).cxx_destruct;
- (void)onExit;
- (void)OnCancel:(id)arg1;
- (void)OnDefaultButtonTapped:(id)arg1;
- (void)reloadInnerView:(id)arg1;
- (void)reloadInnerView;
- (void)showFromToolbar:(id)arg1;
- (void)showFromTabBar:(id)arg1;
- (void)showFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(_Bool)arg3;
- (void)showFromBarButtonItem:(id)arg1 animated:(_Bool)arg2;
- (void)showInView:(id)arg1;
- (void)addTapRecognizer;
- (void)tapOut:(id)arg1;
- (void)dismissWithClickedButtonIndex:(long long)arg1 animated:(_Bool)arg2;
- (void)setDestructiveButtonIndex:(long long)arg1;
- (long long)destructiveButtonIndex;
- (void)setCancelButtonIndex:(long long)arg1;
- (long long)cancelButtonIndex;
- (long long)firstOtherButtonIndex;
- (id)buttonTitleAtIndex:(long long)arg1;
- (long long)numberOfButtons;
- (long long)addButtonWithTitle:(id)arg1;
- (void)setDelegate:(id)arg1;
- (id)delegate;
- (void)setTitle:(id)arg1;
- (id)title;
- (id)initWithTitle:(id)arg1 delegate:(id)arg2 cancelButtonTitle:(id)arg3 destructiveButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;
- (id)init;
- (id)makePannelViewWithButtonList:(id)arg1 withCancelButtonTitle:(id)arg2;
- (id)makeTitleViewWithTitle:(id)arg1;
- (double)heightOfWholeSheet;
- (void)setFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

