//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface MMAlbumDataProvider : MMObject
{
}

+ (id)getAlbumSortEndDateFromAlbumType:(long long)arg1 ForSubType:(long long)arg2 shouldIncludeVideo:(_Bool)arg3;
+ (id)getAlbumFromAlbumType:(long long)arg1 ForSubType:(long long)arg2 shouldIncludeVideo:(_Bool)arg3;
+ (void)AllMMAlbumsForPHFrameworkWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3;
+ (void)AllMMAlbumsForAssetLibrbaryWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3;
+ (_Bool)isAuthorize;
+ (void)AllMMAlbumsWith:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2 shouldIncludeVideo:(_Bool)arg3;

@end

