//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MMDumpReporterDelegate.h"
#import "MMDumpReporterExt.h"
#import "MMPickerViewDelegate.h"

@class MMPickerView, NSMutableArray, NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UISwitch, UITextField, UIView;

@interface MMCheckDumpViewController : MMUIViewController <MMDumpReporterDelegate, MMDumpReporterExt, MMPickerViewDelegate>
{
    UITextField *m_textFiled;
    unsigned long long m_nTimeInterval;
    UIActivityIndicatorView *m_activityView;
    NSMutableArray *m_arrDates;
    long long m_selectedRow;
    UIView *textView;
    UIView *roundView;
    UILabel *m_tipLabel;
    UILabel *m_checklabel;
    UISwitch *m_checkSitchView;
    UIButton *m_btnDate;
    UIButton *m_btndump;
    UILabel *warningLabel;
    UIImageView *imgvRecover;
    MMPickerView *m_pickerView;
    _Bool m_isUploading;
    _Bool m_isFinish;
}

- (void).cxx_destruct;
- (void)onUploadResult:(_Bool)arg1;
- (void)MMPickerViewDidChooseRow:(long long)arg1 atSession:(long long)arg2;
- (void)onChoseDate;
- (void)initViewAfterUploadingSuccessfully;
- (void)initViewOnUploading;
- (void)onUploadDump;
- (void)onSwitchValueChange:(id)arg1;
- (void)viewDidLoad;
- (void)initData;
- (void)initView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

