//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface MMDumpReportTaskData : NSObject
{
    unsigned long long m_reportCntOneTime;
    NSString *m_nsTag;
    NSArray *m_arrUploadFiles;
    NSArray *m_arrUploadCPUFiles;
    NSArray *m_arrUploadBackgroundFiles;
}

@property(retain, nonatomic) NSArray *m_arrUploadBackgroundFiles; // @synthesize m_arrUploadBackgroundFiles;
@property(retain, nonatomic) NSArray *m_arrUploadCPUFiles; // @synthesize m_arrUploadCPUFiles;
@property(retain, nonatomic) NSArray *m_arrUploadFiles; // @synthesize m_arrUploadFiles;
@property(retain, nonatomic) NSString *m_nsTag; // @synthesize m_nsTag;
@property(nonatomic) unsigned long long m_reportCntOneTime; // @synthesize m_reportCntOneTime;
- (void).cxx_destruct;

@end

