//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "EmoticonBackupOperateMgrExt.h"
#import "EmoticonDescMgrExt.h"
#import "EmoticonStoreCellDelegate.h"
#import "EmoticonStoreItemExt.h"
#import "EmoticonStoreMgrExt.h"
#import "IEmoticonDownloadExt.h"
#import "IMsgRevokeExt.h"
#import "MMImgageBrowseViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class CEmoticonWrap, CMessageWrap, EmoticonStoreItem, MMAnimationTipView, MMImageBrowseView, MMStoreEmotionAllCell, NSMutableArray, NSString, UICollectionView, UIView, WCActionSheet;

@interface MMEmotionMsgBrowseViewController : MMUIViewController <EmoticonBackupOperateMgrExt, UICollectionViewDataSource, UICollectionViewDelegate, EmoticonStoreMgrExt, EmoticonStoreCellDelegate, MMImgageBrowseViewDelegate, WCActionSheetDelegate, EmoticonStoreItemExt, EmoticonDescMgrExt, IEmoticonDownloadExt, IMsgRevokeExt, UIAlertViewDelegate>
{
    MMImageBrowseView *m_imageView;
    MMAnimationTipView *m_tipView;
    CMessageWrap *m_wrapMsg;
    CEmoticonWrap *m_wrapEmoticon;
    id m_singleTapOnNav;
    EmoticonStoreItem *m_item;
    WCActionSheet *m_actionSheet;
    UIView *_containerView;
    MMImageBrowseView *_storeEmotionImageView;
    UICollectionView *_recommendedCollectionView;
    NSMutableArray *_recommendedArray;
    _Bool _isLoadedFromCache;
    MMStoreEmotionAllCell *_emotionCell;
}

@property(retain, nonatomic) EmoticonStoreItem *m_item; // @synthesize m_item;
@property(retain, nonatomic) id m_singleTapOnNav; // @synthesize m_singleTapOnNav;
- (void).cxx_destruct;
- (void)OnShowAlertWithIKnow:(id)arg1;
- (void)OnShowAlertWithOK:(id)arg1;
- (void)OnStopLoading;
- (void)OnStartLoadingAndShowStringBlocked:(id)arg1;
- (void)OnStopLoadingAndShowError:(id)arg1;
- (void)OnStopLoadingAndShowOK:(id)arg1;
- (void)OnStartLoadingAndShowString:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)OnStoreListChanged:(id)arg1 withRet:(int)arg2 withReqType:(unsigned int)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)onAddBackupEmoticonFailed:(id)arg1 isOverLimit:(_Bool)arg2;
- (void)onAddBackupEmoticonOK:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)OnMsgRevoked:(id)arg1 n64MsgId:(long long)arg2 SysMsg:(id)arg3;
- (void)OnEmoticonDownload:(unsigned int)arg1 withMsgWrap:(id)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onSingleTapImageBrowseView;
- (void)OnEmoticonStoreItemChanged:(id)arg1;
- (void)onGetEmoticonClickFlag:(unsigned int)arg1 downloadFlag:(unsigned int)arg2 pid:(id)arg3;
- (void)onGetEmoticonClickFlag:(unsigned int)arg1 pid:(id)arg2;
- (void)onPurchase:(id)arg1;
- (void)onSaveEmoticon:(id)arg1;
- (void)jumpToEmotionPage;
- (void)onOperate:(id)arg1;
- (void)onSingleTapOnNavigationBar:(id)arg1;
- (void)exitFullScreen;
- (void)setFullScreen:(_Bool)arg1;
- (void)removeNvGestureRecognizer;
- (void)addNvGestureRecognizer;
- (void)handleViewWillDisappear;
- (void)handleViewWillAppear;
- (void)showStatusBar;
- (void)hideStatusBar;
- (void)adjustImageViewRect;
- (void)initBottomView;
- (void)popViewController;
- (void)setupBackBarItem;
- (void)setupRecommendedView;
- (void)onClickEmotionCell;
- (void)setupEmotionCell;
- (void)setupStoreEmotionView;
- (void)initImageView;
- (void)reloadData;
- (void)setupNavigationBar;
- (void)initView;
- (void)initData;
- (void)willAppear;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithMsgWrap:(id)arg1;
- (void)dealloc;
- (void)adjustViewAndNavBarRect;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

