//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISessionStorageDelegate.h"

@class MMBaseSessionStorage, MMEnterpriseMainUsrData, NSMutableDictionary, NSString;

@interface MMEnterpriseSubSessionCacher : NSObject <ISessionStorageDelegate>
{
    MMEnterpriseMainUsrData *m_mainUsrData;
    NSString *m_mainUsrName;
    NSString *m_sessionType;
    MMBaseSessionStorage *m_sessionStorage;
    NSMutableDictionary *m_dictUsrname2CellData;
    _Bool m_showRedDot;
}

@property(readonly, nonatomic) NSString *mainUsrName; // @synthesize mainUsrName=m_mainUsrName;
- (void).cxx_destruct;
- (void)performCleanUpNoMsgSessions:(id)arg1;
- (id)getPathForOldSessionCache;
- (void)deleteOldVersionSessionCache;
- (long long)compareSession:(id)arg1 rightSession:(id)arg2;
- (id)importSessions;
- (void)clearSessionCache;
- (void)deleteAllSessions;
- (id)sessionInfoList;
- (void)deleteSessionWithUsrName:(id)arg1;
- (void)deleteSessionAtIndex:(long long)arg1;
- (id)sessionCellDataAtIndex:(long long)arg1;
- (id)sessionInfoWithUsrName:(id)arg1;
- (void)updateSessionList:(id)arg1;
- (void)updateSessionInfo:(id)arg1;
- (id)sessionInfoAtIndex:(long long)arg1;
- (unsigned int)sessionCount;
- (void)clearMainUsrRedDot;
- (_Bool)getMainUsrShowRedDot;
- (void)setMainUsrShowRedDot;
- (void)deleteNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (void)setNewArrivalCount:(unsigned int)arg1 withSubSessionUsrName:(id)arg2;
- (unsigned int)getNewArrivalCountWithSubSessionUsrName:(id)arg1;
- (unsigned int)getMainUsrUnreadCount;
- (void)clearMainUsrUnreadCount;
- (void)saveMainUsrData;
- (void)loadMainUsrData;
- (id)getMainUsrDataPath;
- (void)dealloc;
- (id)initWithMainUsrName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

