//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "IMsgExt.h"
#import "MMService.h"

@class NSMutableDictionary, NSString;

@interface MMEnterpriseBrandSessionMgr : MMService <MMService, IMsgExt, IContactMgrExt, IMMNewSessionMgrExt>
{
    NSMutableDictionary *_dictMainUsr2SubSessionCacher;
}

- (void).cxx_destruct;
- (id)genMainFrameSessionInfo:(id)arg1;
- (_Bool)isExistRedDot:(id)arg1;
- (id)getMainUsrName:(id)arg1;
- (id)sessionInfoWithSubUsrName:(id)arg1;
- (id)subSessionCacherWithSubUsrName:(id)arg1;
- (id)subSessionCacher:(id)arg1;
- (void)onModifyContactDraft:(id)arg1;
- (void)onModifyContact:(id)arg1;
- (void)onDeleteContact:(id)arg1;
- (void)OnModMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2;
- (void)OnAddMsg:(id)arg1 MsgWrap:(id)arg2;
- (void)OnUnReadCountChange:(id)arg1;
- (void)OnDelMsg:(id)arg1;
- (void)onDeleteSessionOfUser:(id)arg1;
- (void)isMessage:(id)arg1 Handled:(_Bool *)arg2;
- (void)isUser:(id)arg1 Handled:(_Bool *)arg2;
- (void)modifySubEnterpriseContact;
- (void)clearUnReadCntOfSubUsrName:(id)arg1;
- (void)deleteSessionOfSubUsrName:(id)arg1;
- (void)updateSessionOfSubUsrName:(id)arg1;
- (void)topSessionOfSubUsrName:(id)arg1;
- (void)clearUnReadCntOfMainUsrName:(id)arg1;
- (void)deleteSessionListOfMainUsrName:(id)arg1;
- (id)sessionInfoWithMainUsrName:(id)arg1 atIndex:(long long)arg2;
- (id)sessionCellDataWithMainUsrName:(id)arg1 atIndex:(long long)arg2;
- (unsigned int)sessionUnreadCountWithMainUserName:(id)arg1;
- (unsigned int)sessionNewArrivalUnreadCountWithMainUserName:(id)arg1;
- (unsigned int)sessionCountWithMainUserName:(id)arg1;
- (_Bool)onServiceMemoryWarning;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

