//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MFMailComposeViewControllerDelegate.h"
#import "MMPathComponentViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMTableView, NSData, NSMutableArray, NSString, UIToolbar, WriteMailViewController;

@interface MMFileExplorerViewController : MMUIViewController <UIGestureRecognizerDelegate, UITableViewDelegate, UITableViewDataSource, MMPathComponentViewDelegate, WCActionSheetDelegate, MFMailComposeViewControllerDelegate, UIDocumentInteractionControllerDelegate, UIAlertViewDelegate>
{
    NSString *m_currentPath;
    NSMutableArray *m_history;
    NSMutableArray *m_backStack;
    NSMutableArray *m_forwStack;
    NSMutableArray *m_files;
    MMTableView *m_tableView;
    UIToolbar *m_toolBar;
    NSMutableArray *m_copiedItems;
    NSMutableArray *m_operatingPaths;
    NSString *m_homePath;
    _Bool m_isCut;
    _Bool m_isAllConfirm;
    WriteMailViewController *m_mailViewCtrl;
    NSData *m_mailAttachData;
    NSString *m_nsMailAttachName;
}

@property(retain, nonatomic) NSString *m_homePath; // @synthesize m_homePath;
@property(retain, nonatomic) NSMutableArray *m_operatingPaths; // @synthesize m_operatingPaths;
@property(retain, nonatomic) NSMutableArray *m_copiedItems; // @synthesize m_copiedItems;
@property(retain, nonatomic) NSMutableArray *m_forwStack; // @synthesize m_forwStack;
@property(retain, nonatomic) NSMutableArray *m_backStack; // @synthesize m_backStack;
@property(retain, nonatomic) UIToolbar *m_toolBar; // @synthesize m_toolBar;
@property(retain, nonatomic) MMTableView *m_tableView; // @synthesize m_tableView;
@property(retain, nonatomic) NSMutableArray *m_files; // @synthesize m_files;
@property(retain, nonatomic) NSMutableArray *m_history; // @synthesize m_history;
@property(retain, nonatomic) NSString *m_currentPath; // @synthesize m_currentPath;
- (void).cxx_destruct;
- (void)onSaveToAlbum:(id)arg1;
- (void)onMultiDelete;
- (void)onDelete:(id)arg1;
- (void)onRename:(id)arg1;
- (void)onPaste:(id)arg1;
- (void)onMultiCut;
- (void)onCut:(id)arg1;
- (void)onMultiCopy;
- (void)onCopy:(id)arg1;
- (void)mailComposeController:(id)arg1 didFinishWithResult:(int)arg2 error:(id)arg3;
- (void)findEmailAddresses:(id)arg1 result:(id)arg2;
- (_Bool)checkStringSize:(id)arg1 minSize:(int)arg2 maxSize:(int)arg3;
- (void)onMultiMail;
- (void)onMail:(id)arg1;
- (void)addAttach;
- (void)writeMailWithAttachFile:(id)arg1 filePath:(id)arg2 zipName:(id)arg3 zipPath:(id)arg4;
- (id)mimeOfFile:(id)arg1;
- (void)gotoHomePath;
- (void)gotoPrevious;
- (void)onEditEnd;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onAction:(id)arg1;
- (void)handleLongPressEx:(id)arg1;
- (void)openMenu:(id)arg1 andGestureRecognizer:(id)arg2;
- (void)onClickOnPath:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)reportError:(id)arg1;
- (id)documentInteractionControllerViewControllerForPreview:(id)arg1;
- (void)tableView:(id)arg1 didDeselectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)updateToolBarStatus;
- (void)internalClickOnPath:(id)arg1;
- (void)openFileInOtherApp:(id)arg1;
- (_Bool)isSqliteDatabaseFile:(id)arg1;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (_Bool)canBecomeFirstResponder;
- (void)viewDidLoad;
- (id)gotoPath:(id)arg1 withTable:(id)arg2;
- (id)displayForFooter;
- (id)displayForPrevious;
- (id)displayForTitle;
- (id)displayForPath;
- (void)reloadCurrentPath;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

