//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class HDHeadImgDownloadTask, NSString;

@interface MMHDHeadImgDownloader : MMObject <PBMessageObserverDelegate>
{
    NSString *m_nsTempFile;
    HDHeadImgDownloadTask *m_currTask;
    id <HeadImgDownloaderDelegate> downloadDelegate;
}

@property(nonatomic) __weak id <HeadImgDownloaderDelegate> downloadDelegate; // @synthesize downloadDelegate;
- (void).cxx_destruct;
- (void)onDownloadPartOK:(id)arg1;
- (void)onDownloadPartFail;
- (void)ondownloadComplete;
- (void)updateNormalHead;
- (id)generateNormalHeadData:(id)arg1;
- (void)MessageReturnCDN:(id)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (unsigned int)downloadHDHeadImg:(id)arg1 url:(id)arg2 forCategory:(unsigned char)arg3;
- (unsigned int)downloadHDHeadImg:(id)arg1 forCategory:(unsigned char)arg2;
- (void)stopDownload;
- (_Bool)saveData:(id)arg1 forTask:(id)arg2 file:(id)arg3;
- (_Bool)downloadHDImg:(id)arg1 offset:(unsigned int)arg2 len:(unsigned int)arg3;
- (unsigned int)getFileSize:(id)arg1;
- (id)getTempFilePath:(id)arg1;
- (void)reset;
- (void)dealloc;
- (id)init;

@end

