//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMAudioDataWriteStreamDelegate.h"
#import "MMMusicPlayerNotifyExt.h"
#import "MMService.h"
#import "NSURLConnectionDelegate.h"
#import "WCAudioSessionExt.h"

@class MMAudioDataPipe, MMAudioStreamPlayer, MMMusicInfo, NSObject, NSString, NSTimer, NSURLConnection;

@interface MMMusicPlayer : MMService <MMMusicPlayerNotifyExt, WCAudioSessionExt, MMService, NSURLConnectionDelegate, MMAudioDataWriteStreamDelegate>
{
    MMAudioStreamPlayer *m_audioPlayer;
    MMAudioDataPipe *m_dataPipe;
    _Bool m_isLocalPlay;
    _Bool m_isQQMusicWifiPlay;
    _Bool m_isCyclePlay;
    MMMusicInfo *m_musicInfo;
    NSTimer *m_levelTimer;
    NSObject *m_clientInfo;
    NSString *m_title;
    NSString *m_photoUrl;
    NSURLConnection *m_dlConn;
    NSString *m_url;
}

@property(retain, nonatomic) MMMusicInfo *m_musicInfo; // @synthesize m_musicInfo;
@property(retain, nonatomic) NSString *m_url; // @synthesize m_url;
@property(retain, nonatomic) NSURLConnection *m_dlConn; // @synthesize m_dlConn;
@property(retain, nonatomic) NSString *m_photoUrl; // @synthesize m_photoUrl;
@property(retain, nonatomic) NSString *m_title; // @synthesize m_title;
@property(retain, nonatomic) NSObject *m_clientInfo; // @synthesize m_clientInfo;
- (void).cxx_destruct;
- (void)onWCAudioSessionOverride;
- (void)onWCAudioSessionCategoryChange:(unsigned long long)arg1;
- (void)onWCAudioSessionOldDeviceUnavailable;
- (void)onWCAudioSessionNewDeviceAvailable;
- (void)notifyMusicPlayerRestartMusic;
- (void)notifyMusicPlayerPauseMusic;
- (long long)status;
- (_Bool)isIdle;
- (_Bool)isPaused;
- (_Bool)isPlaying;
- (_Bool)isWaiting;
- (void)pause;
- (void)tryStopClientId:(id)arg1;
- (void)stopcycle;
- (void)stop;
- (void)start;
- (void)TimerCheckMeter;
- (void)playWithUrl:(id)arg1 MusicID:(id)arg2;
- (id)bcdStringFromUrl_WechatMusicUrl:(id)arg1;
- (id)bcdStringFromUrl_QQMusic:(id)arg1;
- (void)ignoreCurrentMusicItem;
- (void)addMusicItem:(id)arg1;
- (void)playbackStateChanged:(id)arg1;
- (void)destroyStreamer;
- (void)dealloc;
- (void)onServiceInit;
- (id)init;
- (void)startDownloadMusicFromUrl:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)reportDownloadStart;
- (void)reportDownloadFailed;
- (void)onHandleWriteEventfromStream:(id)arg1 eventType:(unsigned long long)arg2;
- (id)downloadTempPathForMusicFromUrl:(id)arg1;
- (id)cachePathForMusicFromUrl:(id)arg1;
- (id)getUrlPathExt:(id)arg1;
- (id)hashForUrl:(id)arg1;
- (id)cacheRootPath;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

