//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IOnlineClientMgrExt.h"
#import "MMService.h"

@class NSString, OnlineDeviceInfoViewController;

@interface MMOnlineDeviceStatusMgr : MMService <IOnlineClientMgrExt, MMService>
{
    _Bool _isShowing;
    OnlineDeviceInfoViewController *_viewController;
    double showVCTime;
}

- (void).cxx_destruct;
- (void)onSecondaryDeviceActiveChanged:(_Bool)arg1;
- (void)onLogoutWeb;
- (void)showDeviceInfoViewWithIsManualOpen:(_Bool)arg1;
- (void)hideDeviceInfoView;
- (void)showDeviceInfoView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

