//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PHPhotoLibraryChangeObserver.h"

@class NSString;

@interface MMPhotoLibraryDataProvider : MMService <PHPhotoLibraryChangeObserver, MMService>
{
    _Bool _isAlreadyGetData;
    _Bool _isNeedVideo;
    unsigned long long _photoMaxCount;
}

@property(nonatomic) _Bool isNeedVideo; // @synthesize isNeedVideo=_isNeedVideo;
@property(nonatomic) _Bool isAlreadyGetData; // @synthesize isAlreadyGetData=_isAlreadyGetData;
@property(nonatomic) unsigned long long photoMaxCount; // @synthesize photoMaxCount=_photoMaxCount;
- (void)photoLibraryDidChange:(id)arg1;
- (void)getUserPhotoLibraryForPHFrameworkWithMaxCount:(unsigned long long)arg1;
- (void)getUserPhotoLibraryForALAssetLibraryWithMaxCount:(unsigned long long)arg1;
- (_Bool)isAlreadyGetPhotoLibraryData;
- (_Bool)isAuthorizationStatusNotDetermined;
- (_Bool)isAuthorize;
- (void)getUserPhotoLibraryWithMaxCount:(unsigned long long)arg1 andIsNeedVideo:(_Bool)arg2;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

