//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCoding.h"

@class CContact, CMessageWrap, NSString;

@interface MMSessionInfo : NSObject <WCDBCoding>
{
    NSString *m_nsUserName;
    NSString *m_nsFilePath;
    unsigned int m_uUnReadCount;
    _Bool m_bShowUnReadAsRedDot;
    CContact *m_contact;
    CMessageWrap *m_msgWrap;
    unsigned int m_uLastTime;
    _Bool m_bIsTop;
    unsigned int m_uTopTime;
    unsigned int m_uUnTopTime;
    unsigned int m_uAtMeCount;
    unsigned int ConIntRes2;
    NSString *ConStrRes2;
}

+ (id)dummyObject;
+ (void)initialize;
@property(nonatomic) unsigned int m_uAtMeCount; // @synthesize m_uAtMeCount;
@property(nonatomic) unsigned int m_uUnTopTime; // @synthesize m_uUnTopTime;
@property(nonatomic) unsigned int m_uTopTime; // @synthesize m_uTopTime;
@property(retain, nonatomic) CMessageWrap *m_msgWrap; // @synthesize m_msgWrap;
@property(retain, nonatomic) CContact *m_contact; // @synthesize m_contact;
@property(nonatomic) _Bool m_bIsTop; // @synthesize m_bIsTop;
@property(retain, nonatomic) NSString *ConStrRes2; // @synthesize ConStrRes2;
@property(retain, nonatomic) NSString *m_nsFilePath; // @synthesize m_nsFilePath;
@property(nonatomic) unsigned int ConIntRes2; // @synthesize ConIntRes2;
@property(nonatomic) _Bool m_bShowUnReadAsRedDot; // @synthesize m_bShowUnReadAsRedDot;
@property(nonatomic) unsigned int m_uUnReadCount; // @synthesize m_uUnReadCount;
@property(nonatomic) unsigned int m_uLastTime; // @synthesize m_uLastTime;
@property(retain, nonatomic) NSString *m_nsUserName; // @synthesize m_nsUserName;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (long long)compare:(id)arg1;
- (void)tryLoadExtInfo;
- (id)init;
- (const basic_string_a490aa4c *)getWCDBPrimaryColumnName;
- (const struct WCDBIndexHelper *)getWCDBIndexArray;
- (unsigned long long)getWCDBIndexArrayCount;
- (const map_0e718273 *)getValueTagIndexMap;
- (id)getValueTypeTable;
- (const map_0e718273 *)getFileValueTagIndexMap;
- (id)getFileValueTypeTable;
- (const map_0e718273 *)getPackedValueTagIndexMap;
- (id)getPackedValueTypeTable;
- (const map_7a576766 *)getValueNameIndexMap;
- (id)getValueTable;
- (const WCDBCondition_22fabacd *)db_ConStrRes2;
- (const WCDBCondition_22fabacd *)db_m_nsFilePath;
- (const WCDBCondition_c6db074e *)db_ConIntRes2;
- (const WCDBCondition_c6db074e *)db_m_bShowUnReadAsRedDot;
- (const WCDBCondition_c6db074e *)db_m_uUnReadCount;
- (const WCDBCondition_c6db074e *)db_m_uLastTime;
- (const WCDBCondition_22fabacd *)db_m_nsUserName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

