//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMusicPlayerExt.h"
#import "IUiUtilExt.h"
#import "SendAppMsgHandleDelegate.h"
#import "ShareUploadTaskConfirmLogicHelperDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"

@class MMAnimationTipView, MMShakeMusicCoverImgView, NSMutableArray, NSString, NSTimer, SendAppMsgHandler, UIButton, UIImageView, UILabel, UITableView;

@interface MMShakeMusicViewController : MMUIViewController <WCActionSheetDelegate, UITableViewDelegate, UITableViewDataSource, ShareUploadTaskConfirmLogicHelperDelegate, IUiUtilExt, SendAppMsgHandleDelegate, IMusicPlayerExt>
{
    SendAppMsgHandler *_sendAppMsgHandler;
    UITableView *_lyricsView;
    NSMutableArray *_lyricsList;
    NSMutableArray *_timeList;
    NSMutableArray *_heightOfRow;
    NSMutableArray *_totalHeightOfRow;
    UIImageView *_blackView;
    UILabel *_noLyricsTip;
    NSTimer *_timer;
    int _count;
    int _currentIndex;
    float _currentRowHeight;
    float _heightOfPerSecond;
    float _totalScrollHeight;
    float _perScrolHeight;
    NSString *_lyrics;
    NSString *_singer;
    NSString *_musicName;
    NSString *_coverImageUrl;
    NSString *_album;
    NSString *_mediaUrl;
    NSString *_musicUrl;
    NSString *_musicLowBandUrl;
    NSString *_musicID;
    NSString *_musicAppId;
    float _offset;
    NSMutableArray *_musicInfoList;
    _Bool _isDone;
    UIButton *_playMusicButton;
    MMShakeMusicCoverImgView *_enlargeCoverImageView;
    _Bool isPlaying;
    float _lastTime;
    _Bool _isWating;
    _Bool _isBlur;
    int _lyricsViewHeight;
    UIImageView *_infoView;
    UIImageView *_wordShade;
    UIImageView *_coverImageShadeView;
    MMShakeMusicCoverImgView *_coverImageView;
    UILabel *_musicNameLabel;
    UILabel *_singerLabel;
    UILabel *_albumLabel;
    UIImageView *_coverImageGlowView;
    unsigned long long _lastSystemTime;
    float _totalDelayTime;
    _Bool m_isFromBanner;
    _Bool m_isFirstAppear;
    MMAnimationTipView *m_tipView;
    _Bool isScroll;
    NSString *_coverPath;
}

@property(retain, nonatomic) NSString *coverPath; // @synthesize coverPath=_coverPath;
@property(retain, nonatomic) MMAnimationTipView *m_tipView; // @synthesize m_tipView;
@property(nonatomic) _Bool isFromBanner; // @synthesize isFromBanner=m_isFromBanner;
@property(nonatomic) _Bool isScroll; // @synthesize isScroll;
@property(retain, nonatomic) NSString *musicAppId; // @synthesize musicAppId=_musicAppId;
@property(retain, nonatomic) NSString *musicID; // @synthesize musicID=_musicID;
@property(retain, nonatomic) NSString *musicLowBandUrl; // @synthesize musicLowBandUrl=_musicLowBandUrl;
@property(retain, nonatomic) NSString *musicUrl; // @synthesize musicUrl=_musicUrl;
@property(retain, nonatomic) NSString *mediaUrl; // @synthesize mediaUrl=_mediaUrl;
@property(nonatomic) float offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *album; // @synthesize album=_album;
@property(retain, nonatomic) NSString *coverImageUrl; // @synthesize coverImageUrl=_coverImageUrl;
@property(retain, nonatomic) NSString *musicName; // @synthesize musicName=_musicName;
@property(retain, nonatomic) NSString *singer; // @synthesize singer=_singer;
@property(retain, nonatomic) NSString *lyrics; // @synthesize lyrics=_lyrics;
- (void).cxx_destruct;
- (void)OnSendAppMsgOK;
- (void)onTopBarFrameChanged;
- (void)onLyricsChanged:(id)arg1 Lyrics:(id)arg2;
- (void)onMusicPlayStatusChanged;
- (void)updatePlayBtn;
- (void)dealloc;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)initView;
- (void)updateSubViews;
- (void)playMusic;
- (id)getMusiclUrl;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)getCoverImageData;
- (id)getMessageWrap:(id)arg1;
- (id)getUpLoadTask:(id)arg1;
- (void)showList:(id)arg1;
- (void)OnReturn;
- (void)scroll;
- (void)startScroll;
- (void)stopTimer;
- (void)setTextHighLightWithIndex:(int)arg1;
- (void)makeCurrentIndexWithTime:(float)arg1;
- (void)resolveLyrics;
- (float)time_StringToFloat:(id)arg1;
- (void)initDataFromMusicMgr;
- (id)initFromBanner;
- (void)initMusicList;
- (id)initWithMusicItem:(id)arg1 andOffset:(float)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

