//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "GameMsgCellViewDelegate.h"
#import "IGameFacadeExt.h"
#import "MMRefreshTableFooterDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "tableViewDelegate.h"

@class MMTableView, NSMutableArray, NSMutableDictionary, NSString, WCTimeLineFooterView;

@interface MMSnsGameListViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, WCActionSheetDelegate, tableViewDelegate, MMRefreshTableFooterDelegate, GameMsgCellViewDelegate, IGameFacadeExt>
{
    MMTableView *_tableView;
    WCTimeLineFooterView *_footerView;
    NSMutableArray *_arrMessage;
    NSMutableDictionary *_dicCells;
    NSMutableDictionary *_dicCellHeights;
    _Bool _hasMore;
    int _statSourceScene;
}

- (void).cxx_destruct;
- (void)jumpToApp:(id)arg1;
- (void)jumpToDetailViewV2:(id)arg1 scene:(int)arg2;
- (void)jumpToWebView:(id)arg1 msgItem:(id)arg2 scenc:(int)arg3 opType:(int)arg4;
- (void)onActionBtnClicked:(id)arg1;
- (void)onUrlClicked:(id)arg1 gameMsgItem:(id)arg2;
- (void)onAppNameClicked:(id)arg1 gameMsgItem:(id)arg2;
- (void)onTouchDefaultView:(id)arg1;
- (void)onImageClicked:(id)arg1 originView:(id)arg2;
- (void)addMsgList:(id)arg1;
- (void)onNewGameMsgsUpdate:(id)arg1;
- (void)onGetNextPageGameMsgList:(id)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3;
- (void)onGetFirstPageGameMsgList:(id)arg1 ErrCode:(int)arg2 HasMore:(_Bool)arg3 HasBatchGetting:(_Bool)arg4;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 editingStyleForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)genNormalCellContentViewAtIndexPath:(id)arg1;
- (double)getNormalCellContentViewHeightAtIndexPath:(id)arg1;
- (void)updateTableFooterView;
- (void)MMRefreshTableFooterDidTriggerRefresh:(id)arg1;
- (void)onLoadMore;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didReceiveLocalMemoryWarning:(id)arg1;
- (void)initView;
- (void)initData;
- (void)setSourceScene:(int)arg1;
- (void)onClearList;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

