//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

#import "ILinkEventExt.h"
#import "RichTextLayoutDelegate.h"
#import "WCImageViewDelegate.h"

@class MMHeadImageView, MMWebImageView, NSString, RichTextView, SnsGameMsg, UIButton, UILabel, UIView, UrlLabel;

@interface MMSnsGameListCellView : MMUIView <RichTextLayoutDelegate, ILinkEventExt, WCImageViewDelegate>
{
    SnsGameMsg *m_snsGameMsgItem;
    MMHeadImageView *m_headerView;
    MMWebImageView *m_iconView;
    RichTextView *m_contentLabel;
    UILabel *m_nickLabel;
    UILabel *m_actionLabel;
    UILabel *m_timeLabel;
    UrlLabel *m_appNameLabel;
    UIView *m_defaultView;
    UIView *m_URLView;
    UIView *m_VideoView;
    UIView *m_ImageView;
    UIView *m_backgroundView;
    UIButton *m_actionBtn;
    id <GameMsgCellViewDelegate> m_delegate;
    _Bool m_isDefaultView;
}

+ (double)heightForSnsGameMsg:(id)arg1;
+ (void)caluThumbSize:(id)arg1;
@property(nonatomic) __weak id <GameMsgCellViewDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 backupUrl:(id)arg2 withRect:(struct CGRect)arg3;
- (_Bool)shouldOpenNewLineAtY:(double)arg1 withLineHeight:(double)arg2 richTextView:(id)arg3;
- (void)onActionBtnTouch;
- (void)onTouchUrlBtn:(id)arg1;
- (void)onImageClicked;
- (void)onTouchDefaultView;
- (void)onTouchVideoBackImageButton:(id)arg1;
- (void)layoutSubviews;
- (id)getVideoContentView;
- (id)getImageContentView;
- (id)getURLContentView;
- (id)getDefaultViewWithImage;
- (id)getDefaultView;
- (void)initSnsGameMsgCell;
- (void)dealloc;
- (id)initWithSnsMsgItem:(id)arg1 withSize:(struct CGSize)arg2;
- (id)getDisplayName;
- (id)getContactDisplayName;
- (id)getAppName;
- (_Bool)canClickSourceName;
- (_Bool)canShowSourceName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

