//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class EmoticonStoreDownloadView, EmoticonStoreItem, MMWebImageView, UIImageView, UILabel, UIView;

@interface MMStoreEmotionAllCell : UICollectionViewCell
{
    long long _type;
    long long _scene;
    MMWebImageView *_m_webImageView;
    UILabel *_m_nameLabel;
    UILabel *_m_inroduceLabel;
    EmoticonStoreDownloadView *_m_downloadView;
    EmoticonStoreItem *_m_storeItem;
    UIView *_m_lineView;
    MMWebImageView *_m_tagImageView;
    UIImageView *_m_newImageView;
}

@property(retain, nonatomic) UIImageView *m_newImageView; // @synthesize m_newImageView=_m_newImageView;
@property(retain, nonatomic) MMWebImageView *m_tagImageView; // @synthesize m_tagImageView=_m_tagImageView;
@property(retain, nonatomic) UIView *m_lineView; // @synthesize m_lineView=_m_lineView;
@property(retain, nonatomic) EmoticonStoreItem *m_storeItem; // @synthesize m_storeItem=_m_storeItem;
@property(retain, nonatomic) EmoticonStoreDownloadView *m_downloadView; // @synthesize m_downloadView=_m_downloadView;
@property(retain, nonatomic) UILabel *m_inroduceLabel; // @synthesize m_inroduceLabel=_m_inroduceLabel;
@property(retain, nonatomic) UILabel *m_nameLabel; // @synthesize m_nameLabel=_m_nameLabel;
@property(retain, nonatomic) MMWebImageView *m_webImageView; // @synthesize m_webImageView=_m_webImageView;
- (void).cxx_destruct;
- (void)setScene:(long long)arg1 andType:(long long)arg2;
- (void)updateStoreItem:(id)arg1 Delegate:(id)arg2 Entrance:(unsigned int)arg3;
- (void)layoutSubviews;
- (void)loadTagImageView;
- (void)initDownloadView;
- (void)initIntroduceLabel;
- (void)initNameLabel;
- (void)initWebImageView;
- (void)initLineView;
- (void)drawRect:(struct CGRect)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (void)setMsgBrowseStyle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

