//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString, UIColor, UIImage;

@interface MMTabBarButton : UIButton
{
    NSString *_nsNormalTitle;
    NSString *_nsSelectedTitle;
    UIImage *_oNormalBackgroundImage;
    UIImage *_oSelectedBackgroundImage;
    UIImage *_oNormalImage;
    UIImage *_oSelectedImage;
    UIColor *_oNormalShadowColor;
    UIColor *_oSelectedShadowColor;
    UIColor *_oNormalTitleColor;
    UIColor *_oSelectedTitleColor;
}

@property(retain, nonatomic) UIColor *oSelectedShadowColor; // @synthesize oSelectedShadowColor=_oSelectedShadowColor;
@property(retain, nonatomic) UIColor *oNormalShadowColor; // @synthesize oNormalShadowColor=_oNormalShadowColor;
@property(retain, nonatomic) UIColor *oSelectedTitleColor; // @synthesize oSelectedTitleColor=_oSelectedTitleColor;
@property(retain, nonatomic) UIColor *oNormalTitleColor; // @synthesize oNormalTitleColor=_oNormalTitleColor;
@property(retain, nonatomic) UIImage *oSelectedImage; // @synthesize oSelectedImage=_oSelectedImage;
@property(retain, nonatomic) UIImage *oNormalImage; // @synthesize oNormalImage=_oNormalImage;
@property(retain, nonatomic) UIImage *oSelectedBackgroundImage; // @synthesize oSelectedBackgroundImage=_oSelectedBackgroundImage;
@property(retain, nonatomic) UIImage *oNormalBackgroundImage; // @synthesize oNormalBackgroundImage=_oNormalBackgroundImage;
@property(retain, nonatomic) NSString *nsSelectedTitle; // @synthesize nsSelectedTitle=_nsSelectedTitle;
@property(retain, nonatomic) NSString *nsNormalTitle; // @synthesize nsNormalTitle=_nsNormalTitle;
- (void).cxx_destruct;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)setTitle:(id)arg1 forState:(unsigned long long)arg2;
- (void)setBackgroundImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setImage:(id)arg1 forState:(unsigned long long)arg2;
- (void)setSelected:(_Bool)arg1;

@end

