//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@interface MMUIEventTargetWrap : MMObject
{
    id <NSObject> _delegate;
    id _target;
    SEL _action;
    _Bool _deleteMark;
}

@property(nonatomic) _Bool deleteMark; // @synthesize deleteMark=_deleteMark;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) __weak id <NSObject> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)init;

@end

