//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIWindow.h"

#import "IVOIPExt.h"
#import "IVOIPModeSwitchExt.h"
#import "MMVoipMinimizeWindowExt.h"
#import "MoveWithTouchAlgorithmDelegate.h"

@class MoveWithTouchAlgorithm, NSString, UIImageView, UIView, VOIPVideoRender;

@interface MMVoipMinimizeWindow : MMUIWindow <MoveWithTouchAlgorithmDelegate, MMVoipMinimizeWindowExt, IVOIPExt, IVOIPModeSwitchExt>
{
    _Bool m_hasChangeToAudioMode;
    _Bool m_hasHideWindow;
    _Bool _m_hasChangeToMinimizeMode;
    _Bool _m_hasBeginTalk;
    MoveWithTouchAlgorithm *m_moveAlgorithm;
    VOIPVideoRender *m_peerRender;
    UIView *m_peerRenderView;
    UIImageView *m_imageView;
    UIView *m_preview;
    unsigned long long _mininzeTime;
    struct CGRect m_fixRect;
    struct CGRect _m_rectBeforeToFullScreen;
}

@property(nonatomic) unsigned long long mininzeTime; // @synthesize mininzeTime=_mininzeTime;
@property(nonatomic) struct CGRect m_rectBeforeToFullScreen; // @synthesize m_rectBeforeToFullScreen=_m_rectBeforeToFullScreen;
@property(nonatomic) _Bool m_hasBeginTalk; // @synthesize m_hasBeginTalk=_m_hasBeginTalk;
@property(nonatomic) _Bool m_hasChangeToMinimizeMode; // @synthesize m_hasChangeToMinimizeMode=_m_hasChangeToMinimizeMode;
@property(retain, nonatomic) UIView *m_preview; // @synthesize m_preview;
@property(retain, nonatomic) UIImageView *m_imageView; // @synthesize m_imageView;
@property(nonatomic) struct CGRect m_fixRect; // @synthesize m_fixRect;
@property(nonatomic) _Bool m_hasHideWindow; // @synthesize m_hasHideWindow;
@property(nonatomic) _Bool m_hasChangeToAudioMode; // @synthesize m_hasChangeToAudioMode;
@property(retain, nonatomic) UIView *m_peerRenderView; // @synthesize m_peerRenderView;
@property(retain, nonatomic) VOIPVideoRender *m_peerRender; // @synthesize m_peerRender;
@property(retain, nonatomic) MoveWithTouchAlgorithm *m_moveAlgorithm; // @synthesize m_moveAlgorithm;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)OnFromRemoteVideoToBothVideo;
- (void)OnFromLocalVideoToBothVideo;
- (void)OnOneWayLocalEarModeForBadNetwork;
- (void)OnOneWayRemoteEarModeForBadNetwork;
- (void)OnOneWayRemoteVideoMode;
- (void)OnOneWayLocalVideoMode;
- (void)OnOneWayRemoteEarMode;
- (void)OnOneWayLocalEarMode;
- (void)OnOneWayRemoteEarModeFor2G;
- (void)OnOneWayLocalEarModeFor2G;
- (void)OnBothEarMode;
- (void)OnRemoteVideoMode;
- (void)OnRemoteEarMode;
- (void)OnLocalVideoMode;
- (void)OnLocalEarMode;
- (void)OnBothVideoMode;
- (void)OnRemoteEarModeFor2G;
- (void)OnLocalEarModeFor2G;
- (void)OnAutoHangUp:(id)arg1;
- (void)OnCallInterrupt:(id)arg1;
- (void)OnLightInterrupt:(_Bool)arg1;
- (void)OnTellMeViewIsExist:(_Bool *)arg1;
- (void)OnMonitorWithSendRecvInfo:(int)arg1 andSendFPS:(int)arg2 andRecvFPS:(int)arg3 andSendKbps:(int)arg4 andRecvKbps:(int)arg5 andP2SInfo:(id)arg6;
- (void)OnMonitorWithSendFPS:(int)arg1 andRecvFPS:(int)arg2;
- (void)OnMonitorChannelInfo:(unsigned int)arg1 andChannelType:(int)arg2;
- (void)OnTalkBrokenError:(id)arg1 ErrNo:(int)arg2;
- (void)OnNetWorkError:(id)arg1 ErrNo:(int)arg2;
- (void)OnSyncError:(id)arg1 ErrNo:(int)arg2;
- (void)OnError:(id)arg1 ErrNo:(int)arg2;
- (void)OnTimeOut:(id)arg1;
- (void)OnInterrupt:(id)arg1;
- (void)OnBeginTalk:(id)arg1;
- (void)OnBeginConnect:(id)arg1;
- (void)OnBeHanguped:(id)arg1;
- (void)OnBeRejected:(id)arg1;
- (void)OnPreConnect:(id)arg1;
- (void)OnBeAccepted:(id)arg1;
- (void)OnNoAnswer:(id)arg1;
- (void)OnAccept:(id)arg1 ErrNo:(int)arg2;
- (void)OnCall:(id)arg1 ErrNo:(int)arg2;
- (void)onVoipChangeToFullScreenDisplay;
- (void)onVoipChangeToMinimizeDisplay;
- (void)clearAnimation;
- (void)showMinimizeWindow;
- (void)changeToFullScreen;
- (_Bool)canDoAnimation;
- (id)onMoveWithTouchAlgorithmRequestView;
- (void)onMoveWithTouchAlgorithmTaped;
- (void)onMoveEndWithTouchAlgorithmResultMoveTo:(struct CGPoint)arg1;
- (void)onMoveWithTouchAlgorithmResultMoveTo:(struct CGPoint)arg1;
- (void)hideVoipMinimizeWindow;
- (void)previewAnimation;
- (void)updatePreview;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)minimizeWindowFrame;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

