//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IJSSpeedyMgrExt.h"
#import "MMIconActionSheetDelegate.h"
#import "MMJSApiVerifyMgrDelegate.h"
#import "MMWebViewFontFloatViewDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WebViewA8KeyLogicDelegate.h"
#import "WebViewJSLogicDelegate.h"
#import "WebViewURLCheckLogicDelegate.h"

@class CContact, JSConsoleViewController, MMAnimationTipView, MMJSApiVerifyMgr, MMScrollActionSheet, MMURLHandler, MMWebProgressBar, MMWebViewHistory, NSCache, NSMutableArray, NSMutableDictionary, NSMutableSet, NSString, NSURLConnection, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UILongPressGestureRecognizer, UIScreenEdgePanGestureRecognizer, UIView, UIWebView, WCDeepLinkHandler, WXGesture, WebViewA8KeyLogicImpl, WebViewJSLogicImpl, WebViewMenuCustomizeLogic, WebViewURLCheckLogic;

@interface MMWebViewController : MMUIViewController <UIGestureRecognizerDelegate, WebViewURLCheckLogicDelegate, PBMessageObserverDelegate, WCActionSheetDelegate, UIWebViewDelegate, UIAlertViewDelegate, MMWebViewFontFloatViewDelegate, MMIconActionSheetDelegate, WebViewA8KeyLogicDelegate, WebViewJSLogicDelegate, UIScrollViewDelegate, IJSSpeedyMgrExt, MMJSApiVerifyMgrDelegate>
{
    UIWebView *webView;
    UILabel *m_deeplinkRedirecting;
    UIImageView *m_addressBarView;
    UILabel *m_addressLabel;
    UIButton *m_addressBarBtn;
    UIActivityIndicatorView *m_activityView;
    MMURLHandler *m_urlHandler;
    WXGesture *m_gesture;
    NSString *m_initUrl;
    WebViewA8KeyLogicImpl *m_a8KeyLogicImpl;
    JSConsoleViewController *m_consoleViewController;
    WebViewJSLogicImpl *m_jsLogicImpl;
    WebViewURLCheckLogic *m_urlCheckLogic;
    unsigned int m_uiBackCount;
    _Bool m_isPageDidLoaded;
    UIButton *m_loadFailView;
    NSMutableArray *m_actionSheetRow1;
    NSMutableArray *m_actionSheetRow2;
    MMScrollActionSheet *m_scrollActionSheet;
    WebViewMenuCustomizeLogic *m_menuCustomizeLogic;
    NSMutableDictionary *m_jsInitInfo;
    WCDeepLinkHandler *m_deepLinkHandler;
    _Bool m_bDeepLink;
    MMJSApiVerifyMgr *m_apiVerifyMgr;
    UIImageView *m_lastPageShot;
    UIView *m_lastView;
    UIView *m_coverView;
    UIView *m_shadowView;
    double m_lastViewCenterX;
    double m_lastChangedCenterX;
    double m_lastChangedTime;
    double m_lastChangedCenterX2;
    double m_lastChangedTime2;
    UIScreenEdgePanGestureRecognizer *m_swipeGestureRecognizer;
    UIView *m_invisibleScrollPreventer;
    MMWebViewHistory *m_history;
    _Bool m_isScrollMenuScroll;
    id <MMWebViewDelegate> m_delegate;
    _Bool m_bAutoSetTitle;
    NSMutableSet *m_jsTempAllowApiCalls;
    _Bool m_isDisableShareMenu;
    _Bool m_disalbeStartLoadGetA8Key;
    unsigned int m_addScence;
    UIView *m_customLoadingView;
    _Bool m_bShouldForcedRotationToPortrait;
    unsigned int m_stat_enterTime;
    long long m_loadingCount;
    _Bool m_isFinishLoaded;
    UILongPressGestureRecognizer *m_longPressGestureRecognizer;
    _Bool m_openAllPermission;
    _Bool m_isPageLoading;
    NSString *m_jump;
    _Bool m_viewDidAppear;
    double m_startLoadTime;
    NSString *m_oLoadingUrl;
    _Bool m_isHideShareMenuByJsApi;
    _Bool m_isPageLoadFail;
    _Bool m_bPresentModal;
    _Bool m_bLoadFromLocalServer;
    vector_01fc9dba _pIDKeyList;
    _Bool m_bHasAnimated;
    _Bool m_bOfflinePage;
    _Bool m_isLanscape;
    _Bool _m_canCache;
    _Bool _m_bUserHasClickLink;
    _Bool _m_isSwiping;
    unsigned int uiCurrentEventID;
    int _m_webviewType;
    NSMutableDictionary *m_extraInfo;
    NSCache *m_urlCheckResultCache;
    NSString *nsUrlOfReadingMode;
    NSString *nsUrlOfReadModeOriginal;
    NSString *m_nsJSFitContent;
    CContact *_brandContact;
    MMAnimationTipView *_m_animationTipView;
    NSURLConnection *_m_connection;
    MMWebProgressBar *_m_progressBar;
    NSString *_m_lastCheckCpKey;
}

@property(retain, nonatomic) NSString *m_lastCheckCpKey; // @synthesize m_lastCheckCpKey=_m_lastCheckCpKey;
@property(nonatomic) _Bool m_isSwiping; // @synthesize m_isSwiping=_m_isSwiping;
@property(retain, nonatomic) MMWebProgressBar *m_progressBar; // @synthesize m_progressBar=_m_progressBar;
@property(retain, nonatomic) NSURLConnection *m_connection; // @synthesize m_connection=_m_connection;
@property(retain, nonatomic) MMAnimationTipView *m_animationTipView; // @synthesize m_animationTipView=_m_animationTipView;
@property(nonatomic) int m_webviewType; // @synthesize m_webviewType=_m_webviewType;
@property(nonatomic) _Bool m_bUserHasClickLink; // @synthesize m_bUserHasClickLink=_m_bUserHasClickLink;
@property(retain, nonatomic) CContact *brandContact; // @synthesize brandContact=_brandContact;
@property(nonatomic) _Bool m_canCache; // @synthesize m_canCache=_m_canCache;
@property(retain, nonatomic) NSString *m_nsJSFitContent; // @synthesize m_nsJSFitContent;
@property(retain, nonatomic) NSString *nsUrlOfReadModeOriginal; // @synthesize nsUrlOfReadModeOriginal;
@property(retain, nonatomic) NSString *nsUrlOfReadingMode; // @synthesize nsUrlOfReadingMode;
@property(nonatomic) unsigned int uiCurrentEventID; // @synthesize uiCurrentEventID;
@property(retain, nonatomic) NSCache *m_urlCheckResultCache; // @synthesize m_urlCheckResultCache;
@property(nonatomic) _Bool m_bDeepLink; // @synthesize m_bDeepLink;
@property(readonly, nonatomic) NSString *m_initUrl; // @synthesize m_initUrl;
@property(retain, nonatomic) NSMutableDictionary *m_extraInfo; // @synthesize m_extraInfo;
@property(retain, nonatomic) UIView *m_customLoadingView; // @synthesize m_customLoadingView;
@property(nonatomic) _Bool m_isLanscape; // @synthesize m_isLanscape;
@property(nonatomic) __weak id <MMWebViewDelegate> m_delegate; // @synthesize m_delegate;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reportIDKeyForLoadFinish:(long long)arg1;
- (void)reportIDKeyForSystemError:(long long)arg1;
- (void)reportIDKeyForAllRequest;
- (void)logFeature11576WithOpType:(unsigned int)arg1;
- (void)onClickFailView:(id)arg1;
- (void)hideLoadFailView;
- (void)relayoutLoadFailView;
- (void)showLoadFailView:(unsigned int)arg1;
- (void)onPreverifyFinished;
- (id)getJSFunctionDef:(id)arg1;
- (void)onWebViewRequestFinished;
- (_Bool)isGetingA8Key;
- (void)onFinishedHandleJSApi;
- (id)getCurrentWebviewViewController;
- (_Bool)canAccessJSApi:(id)arg1;
- (id)getAuthorizedMonitorEvents:(id)arg1;
- (void)tryStartOutlinkDetect;
- (unsigned char)getJSApiPermission:(id)arg1;
- (_Bool)isShowMenuItem:(id)arg1;
- (unsigned char)getPermissionWithName:(id)arg1;
- (void)processJSAPICall:(id)arg1 funcDef:(id)arg2 funcBlock:(CDUnknownBlockType)arg3 failHandleBlock:(CDUnknownBlockType)arg4 apiPermission:(unsigned char)arg5;
- (void)url:(id)arg1 DidCheckReturnContentAttribute:(unsigned int)arg2;
- (void)onJumpToEmoticonDetailViewController:(id)arg1;
- (void)onJumpToViewController:(id)arg1;
- (void)onJumpToSafariWithUrl:(id)arg1;
- (void)onUpdatedPermisson;
- (void)onGetA8Key:(_Bool)arg1 Reason:(int)arg2;
- (void)saveJSAPIPermissionsInOfflineCache:(id)arg1 url:(id)arg2;
- (void)saveJSAPIPermissions:(id)arg1 url:(id)arg2;
- (void)saveJSAPIAuthInfo:(id)arg1;
- (void)sendGetA8KeyUrlEvent;
- (void)kvReportJSCall:(id)arg1 withParam:(id)arg2;
- (id)sendEventToJSBridge:(id)arg1 Param:(id)arg2;
- (void)doJsApiInitEvent;
- (void)showWXPayTip;
- (void)updateRightBarButtonWithURL:(id)arg1;
- (void)setCurrentUrl:(id)arg1;
- (unsigned int)getCurrentScene;
- (_Bool)isContentOriginal;
- (_Bool)isCanShowAllMenus;
- (_Bool)isPageDidLoad;
- (id)getCurrentUrl;
- (void)stopForcedRotationToPortrait;
- (void)startForcedRotationToPortrait;
- (void)keyboardDidShow:(id)arg1;
- (void)removeNotificationObservers;
- (void)initNotificationObservers;
- (id)webviewController;
- (void)permitTempAccessOfJSApi:(id)arg1;
- (_Bool)isTempAccessOfJSApiPermitted:(id)arg1;
- (_Bool)isAccessPermitttedByPermissionBitSet:(id)arg1;
- (void)onPageNotifyFinishedLoading:(id)arg1;
- (void)onDomReady:(id)arg1;
- (_Bool)shareToFB;
- (void)immediateDismissWebViewController;
- (void)dismissWebViewController;
- (void)setDisableWebAlertView:(_Bool)arg1;
- (_Bool)isMenuAction:(id)arg1;
- (id)getRequestingOrCurrentUrl;
- (void)onSelectFont:(unsigned int)arg1;
- (_Bool)shoudDelaySetFont;
- (void)dealloc;
- (void)OnClose;
- (void)backToAppIfNeed;
- (void)OnReturn;
- (void)cleanJSAPIDelegate;
- (_Bool)isSvrErrorTipForbidden;
- (void)willDisappear;
- (void)swipeBack:(id)arg1;
- (void)checkPosition;
- (double)getAnimationTimeWithDirectionRight:(_Bool)arg1;
- (double)getDefaultSpeed;
- (double)getSwipeSpeed;
- (_Bool)isSwipeRight;
- (void)removeSwipeBackGesture;
- (void)addSwipeBackGesture;
- (_Bool)isSupportSwipeBackGesture;
- (void)viewDidLoad;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)setCustomLoadingView:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)removeCustomLoadingView;
- (void)delaySetFontsWithSize:(id)arg1;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)handleJumpProfileUrl:(id)arg1 profileRange:(struct _NSRange)arg2;
- (void)delayHandleUrl:(id)arg1;
- (_Bool)isPhoneNumberUrl:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)markNeedCheckUrlAndRemoveLastCheckedUrl:(id)arg1;
- (void)checkSwipeGesture;
- (void)updateSnapshotWithURL:(id)arg1;
- (void)setupSnapShotView;
- (void)checkHistoryWithNavigationType:(long long)arg1;
- (void)delayPopForAppStore;
- (id)getUrlPermission:(id)arg1;
- (_Bool)hasUrlPermission:(id)arg1;
- (void)goToURL:(id)arg1;
- (void)goForward;
- (void)goBack;
- (void)stop;
- (void)reload;
- (void)initGestureRecognizer;
- (void)onSwipeGestureRecognizer:(id)arg1;
- (void)onSessionBarButtonClick:(id)arg1;
- (void)setShareBarItem:(id)arg1;
- (unsigned int)GetGeneralBitSetForUrl:(id)arg1;
- (_Bool)IsBitsetSet:(unsigned int)arg1 forUrl:(id)arg2;
- (_Bool)allowScanQRCodeByImage;
- (unsigned int)GetPermissionBitSet3;
- (unsigned int)GetPermissionBitSet2;
- (unsigned int)GetPermissionBitSet;
- (unsigned long long)GetDeepLinkBitSet;
- (void)done:(id)arg1;
- (void)adjustSubviewRects;
- (void)willDismissAndShow;
- (void)viewWillBeDismissed:(_Bool)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didAppear;
- (void)willAppear;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadHTMLString:(id)arg1 baseURL:(id)arg2;
- (id)extraInfo;
- (void)doDNS;
- (void)StartLoadWeb;
- (void)setExtraInfoValue:(id)arg1 forKey:(id)arg2;
- (void)setIsHideShareMenuByJsApi:(_Bool)arg1;
- (void)setDisableShareMenu:(_Bool)arg1;
- (void)setAddFriendScene:(unsigned int)arg1;
- (void)setAutoSetTitle:(_Bool)arg1;
- (void)setWebviewType:(int)arg1;
- (id)getOperationButtonImageNameWithURL:(id)arg1;
- (void)onLongPressOnWebview:(id)arg1;
- (void)enableLongPressDetect;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)shouldShowGoBackBtn;
- (id)initWithURL:(id)arg1 presentModal:(_Bool)arg2 extraInfo:(id)arg3;
- (void)internalInitWithUrl:(id)arg1 presentModal:(_Bool)arg2 extraInfo:(id)arg3;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)resetWebviewInsetOrY;
- (void)restoreAddressBar;
- (void)initAddressBarView;
- (void)initDeeplinkRedirectingView;
- (id)getAddressBarHostText:(id)arg1;
- (void)initNavigationBarItem;
- (void)initProgressView;
- (id)getShareUrl;
- (void)setPayTitle:(id)arg1;
- (id)getCurrentAppId;
- (void)setPublisher:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setRightBarButtonItemEnabled:(_Bool)arg1;
- (_Bool)canShowReadingMode;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)GetReadingModeUrlFromServer:(id)arg1;
- (void)StopReadingMode;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

