//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "MsgFastBrowseViewDelegate.h"
#import "MsgImgFullScreenWindowDelegate.h"

@class CMessageWrap, MsgFastBrowseView, MsgImgFullScreenWindow, NSArray, NSString;

@interface MsgImgFastBrowseViewController : MMUIViewController <MsgImgFullScreenWindowDelegate, MsgFastBrowseViewDelegate>
{
    id <MsgImgFastBrowseViewControllerDelegate> m_delegate;
    NSArray *m_arrMsg;
    MsgFastBrowseView *m_msgFastBrowseView;
    MsgImgFullScreenWindow *m_imgFullScreenWnd;
    _Bool m_bHighlightCurrentImage;
    CMessageWrap *m_curMsgWrap;
    NSString *m_nsChatName;
    double m_scrollOffset;
}

@property(nonatomic) _Bool m_bHighlightCurrentImage; // @synthesize m_bHighlightCurrentImage;
@property(nonatomic) double m_scrollOffset; // @synthesize m_scrollOffset;
@property(retain, nonatomic) NSString *m_nsChatName; // @synthesize m_nsChatName;
@property(retain, nonatomic) CMessageWrap *m_curMsgWrap; // @synthesize m_curMsgWrap;
@property(nonatomic) __weak id <MsgImgFastBrowseViewControllerDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)onSquareImgClicked:(id)arg1 withInfo:(id)arg2 withOffset:(unsigned int)arg3;
- (id)messageWrapsForMsgFastBrowseView:(id)arg1;
- (void)onMsgImgWindowWillHideToMsg:(id)arg1;
- (_Bool)needShowFastBrowseBtn;
- (void)PreviewImage:(id)arg1 MsgSquareThumb:(id)arg2;
- (void)onCancel;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)initView;
- (void)initNavBar;
- (void)initData;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithMsgWrap:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

