//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NewMainFrameViewController.h"

#import "MMImagePickerManagerDelegate.h"

@class NSString;

@interface NewMainFrameViewController (RightMenuActions) <MMImagePickerManagerDelegate>
- (void)openWeChatOut;
- (void)openFace2FaceReceiveMoney;
- (void)onRadar;
- (void)onMassSend;
- (void)openAlbum;
- (void)showQRInfoView;
- (void)showEmoticonStoreView;
- (void)showWCPayView;
- (void)showMyWCView;
- (void)onSelectContactReturn:(id)arg1 atScene:(unsigned int)arg2;
- (_Bool)onFilterContactCandidate:(id)arg1;
- (void)createVideoVOIPChat;
- (void)createVoiceVOIPChat;
- (void)MMImagePickerManagerDidCancel:(id)arg1;
- (void)MMImagePickerManager:(id)arg1 didFinishPickingImageWithInfo:(id)arg2;
- (void)createSharePhoto;
- (void)onCreateNewMessage;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

