//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableArray, NSString;

@interface NewSendMsgMgr : MMService <MMService, PBMessageObserverDelegate>
{
    NSMutableArray *arySendMsgRunningQueue;
    NSMutableArray *arySendMsgWaitingQueue;
}

@property(retain, nonatomic) NSMutableArray *arySendMsgWaitingQueue; // @synthesize arySendMsgWaitingQueue;
@property(retain, nonatomic) NSMutableArray *arySendMsgRunningQueue; // @synthesize arySendMsgRunningQueue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)onServiceInit;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)handleSendMsgResp:(id)arg1;
- (void)handleSendMsgListSuc:(id)arg1 microMsgReqList:(id)arg2;
- (void)handleSendMsgListFail:(id)arg1;
- (id)microMsgReq2WrapMsg:(id)arg1;
- (void)batchSendMsg:(id)arg1;
- (void)checkWaitingQueue;
- (void)newSendMsg:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

