//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMMLanguageMgrExt.h"
#import "IMMNewSessionMgrExt.h"
#import "MMKernelExt.h"
#import "MMService.h"
#import "MessageObserverDelegate.h"
#import "PBMessageObserverDelegate.h"

@class NSArray, NSMutableDictionary, NSMutableSet, NSString, SendActiveCGI;

@interface OnlineClientMgr : MMService <IMMLanguageMgrExt, MMService, MessageObserverDelegate, PBMessageObserverDelegate, IMMNewSessionMgrExt, MMKernelExt>
{
    _Bool m_isLoginWebWX;
    unsigned int m_curOnlineVersion;
    NSString *m_summaryXml;
    NSArray *m_arrOnlineInfo;
    _Bool m_isGettingOnlineInfo;
    _Bool m_shouldShowPushSwitch;
    NSMutableSet *m_markingMsgRead;
    NSMutableSet *m_pendingMarkMsgRead;
    SendActiveCGI *m_sendActiveCGI;
    unsigned int m_iconType;
    NSMutableDictionary *m_lastDeviceActiveMsg;
    unsigned long long m_lastReadItemCreateTime;
    _Bool m_isRunningAsBakDevice;
    _Bool m_hasGetChatList;
    _Bool m_needHeartBeat;
    _Bool m_shouldVibrate;
}

- (void).cxx_destruct;
- (void)handleMarkPatternLockUpdate:(id)arg1;
- (void)markPatternLockUpdate;
- (void)onManulLogOut;
- (void)DidEnterForeground:(id)arg1;
- (void)DidEnterBackground:(id)arg1;
- (void)sendUnActiveRequest;
- (void)sendActiveRequest;
- (id)getSendActiveCGI;
- (_Bool)shoudlSendActiveCGI;
- (void)handleMarkTimelineListRead:(id)arg1;
- (void)markTimelineListReadWithLastItemId:(id)arg1 itemCreateTime:(unsigned long long)arg2;
- (void)handleEnterWCMsgList:(id)arg1;
- (void)enterWCMsgListWithLastItemCreateTime:(unsigned long long)arg1;
- (_Bool)isRunningAsBakDevice;
- (id)GetOnlineClient;
- (id)GetSelfOnlineInfo;
- (id)GetOnlineSummaryForKey:(id)arg1;
- (id)GetOnlineSummary;
- (unsigned int)GetOnlineIconType;
- (void)statusNotifyGetChatListRequest;
- (void)checkShouldVibrateForNewMessageFlag:(unsigned int)arg1;
- (void)checkShouldAddFileHelperToTopWithFlag:(unsigned int)arg1;
- (void)checkShouldHidePushSwitchWithFlag:(unsigned int)arg1;
- (void)checkShouldHideOnelineInfoBarWithFlag:(unsigned int)arg1;
- (void)onGetOnlineInfoResponse:(id)arg1;
- (_Bool)createGetOnlineInfoEvent;
- (void)GetOnlineInfoFromServer;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)isNeedSyncChatname:(id)arg1;
- (void)onRemoteDeviceEnterSession:(id)arg1;
- (void)onRemoteDeviceQuitSession:(id)arg1;
- (void)onGetChatListResponsed:(id)arg1;
- (void)onGetEnterFunction:(id)arg1;
- (void)onGetQuitFunction:(id)arg1;
- (void)onGetMarkFunction:(id)arg1;
- (void)onGetSyncEnd;
- (void)MessageReturn:(unsigned int)arg1 MessageInfo:(id)arg2 Event:(unsigned int)arg3;
- (void)onActiveUsrNameChange:(id)arg1 curUsrName:(id)arg2;
- (void)getAllChat;
- (void)onMarkMsgReadReturn:(id)arg1 withResponse:(id)arg2;
- (void)MarkChatRead:(id)arg1;
- (void)QuitChat:(id)arg1;
- (void)EnterChat:(id)arg1;
- (void)logoutWeb:(_Bool)arg1;
- (void)onKickQuit;
- (void)setLastDeviceActiveMsg:(id)arg1 isEnterFunction:(_Bool)arg2;
- (_Bool)shouldShowPushSwitch;
- (void)setIsNeedShowPush:(_Bool)arg1;
- (_Bool)isNeedShowPush;
- (_Bool)isLoginWebWX;
- (_Bool)shouldVibranteForNewMessage;
- (void)onLanguageChange;
- (void)forceCheckIsLoginWebWX;
- (void)setAuthFlag:(unsigned long long)arg1;
- (unsigned int)genRandomClienMsgId;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

