//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "ICdnComMgrExt.h"
#import "PBMessageObserverDelegate.h"

@class CdnTaskInfo, FIFOFileQueue, NSString;

@interface OpenUploadCDNMgr : MMObject <ICdnComMgrExt, PBMessageObserverDelegate>
{
    FIFOFileQueue *_fileInfoQueue;
    unsigned int _curEventId;
    CdnTaskInfo *_curTaskInfo;
}

- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)OnCdnUpload:(id)arg1;
- (void)OnCdnUploadProgress:(id)arg1;
- (void)OnSetCdnDnsInfo;
- (_Bool)CreateCurUploadEvent;
- (void)StopUploadByChatName:(id)arg1;
- (void)StopUpload:(id)arg1;
- (void)StopCurUpload;
- (void)StartUpload:(id)arg1 MsgWrap:(id)arg2 Scene:(unsigned int)arg3;
- (void)ClearEventID;
- (void)UploadFail:(int)arg1;
- (void)UploadOk:(long long)arg1;
- (void)CheckQueue;
- (void)InitQueue;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

