//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBase, WCDataBaseTable;

@interface OpLogDB : NSObject
{
    WCDataBase *m_db;
    WCDataBaseTable *m_table;
}

@property(retain, nonatomic) WCDataBaseTable *m_table; // @synthesize m_table;
@property(retain, nonatomic) WCDataBase *m_db; // @synthesize m_db;
- (void).cxx_destruct;
- (_Bool)DeleteOpLogWithOpLogID:(unsigned int)arg1;
- (unsigned int)GetOpLogCount;
- (id)GetOpLogLargerThanOpLogID:(unsigned int)arg1 limit:(unsigned int)arg2;
- (_Bool)InsertOpLog:(id)arg1;
- (void)Close;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

