//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableArray;

@interface PayUPasswordBgView : UIView
{
    UIView *RoundCell1;
    UIView *RoundCell2;
    UIView *RoundCell3;
    UIView *RoundCell4;
    UIView *RoundCell5;
    UIView *RoundCell6;
    int iTotalNum;
    NSMutableArray *m_arrRoundCell;
}

- (void)SetInputNum:(int)arg1;
- (id)RoundCell:(int)arg1;
- (id)initWithFrame:(struct CGRect)arg1 AndImage:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 AndImage:(id)arg2 WithTotalNum:(int)arg3;

@end

