//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PayUBaseEncryptor : NSObject
{
}

+ (id)PayURSAEncrypt:(id)arg1 TimeSalt:(id)arg2 InputIntentType:(int)arg3 InputHandleMethodType:(int)arg4;
+ (id)doSha1Hash:(id)arg1;
+ (id)doMd5Hash:(id)arg1;

@end

