//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PayUPasswordCtrl;

@protocol PayUPasswordCtrlDelegate <NSObject>

@optional
- (void)passwordCtrlDidEndEditing:(PayUPasswordCtrl *)arg1;
- (void)passwordCtrlDidBeginEditing:(PayUPasswordCtrl *)arg1;
- (void)passwordCtrlShouldChange:(PayUPasswordCtrl *)arg1;
@end

