//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString, PoiLocation;

@interface POIBaseInfo : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) NSString *address; // @dynamic address;
@property(retain, nonatomic) NSString *branchName; // @dynamic branchName;
@property(retain, nonatomic) NSString *bussinessId; // @dynamic bussinessId;
@property(retain, nonatomic) NSString *catagory; // @dynamic catagory;
@property(retain, nonatomic) NSString *city; // @dynamic city;
@property(retain, nonatomic) NSMutableArray *coverUrlList; // @dynamic coverUrlList;
@property(retain, nonatomic) PoiLocation *location; // @dynamic location;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(nonatomic) unsigned int poiid; // @dynamic poiid;
@property(nonatomic) float price; // @dynamic price;
@property(retain, nonatomic) NSString *province; // @dynamic province;
@property(retain, nonatomic) NSString *telPhone; // @dynamic telPhone;
@property(nonatomic) unsigned long long type; // @dynamic type;

@end

