//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PSTNMgr.h"

@interface PSTNMgr (Data)
- (int)OnTransportChannelData:(void *)arg1 len:(int)arg2;
- (void)DataNotify_pp:(char *)arg1 len:(int)arg2 param:(short)arg3;
- (void)DataNotify:(char *)arg1 len:(int)arg2;
- (void)EventNotify:(long long)arg1 param:(int)arg2;
@end

