//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@interface PstnUserStatus : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(nonatomic) unsigned int memberId; // @dynamic memberId;
@property(nonatomic) unsigned int userStatus; // @dynamic userStatus;
@property(nonatomic) unsigned int userStatusKey; // @dynamic userStatusKey;

@end

