//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "CanvasManagerDelegate.h"
#import "IBottleMgrExt.h"
#import "IBottleSessionExt.h"
#import "MMTipsViewControllerDelegate.h"
#import "scrollViewDelegate.h"

@class BottleAnimation, BottleButton, BottleTipView, FishBottleLogicView, MMScrollView, NSString, ThrowBottleLogicView, UIImageView, UIView;

@interface SandyBeachViewController : MMUIViewController <CanvasManagerDelegate, scrollViewDelegate, IBottleSessionExt, IBottleMgrExt, MMTipsViewControllerDelegate>
{
    _Bool mIsFirstAppear;
    unsigned int mTimeOfDayType;
    _Bool mIsTouchEnabeld;
    unsigned int mThrowCount;
    unsigned int mFishCount;
    unsigned int mNewBottleCount;
    MMScrollView *mScrollView;
    UIImageView *mBGImageView;
    UIImageView *mMaskImageView;
    UIImageView *mSpotLightView;
    BottleTipView *mBottleTipView;
    BottleAnimation *mBottleAnimation;
    UIView *mBeachFlatView;
    BottleButton *mThrowBtnView;
    BottleButton *mFishBtnView;
    BottleButton *mBottleBtnView;
    ThrowBottleLogicView *mThrowLogicView;
    FishBottleLogicView *mFishLogicView;
}

@property(retain, nonatomic) FishBottleLogicView *mFishLogicView; // @synthesize mFishLogicView;
@property(retain, nonatomic) ThrowBottleLogicView *mThrowLogicView; // @synthesize mThrowLogicView;
@property(retain, nonatomic) BottleButton *mBottleBtnView; // @synthesize mBottleBtnView;
@property(retain, nonatomic) BottleButton *mFishBtnView; // @synthesize mFishBtnView;
@property(retain, nonatomic) BottleButton *mThrowBtnView; // @synthesize mThrowBtnView;
@property(retain, nonatomic) UIView *mBeachFlatView; // @synthesize mBeachFlatView;
@property(retain, nonatomic) BottleAnimation *mBottleAnimation; // @synthesize mBottleAnimation;
@property(retain, nonatomic) BottleTipView *mBottleTipView; // @synthesize mBottleTipView;
@property(retain, nonatomic) UIImageView *mSpotLightView; // @synthesize mSpotLightView;
@property(retain, nonatomic) UIImageView *mMaskImageView; // @synthesize mMaskImageView;
@property(retain, nonatomic) UIImageView *mBGImageView; // @synthesize mBGImageView;
@property(retain, nonatomic) MMScrollView *mScrollView; // @synthesize mScrollView;
- (void).cxx_destruct;
- (void)onClickTipsBtn:(id)arg1 Index:(long long)arg2;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)viewWillPush:(_Bool)arg1;
- (void)viewWillPresent:(_Bool)arg1;
- (void)viewWillBePoped:(_Bool)arg1;
- (void)willShow;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)willAppear;
- (void)viewDidLayoutSubviews;
- (void)forceToPortrait;
- (void)viewDidLoad;
- (void)toggleSetting:(id)arg1;
- (void)toggleBottle;
- (void)toggleFish;
- (void)toggleThrow;
- (void)showGuideToNearbyTipView:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

