//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WXPBGeneratedMessage.h"

@class BaseResponse, NSString;

@interface SearchUnauthDeviceResp : WXPBGeneratedMessage
{
}

+ (void)initialize;

// Remaining properties
@property(retain, nonatomic) BaseResponse *baseResponse; // @dynamic baseResponse;
@property(retain, nonatomic) NSString *deviceDesc; // @dynamic deviceDesc;
@property(retain, nonatomic) NSString *deviceTitle; // @dynamic deviceTitle;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;

@end

