//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMTableView, NSString, UITextField;

@interface SetServerIPViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource>
{
    UITextField *m_longIPTextField;
    UITextField *m_shortIPTextField;
    UITextField *m_UinTextField;
    MMTableView *m_tableView;
}

@property(retain, nonatomic) MMTableView *m_tableView; // @synthesize m_tableView;
@property(retain, nonatomic) UITextField *m_shortIPTextField; // @synthesize m_shortIPTextField;
@property(retain, nonatomic) UITextField *m_longIPTextField; // @synthesize m_longIPTextField;
- (void).cxx_destruct;
- (void)dealloc;
- (void)saveData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)onBack;
- (void)initNavigationBar;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)nextStep:(id)arg1;
- (void)makeUinTextCell:(id)arg1;
- (void)makeShortTextCell:(id)arg1;
- (void)makeLongTextCell:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

