//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingBaseViewController.h"

#import "IQQAccountMgrExt.h"
#import "PasswordLogicDelegate.h"

@class NSString, PasswordLogic;

@interface SettingUnbindQQViewController : SettingBaseViewController <PasswordLogicDelegate, IQQAccountMgrExt>
{
    NSString *m_nsTicket;
    PasswordLogic *m_verifyPasswdLogic;
}

@property(retain, nonatomic) NSString *m_nsTicket; // @synthesize m_nsTicket;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)undoRegester;
- (void)doRegester;
- (void)OnLocalUnBindQQOK;
- (void)OnUnBindQQFail;
- (void)OnUnBindQQOK;
- (void)passwordLogicPause;
- (void)passwordLogicStart;
- (void)passwordLogicCancel;
- (void)verifyPasswordOK:(id)arg1;
- (void)verifyPasswordFail;
- (void)unknownFail;
- (void)onUnBindQQ;
- (void)startVerityPasswd;
- (void)updateUnbindOK;
- (void)updateViewWithIcon:(id)arg1 tip:(id)arg2;
- (void)onDone:(id)arg1;
- (void)onCancel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

