//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "CBCentralManagerDelegate.h"
#import "CLLocationManagerDelegate.h"
#import "MMConfigMgrExt.h"
#import "MMService.h"

@class CBCentralManager, CLLocationManager, NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface ShakeRangingBeaconsMgr : MMService <CLLocationManagerDelegate, CBCentralManagerDelegate, MMConfigMgrExt, MMService>
{
    _Bool _isHaveShowed;
    CLLocationManager *_locationManager;
    NSMutableDictionary *_beaconsDict;
    CBCentralManager *_manager;
    NSArray *_uuidsArr;
    double _startRangingTime;
}

@property(nonatomic) double startRangingTime; // @synthesize startRangingTime=_startRangingTime;
@property(retain, nonatomic) NSArray *uuidsArr; // @synthesize uuidsArr=_uuidsArr;
@property(retain, nonatomic) CBCentralManager *manager; // @synthesize manager=_manager;
@property(retain) NSMutableDictionary *beaconsDict; // @synthesize beaconsDict=_beaconsDict;
@property(retain) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property _Bool isHaveShowed; // @synthesize isHaveShowed=_isHaveShowed;
- (void).cxx_destruct;
- (void)onMMConfigUpdated;
- (void)centralManagerDidUpdateState:(id)arg1;
- (_Bool)haveStartRangingRegion:(id)arg1;
- (void)registerRangingRegions;
- (void)detectBluetoothAvailable;
- (_Bool)isDeviceAndOSVersionOKForIBeacon;
- (id)keyForBeacon:(id)arg1;
- (void)locationManager:(id)arg1 didRangeBeacons:(id)arg2 inRegion:(id)arg3;
- (void)stopRanging;
- (void)startRanging;
@property(readonly) NSMutableArray *beacons;
- (void)setupUUIDs;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

