//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SightMovieWriter.h"

#import "MMovieCompressorDelegate.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, MMovieCompressor, NSObject<OS_dispatch_queue>, NSString, UIImage;

@interface SightMovieWriterF4 : SightMovieWriter <MMovieCompressorDelegate>
{
    _Bool m_isRecording;
    NSString *m_videoPath;
    NSString *m_audioPath;
    struct CGSize m_videoSize;
    double m_bitRate;
    long long m_videoOrientation;
    struct CGAffineTransform m_preferredTransform;
    UIImage *m_firstFrame;
    AVAssetWriter *m_writer;
    AVAssetWriterInput *m_videoInput;
    AVAssetWriterInputPixelBufferAdaptor *m_PixelBufferInput;
    unsigned int m_videoFrame;
    NSObject<OS_dispatch_queue> *m_movieWritingQueue;
    CDStruct_1b6d18a9 m_startTime;
    CDStruct_1b6d18a9 m_previousVideoTime;
    CDStruct_1b6d18a9 m_initializeTime;
    unsigned long long m_audioTimeStamp;
    unsigned long long m_videoTimeStamp;
    _Bool m_isLowPerformance;
    _Bool videoEncodingIsFinished;
    MMovieCompressor *m_audioCompressor;
    _Bool m_disableWritingToFile;
    _Bool _forceMPEG4;
}

@property(nonatomic) _Bool forceMPEG4; // @synthesize forceMPEG4=_forceMPEG4;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *writtingQueue; // @synthesize writtingQueue=m_movieWritingQueue;
- (void).cxx_destruct;
- (void)notifyOutput:(id)arg1;
- (void)compressMovieWithExport:(id)arg1;
- (void)tryMergeOutputVideo;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFailed:(unsigned int)arg2;
- (void)mMovieCompressor:(id)arg1 onMovieCompressFinished:(id)arg2 thumbImg:(id)arg3 ret:(unsigned int)arg4;
- (void)compressAudio;
- (id)makeNewPath:(id)arg1 withSubfix:(id)arg2;
- (void)cancelAmr;
- (void)stopAmr;
- (void)startAmr;
- (void)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)cancelWriting;
- (void)finishWriting;
- (void)startWriting;
- (void)realWriting;
- (void)prepareWriting;
- (_Bool)isWriting;
- (void)dealloc;
- (void)initWritterOutPut;
- (id)initWithFilePath:(id)arg1 videoOrientation:(long long)arg2 videoSize:(struct CGSize)arg3 bitRate:(double)arg4;
- (id)initWithFilePath:(id)arg1 videoOrientation:(long long)arg2 videoSize:(struct CGSize)arg3;
- (int)outputType;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

