//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SightMovieWriter.h"

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSObject<OS_dispatch_queue>, NSString, UIImage;

@interface SightMovieWriterF2 : SightMovieWriter
{
    _Bool m_isRecording;
    NSString *m_moviePath;
    struct CGSize m_videoSize;
    double m_bitRate;
    long long m_videoOrientation;
    struct CGAffineTransform m_preferredTransform;
    UIImage *m_firstFrame;
    AVAssetWriter *m_writer;
    AVAssetWriterInput *m_audioInput;
    AVAssetWriterInput *m_videoInput;
    AVAssetWriterInputPixelBufferAdaptor *m_PixelBufferInput;
    unsigned int m_audioFrame;
    unsigned int m_videoFrame;
    NSObject<OS_dispatch_queue> *m_movieWritingQueue;
    CDStruct_1b6d18a9 m_startTime;
    CDStruct_1b6d18a9 m_previousVideoTime;
    CDStruct_1b6d18a9 m_previousAudioTime;
    _Bool m_isLowPerformance;
    _Bool audioEncodingIsFinished;
    _Bool videoEncodingIsFinished;
    _Bool _forceMPEG4;
}

@property(nonatomic) _Bool forceMPEG4; // @synthesize forceMPEG4=_forceMPEG4;
- (void).cxx_destruct;
- (void)compressMovieWithExport;
- (id)makeNewPath:(id)arg1;
- (void)appendVideoSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)appendAudioSampleBuffer:(struct opaqueCMSampleBuffer *)arg1;
- (void)cancelWriting;
- (void)finishWriting;
- (void)startWriting;
- (void)realWriting;
- (void)prepareWriting;
- (_Bool)isWriting;
- (void)dealloc;
- (void)initWritterOutPut;
- (id)initWithFilePath:(id)arg1 videoOrientation:(long long)arg2 videoSize:(struct CGSize)arg3 bitRate:(double)arg4;
- (id)initWithFilePath:(id)arg1 videoOrientation:(long long)arg2 videoSize:(struct CGSize)arg3;
- (int)outputType;

@end

