//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SnsGameActionInfo : NSObject
{
    unsigned int _actionType;
    NSString *_actionBtnTitle;
    NSString *_jumpUrl;
    NSString *_messageExt;
    NSString *_lanuchGameBtnTitle;
    NSString *_gameRankViewTitle;
}

@property(retain, nonatomic) NSString *gameRankViewTitle; // @synthesize gameRankViewTitle=_gameRankViewTitle;
@property(retain, nonatomic) NSString *lanuchGameBtnTitle; // @synthesize lanuchGameBtnTitle=_lanuchGameBtnTitle;
@property(retain, nonatomic) NSString *messageExt; // @synthesize messageExt=_messageExt;
@property(retain, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(retain, nonatomic) NSString *actionBtnTitle; // @synthesize actionBtnTitle=_actionBtnTitle;
@property(nonatomic) unsigned int actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;
- (void)dealloc;

@end

