//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SnsGameShareMessageInfo : NSObject
{
    unsigned int _shareMsgType;
    NSString *_shareMsgTitle;
    NSString *_shareMsgDesc;
    NSString *_shareMsgContent;
    NSString *_thumbUrl;
    unsigned int _thumbWidth;
    unsigned int _thumbHeight;
    NSString *_mediaUrl;
}

@property(nonatomic) unsigned int thumbHeight; // @synthesize thumbHeight=_thumbHeight;
@property(nonatomic) unsigned int thumbWidth; // @synthesize thumbWidth=_thumbWidth;
@property(retain, nonatomic) NSString *mediaUrl; // @synthesize mediaUrl=_mediaUrl;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSString *shareMsgContent; // @synthesize shareMsgContent=_shareMsgContent;
@property(retain, nonatomic) NSString *shareMsgDesc; // @synthesize shareMsgDesc=_shareMsgDesc;
@property(retain, nonatomic) NSString *shareMsgTitle; // @synthesize shareMsgTitle=_shareMsgTitle;
@property(nonatomic) unsigned int shareMsgType; // @synthesize shareMsgType=_shareMsgType;
- (void).cxx_destruct;
- (void)dealloc;

@end

