//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "VOIPMgr.h"

#import "AVVideoDataSource.h"

@class NSString;

@interface VOIPMgr (AVVideoDataSource) <AVVideoDataSource>
- (int)VideoDevPutData:(char *)arg1 imageWidth:(unsigned int)arg2 imageHeight:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

