//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "PBMessageObserverDelegate.h"

@class NSMutableArray;

@interface WCAdvertiseLogicMgr : MMObject <PBMessageObserverDelegate>
{
    NSMutableArray *arrUpdateList;
    _Bool bUpdating;
    id <WCLogicMgrDelegate> m_delegate;
}

@property(nonatomic) __weak id <WCLogicMgrDelegate> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)responseForSnsADObjectDetailResponse:(id)arg1 Event:(unsigned int)arg2;
- (void)requestForSnsADObjectDetailRequest:(id)arg1 FromScene:(unsigned int)arg2;
- (void)onOperation:(id)arg1 Finished:(long long)arg2;
- (_Bool)responseForSnsADObjectOpResponse:(id)arg1 Event:(unsigned int)arg2;
- (_Bool)requestForSnsADObjectOpRequest:(id)arg1;
- (void)unInterestAdvertiseDataItem:(id)arg1;
- (_Bool)unLikeAdvertiseDataItem:(id)arg1;
- (_Bool)unCommentAdvertiseDataItem:(id)arg1 commentID:(id)arg2;
- (void)updateAdvertiseDataItemDetail:(id)arg1;
- (void)updateAdvertiseDataList:(id)arg1;
- (void)deleteAdvertiseDataItem:(id)arg1;
- (void)dealloc;
- (id)init;

@end

