//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class UIColor, WCCardData;

@interface WCCardHeaderView : MMUIView
{
    WCCardData *_cardData;
    UIColor *_gapColor;
}

@property(retain, nonatomic) UIColor *gapColor; // @synthesize gapColor=_gapColor;
- (void).cxx_destruct;
- (void)onclickAnnounce:(id)arg1;
- (void)loadTicketSubviews;
- (void)loadRedEnvelopesSubviews;
- (void)loadCardSubviews;
- (void)loadGenaralSubviews;
- (void)layoutSubviews;
- (double)getHeaderViewHeight;
- (id)initWithCardData:(id)arg1;
- (void)dealloc;

@end

