//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

@class NSString;

@interface WCCardFieldItem : MMObject
{
    unsigned int _showflag;
    NSString *_title;
    NSString *_subTitle;
    NSString *_auxTitle;
    NSString *_url;
}

@property(nonatomic) unsigned int showflag; // @synthesize showflag=_showflag;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *auxTitle; // @synthesize auxTitle=_auxTitle;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)dealloc;

@end

