//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class UIView, WCCardData;

@interface WCCardBarCodeView : MMUIView
{
    UIView *_codeView;
    WCCardData *_cardData;
}

- (void).cxx_destruct;
- (void)SetHighLight:(_Bool)arg1;
- (id)getCodeView;
- (_Bool)shouldShowSerialNumber;
- (void)loadNoticeView;
- (id)insertSpaceChar:(id)arg1 hasTransline:(_Bool)arg2;
- (void)loadSerialNumberDisplayView;
- (void)loadOneDimensionalCodeDisplayView;
- (void)loadTwoDimensionalCodeDisplayView;
- (void)loadMemberCardCodeDisplayView;
- (void)layoutSubviews;
- (double)getNoticeHeight;
- (struct CGRect)calFrame;
- (id)initWithCardData:(id)arg1;
- (void)dealloc;

@end

