//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class MMTableView, NSMutableArray, NSString, WCCardData;

@interface WCCardDetailSupplementViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate>
{
    int _cardStatus;
    WCCardData *_cardData;
    NSMutableArray *_tableDatas;
    MMTableView *_tableView;
}

- (void).cxx_destruct;
- (double)GetSectionHeaderHeightForData:(id)arg1;
- (id)getViewControllerTitle;
- (_Bool)hasServicePhone;
- (_Bool)hasImageTextDetail;
- (_Bool)hasCellList2;
- (_Bool)hasCellList1;
- (void)onServicePhone;
- (void)openImageTextDetail;
- (void)openCellList:(id)arg1;
- (void)makeGeneralCell:(id)arg1 title:(id)arg2 subTitle:(id)arg3 hasHandle:(_Bool)arg4;
- (void)makeServicePhoneCell:(id)arg1 cellTitle:(id)arg2;
- (void)makeImageTextCell:(id)arg1 cellTitle:(id)arg2;
- (void)makeCellList:(id)arg1 cellItem:(id)arg2;
- (void)makeFieldCell:(id)arg1 fieldItem:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (id)createTableFooterView;
- (_Bool)hasSourceView;
- (void)initView;
- (void)initData;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithCardData:(id)arg1 cardStatus:(int)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

