//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMObject.h"

#import "WCCardBatchImportViewControllerDelegate.h"
#import "WCCardDetailViewControllerDelegate.h"

@class NSString, UIViewController;

@interface WCCardAddHelper : MMObject <WCCardDetailViewControllerDelegate, WCCardBatchImportViewControllerDelegate>
{
    id <WCCardAddHelperDelegate> _delegate;
    UIViewController *_viewController;
}

- (void).cxx_destruct;
- (void)onImportCancel;
- (void)onImportFail:(id)arg1;
- (void)onImportSuccess:(id)arg1;
- (void)onAcceptCardCancel;
- (void)onAcceptCardFail:(id)arg1;
- (void)onAcceptCardSuccess:(id)arg1;
- (void)dismissViewController;
- (void)cancelHandle;
- (void)handleCardListInfo:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

