//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCContentItemBaseView.h"

#import "MMWebViewDelegate.h"
#import "WCImageViewDelegate.h"

@class MMWebViewController, NSString, WCImageView;

@interface WCContentItemViewTemplateSight : WCContentItemBaseView <MMWebViewDelegate, WCImageViewDelegate>
{
    MMWebViewController *_webViewController;
    WCImageView *_coverImage;
}

+ (double)heightForMedia:(id)arg1 showDetail:(_Bool)arg2;
- (void).cxx_destruct;
- (void)dealloc;
- (void)onClickWCImage:(id)arg1;
- (void)throwUrlMessage;
- (id)initWithWCDataItem:(id)arg1 showDetail:(_Bool)arg2;
- (id)initWithWCDataItem:(id)arg1;
- (void)initViewsWithWCDataItem:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

