//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCContentItemBaseView.h"

#import "MMMusicPlayerContollerDelegate.h"
#import "MMWebViewDelegate.h"
#import "RichTextLayoutDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "WCImageViewDelegate.h"

@class MMMusicPlayerContoller, MMWebViewController, NSString, UIImageView, UILabel, WCImageView;

@interface WCContentItemViewTemplateClassic : WCContentItemBaseView <WCImageViewDelegate, RichTextLayoutDelegate, MMWebViewDelegate, UIGestureRecognizerDelegate, MMMusicPlayerContollerDelegate>
{
    MMWebViewController *_webViewController;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    WCImageView *_coverImage;
    MMMusicPlayerContoller *_playButton;
    UIImageView *_defaultImageView;
    _Bool _forbidJumpUrl;
}

+ (double)heightForMedia:(id)arg1 showDetail:(_Bool)arg2;
+ (id)getTrimDesc:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setNonInteractive;
- (void)setNormalColor;
- (void)setHighlightedColor;
- (void)onClickWCImage:(id)arg1;
- (void)onClickToPlayMusic:(id)arg1;
- (void)throwUrlMessage;
- (void)onLongTouch;
- (void)onFavoriteAdd:(id)arg1;
- (void)initViewsWithWCDataItem:(id)arg1;
- (void)layoutSubviews;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

