//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WCDBCorruptReportInterface.h"

@class NSData, NSRecursiveLock, NSString, WCDBCorruptReport;

@interface WCDataBase : NSObject <WCDBCorruptReportInterface>
{
    struct sqlite3 *m_dbHandle;
    NSData *m_dbEncryptKey;
    _Bool m_isMemoryOnly;
    NSString *m_nsDBPath;
    NSString *m_nsDBFilePath;
    NSRecursiveLock *m_oLock;
    unsigned int m_databaseID;
    id <WCDataBaseEventDelegate> m_eventDelegate;
    WCDBCorruptReport *m_corruptReport;
}

+ (_Bool)GetRowId:(long long *)arg1 fromObject:(id)arg2;
+ (void)globalConfig;
+ (_Bool)deleteDB:(id)arg1;
@property(retain, nonatomic) WCDBCorruptReport *m_corruptReport; // @synthesize m_corruptReport;
@property __weak id <WCDataBaseEventDelegate> m_eventDelegate; // @synthesize m_eventDelegate;
@property(readonly, nonatomic) NSString *m_nsDBFilePath; // @synthesize m_nsDBFilePath;
@property(readonly, nonatomic) NSString *m_nsDBPath; // @synthesize m_nsDBPath;
@property(readonly, nonatomic) _Bool m_isMemoryOnly; // @synthesize m_isMemoryOnly;
- (void).cxx_destruct;
- (void)callEventTransactionRollback;
- (id)dbLock;
- (struct sqlite3 *)dbHandle;
- (id)errorWithCode:(int)arg1 Description:(id)arg2;
- (void)ClearCorruptNum;
- (void)directReportCorrupt:(int)arg1;
- (void)recordCorrupt:(int)arg1;
- (_Bool)deleteObjectsFromTable:(id)arg1 where:(const struct WCDBConditionBase *)arg2;
- (_Bool)deleteObject:(id)arg1 fromTable:(id)arg2;
- (basic_string_a490aa4c)getConditionStringFromObj:(id)arg1;
- (_Bool)updateObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 ofTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4;
- (_Bool)updateObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 ofTable:(id)arg3;
- (_Bool)updateProperty:(const struct WCDBConditionBase *)arg1 withValue:(id)arg2 ofClass:(Class)arg3 ofTable:(id)arg4 where:(const struct WCDBConditionBase *)arg5;
- (_Bool)insertOrUpdateObjects:(id)arg1 inToTable:(id)arg2 onConflict:(CDUnknownBlockType)arg3;
- (_Bool)insertOrUpdateObject:(id)arg1 inToTable:(id)arg2 onConflict:(CDUnknownBlockType)arg3;
- (_Bool)insertOrUpdateObjects:(id)arg1 inToTable:(id)arg2;
- (_Bool)insertObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 inToTable:(id)arg3 autoIncrement:(_Bool)arg4;
- (_Bool)insertObject:(id)arg1 inToTable:(id)arg2 autoIncrement:(_Bool)arg3;
- (_Bool)insertOrUpdateObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 inToTable:(id)arg3;
- (_Bool)insertOrUpdateObject:(id)arg1 inToTable:(id)arg2;
- (_Bool)doInsertObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 inToTable:(id)arg3 autoIncrement:(_Bool)arg4 isOrReplace:(_Bool)arg5;
- (void)bindBlobProperty:(const vector_24c76cbd *)arg1 ofObject:(id)arg2 toSTMT:(struct sqlite3_stmt *)arg3;
- (void)bindBlobProperty:(id)arg1 toSTMT:(struct sqlite3_stmt *)arg2;
- (basic_string_a490aa4c)dumpProperty:(id)arg1 withObject:(id)arg2;
- (basic_string_a490aa4c)dumpProperty:(id)arg1 withValue:(id)arg2;
- (void)autoIncrementPrimaryKey:(id)arg1 withValue:(long long)arg2;
- (void)dumpObject:(id)arg1 onProperties:(const vector_24c76cbd *)arg2 toNameString:(basic_string_a490aa4c *)arg3 andValueString:(basic_string_a490aa4c *)arg4 autoIncrement:(_Bool)arg5;
- (void)fillCrossTableFromTableName:(basic_string_a490aa4c *)arg1 queryInfo:(id)arg2;
- (id)itemFromObject:(id)arg1 columnName:(const basic_string_a490aa4c *)arg2;
- (_Bool)fillCrossTableSelectProperty:(basic_string_a490aa4c *)arg1 queryInfo:(id)arg2 columnInfo:(id)arg3;
- (_Bool)checkTableQueryInfo:(id)arg1;
- (id)getObjectsCrossTables:(id)arg1 where:(const struct WCDBConditionBase *)arg2 orderBy:(const struct WCDBConditionBase *)arg3 limit:(unsigned int)arg4 getError:(id *)arg5;
- (id)getSumProperty:(const struct WCDBConditionBase *)arg1 where:(const struct WCDBConditionBase *)arg2 ofClass:(Class)arg3 fromTable:(id)arg4;
- (id)getMaxProperty:(const struct WCDBConditionBase *)arg1 where:(const struct WCDBConditionBase *)arg2 ofClass:(Class)arg3 fromTable:(id)arg4;
- (id)getMaxProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3;
- (id)getOnePropertyValue:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4 orderBy:(const struct WCDBConditionBase *)arg5;
- (id)getPropertyWithDistinct:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4;
- (id)getProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4 orderBy:(const struct WCDBConditionBase *)arg5 limit:(unsigned int)arg6;
- (id)getProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4 limit:(unsigned int)arg5;
- (id)getProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 where:(const struct WCDBConditionBase *)arg4;
- (id)getProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3;
- (id)getOneProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 withQueryString:(const basic_string_a490aa4c *)arg4;
- (id)getProperty:(const struct WCDBConditionBase *)arg1 ofClass:(Class)arg2 fromTable:(id)arg3 withQueryString:(const basic_string_a490aa4c *)arg4;
- (unsigned int)getCountOfObjectsOfClass:(Class)arg1 fromTable:(id)arg2 withDistinctProperty:(const struct WCDBConditionBase *)arg3 where:(const struct WCDBConditionBase *)arg4;
- (unsigned int)getCountOfObjectsOfClass:(Class)arg1 fromTable:(id)arg2 where:(const struct WCDBConditionBase *)arg3;
- (id)getObjectsOfClass:(Class)arg1 fromTable:(id)arg2 onProperties:(const vector_24c76cbd *)arg3 where:(const struct WCDBConditionBase *)arg4 orderBy:(const struct WCDBConditionBase *)arg5 limit:(unsigned int)arg6 getError:(id *)arg7;
- (id)getObjectsOfClass:(Class)arg1 fromTable:(id)arg2 onProperties:(const vector_24c76cbd *)arg3 where:(const struct WCDBConditionBase *)arg4 orderBy:(const struct WCDBConditionBase *)arg5 limit:(unsigned int)arg6;
- (id)getObjectsOfClass:(Class)arg1 fromTable:(id)arg2 where:(const struct WCDBConditionBase *)arg3 orderBy:(const struct WCDBConditionBase *)arg4 limit:(unsigned int)arg5;
- (id)getObjectsOfClass:(Class)arg1 fromTable:(id)arg2 where:(const struct WCDBConditionBase *)arg3 limit:(unsigned int)arg4;
- (id)getObjectsOfClass:(Class)arg1 fromTable:(id)arg2 where:(const struct WCDBConditionBase *)arg3;
- (id)getAllObjectsOfClass:(Class)arg1 fromTable:(id)arg2;
- (id)getOneObjectOfClass:(Class)arg1 fromTable:(id)arg2 onProperties:(const vector_24c76cbd *)arg3 where:(const struct WCDBConditionBase *)arg4 orderBy:(const struct WCDBConditionBase *)arg5;
- (id)getOneObjectOfClass:(Class)arg1 fromTable:(id)arg2 where:(const struct WCDBConditionBase *)arg3;
- (id)getLastObjectOfClass:(Class)arg1 fromTable:(id)arg2;
- (id)extractOneProperty:(id)arg1 fromSTMT:(struct sqlite3_stmt *)arg2 atIndex:(int)arg3;
- (_Bool)extractObjects:(id)arg1 columnInfo:(id)arg2 fromSTMT:(struct sqlite3_stmt *)arg3;
- (void)extractOneObject:(id)arg1 fromItem:(id)arg2 index:(int)arg3 STMT:(struct sqlite3_stmt *)arg4;
- (id)extractOneObjectRepeatedOfClass:(Class)arg1 withColumnInfo:(id *)arg2 STMT:(struct sqlite3_stmt *)arg3;
- (id)extractOneObjectOfClass:(Class)arg1 fromSTMT:(struct sqlite3_stmt *)arg2;
- (_Bool)excuteSQLNoRet:(const char *)arg1 errCodePrepare:(int *)arg2 errCodeStep:(int *)arg3;
- (_Bool)excuteSQLNoRet:(const char *)arg1;
- (_Bool)rollbackTransaction;
- (_Bool)commitTransaction;
- (_Bool)beginTransaction;
- (id)DBContext;
- (_Bool)createIndexOnTable:(id)arg1 withIndexArray:(const struct WCDBIndexHelper *)arg2 count:(unsigned long long)arg3;
- (_Bool)createIndexOnTable:(id)arg1 withDummyObj:(id)arg2;
- (void)alterTableIfNeeded:(id)arg1 withProperties:(id)arg2;
- (id)getColumnsFromSchema:(id)arg1;
- (id)getSchemaOfTable:(id)arg1;
- (_Bool)isTableExist:(id)arg1;
- (_Bool)dropTableOfName:(id)arg1;
- (_Bool)createTableOfName:(id)arg1 withClass:(Class)arg2;
- (void)generateMultiPrimaryKey:(basic_string_a490aa4c *)arg1 withClass:(Class)arg2;
- (void)generateTableAttribute:(basic_string_a490aa4c *)arg1 withClass:(Class)arg2;
- (void)generateTablePrefix:(basic_string_a490aa4c *)arg1 tableName:(id)arg2 withClass:(Class)arg3;
- (id)usingModule:(id)arg1;
- (id)multiPrimaryKey:(id)arg1;
- (_Bool)isVirtualTable:(id)arg1;
- (id)dicTableHelper:(Class)arg1;
- (id)getTable:(id)arg1 withClass:(Class)arg2;
- (void)forceClose;
- (void)close;
- (_Bool)isOpen;
- (void)openJournalDeleteMode;
- (void)openJournalWalMode;
- (void)configJournalMode:(_Bool)arg1;
- (_Bool)openWithWalMode:(_Bool)arg1;
- (void)dealloc;
- (id)initMemoryOnlyDB;
- (id)initWithPath:(id)arg1 withEncryptKey:(id)arg2;
- (id)initWithPath:(id)arg1 withEncryptKey:(id)arg2 databaseID:(unsigned int)arg3 isWalMode:(_Bool)arg4;
- (id)initWithPath:(id)arg1 withEncryptKey:(id)arg2 databaseID:(unsigned int)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

