//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCDataBase.h"

@interface WCDataBase (File)
+ (void)copyRowInfoFrom:(id)arg1 to:(id)arg2;
- (_Bool)deleteOneObjectFromFile:(id)arg1;
- (_Bool)loadOneObjectFromFile:(id)arg1;
- (_Bool)saveOneObjectToFile:(id)arg1;
- (id)getPathWithRowInfo:(id)arg1;
@end

