//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCDBRowInfo : NSObject
{
    long long rowID;
    _Bool isExtLoaded;
    NSString *path;
}

@property(retain, nonatomic) NSString *path; // @synthesize path;
@property(nonatomic) long long rowID; // @synthesize rowID;
@property(nonatomic) _Bool isExtLoaded; // @synthesize isExtLoaded;
- (void).cxx_destruct;
- (id)description;

@end

