//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCDeviceBrandMgrExt.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class JSEvent, MMLoadingView, MMTableView, NSMutableArray, NSString, NSTimer, UILabel, UIView, WCDevice;

@interface WCDevicePedometerSearchViewController : MMUIViewController <IWCDeviceBrandMgrExt, UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate>
{
    MMLoadingView *m_loadingView;
    UIView *m_footerView;
    UILabel *m_linkHelpBlackLabel;
    UILabel *m_linkHelpBluelabel;
    JSEvent *_m_jsEvent;
    WCDevice *_m_selectedDevice;
    NSTimer *_m_timer;
    NSMutableArray *_m_devicesFound;
    NSMutableArray *_m_devicesFail;
    MMTableView *_m_tableView;
    NSMutableArray *_m_devicesInDB;
    unsigned long long _m_enterStyle;
}

@property(nonatomic) unsigned long long m_enterStyle; // @synthesize m_enterStyle=_m_enterStyle;
@property(retain, nonatomic) NSMutableArray *m_devicesInDB; // @synthesize m_devicesInDB=_m_devicesInDB;
@property(retain, nonatomic) MMTableView *m_tableView; // @synthesize m_tableView=_m_tableView;
@property(retain, nonatomic) NSMutableArray *m_devicesFail; // @synthesize m_devicesFail=_m_devicesFail;
@property(retain, nonatomic) NSMutableArray *m_devicesFound; // @synthesize m_devicesFound=_m_devicesFound;
@property(retain, nonatomic) NSTimer *m_timer; // @synthesize m_timer=_m_timer;
@property(retain, nonatomic) WCDevice *m_selectedDevice; // @synthesize m_selectedDevice=_m_selectedDevice;
@property(retain, nonatomic) JSEvent *m_jsEvent; // @synthesize m_jsEvent=_m_jsEvent;
- (void).cxx_destruct;
- (void)onWCDeviceBindUnauthEnd:(id)arg1 Error:(id)arg2;
- (void)onBlueProfileConnectStateChanged:(long long)arg1 State:(int)arg2 ErrorCode:(int)arg3;
- (void)onWCDeviceFound:(long long)arg1 canHandled:(_Bool *)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onTimer;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)makeHeaderView:(id)arg1;
- (void)makeSearchingCell:(id)arg1;
- (void)stopLoadingAndShowErrorWithText:(id)arg1;
- (void)stopLoadingAndShowOK:(id)arg1 withDelay:(double)arg2;
- (void)stopLoading;
- (void)showLoadingViewWithText:(id)arg1;
- (void)showAlertView:(id)arg1 withTag:(long long)arg2;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)onCancel;
- (void)showLinkHelp;
- (void)showLinkHelp:(id)arg1;
- (void)reloadTableData;
- (void)updateFooterViewLocate:(id)arg1;
- (void)updateFooterViewSize;
- (void)initFooterView;
- (void)initTableView;
- (void)initView;
- (void)dealloc;
- (void)getDevicesInDB;
- (id)initWithJsEvent:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

