//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IWCDeviceAccountMgrExt.h"
#import "IWCDeviceBrandMgrExt.h"
#import "MMService.h"
#import "WCDeviceJSApiBatchSearchLogicHelpDelegate.h"

@class JSEvent, MMWebViewController, NSMutableArray, NSMutableDictionary, NSString, WCDeviceJSApiBatchSearchLogicHelp;

@interface WCDeviceJSApiMgr : MMService <MMService, WCDeviceJSApiBatchSearchLogicHelpDelegate, IWCDeviceAccountMgrExt, IWCDeviceBrandMgrExt>
{
    MMWebViewController *_currWebViewController;
    NSString *_brandUserName;
    _Bool _hasInit;
    _Bool _hasStartScan;
    NSMutableArray *_deviceSearchedList;
    WCDeviceJSApiBatchSearchLogicHelp *_batchSearchDeviceLogicHelp;
    NSMutableArray *_deviceTicketList;
    NSMutableArray *_deviceConnectStateList;
    long long _sendDataJsTaskId;
    JSEvent *_sendDataJsEvent;
    NSMutableDictionary *_directions;
    int m_enterScence;
}

- (void).cxx_destruct;
- (void)onWCDeviceAccountBound:(id)arg1;
- (void)onWCDeviceAccountUnbind:(id)arg1;
- (void)onWCDeviceSendDataToWebView:(id)arg1 data:(id)arg2;
- (void)onSendWCDevicesGetOperTicketResponse:(id)arg1 reqTicketList:(id)arg2 ErrorCode:(int)arg3;
- (void)onWCDeviceBlueToothStateChanged:(int)arg1;
- (void)onWCDeviceInitEnd:(int)arg1 DID:(long long)arg2 isHandled:(_Bool *)arg3;
- (void)onWCDeviceChannelStateChanged:(long long)arg1:(int)arg2:(int)arg3;
- (void)onWCDeviceLost:(long long)arg1;
- (void)handleWCDeviceConnectStateChanged:(long long)arg1 newConnectState:(int)arg2;
- (void)onWCDeviceFoundAddExtData:(long long)arg1 extData:(id)arg2;
- (void)onWCDeviceFoundForJSAPI:(long long)arg1;
- (void)onWCDeviceSendDataEnd:(long long)arg1 ErrType:(int)arg2 ErrCode:(int)arg3 ErrMsg:(const char *)arg4;
- (void)notifyWebViewScanResult:(id)arg1;
- (void)onWCDeviceJSApiBatchSearchResp:(id)arg1;
- (void)addNewSearchDeviceWithDid:(long long)arg1 extData:(id)arg2;
- (_Bool)canHdSendData:(id)arg1;
- (_Bool)canOpenWXDeviceLib:(id)arg1;
- (_Bool)isSendDataDirectionToServer:(id)arg1;
- (_Bool)isSendDataDirectionToH5:(id)arg1;
- (_Bool)isSendDataDirectionSet:(id)arg1;
- (void)setSendDataDirection:(unsigned int)arg1 ForDevice:(id)arg2;
- (void)sendData:(id)arg1 ToDevice:(id)arg2 CallBack:(id)arg3;
- (void)getDeviceInfos:(id)arg1;
- (void)getDeviceTicket:(id)arg1 operType:(unsigned int)arg2 CallBack:(id)arg3;
- (void)disConnectDevice:(id)arg1 CallBack:(id)arg2;
- (void)connectDevice:(id)arg1 CallBack:(id)arg2;
- (void)stopScanDevice:(id)arg1;
- (void)startScanDevice:(id)arg1;
- (void)closeWXDeviceLib;
- (void)openWXDeviceLib:(id)arg1 CallBack:(id)arg2;
- (void)releaseHardDevice;
- (id)exchangeDeviceState2Str:(int)arg1;
- (void)notifyWebViewBindStateChange:(id)arg1 bindState:(_Bool)arg2;
- (void)notifyWebViewConnectStateChange:(id)arg1 connectState:(int)arg2;
- (void)removeDeviceConnectExt:(long long)arg1 needNotifyWebView:(_Bool)arg2;
- (int)getDeviceState:(long long)arg1;
- (void)initHardDevice;
- (void)__resetHdJsSession;
- (void)dealloc;
- (void)onServiceInit;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

