//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCDeviceExtData : NSObject
{
    unsigned int m_deviceTypeMainDevice;
    unsigned int m_isEnterMyDevice;
    NSString *m_alias;
    NSString *m_iconUrl;
    NSString *m_jumpUrl;
    NSString *m_deviceTitle;
    NSString *m_deviceDesc;
    NSString *m_category;
    long long m_bleSimpleProtol;
}

@property(nonatomic) long long m_bleSimpleProtol; // @synthesize m_bleSimpleProtol;
@property(nonatomic) unsigned int m_isEnterMyDevice; // @synthesize m_isEnterMyDevice;
@property(nonatomic) unsigned int m_deviceTypeMainDevice; // @synthesize m_deviceTypeMainDevice;
@property(retain, nonatomic) NSString *m_category; // @synthesize m_category;
@property(retain, nonatomic) NSString *m_deviceDesc; // @synthesize m_deviceDesc;
@property(retain, nonatomic) NSString *m_deviceTitle; // @synthesize m_deviceTitle;
@property(retain, nonatomic) NSString *m_jumpUrl; // @synthesize m_jumpUrl;
@property(retain, nonatomic) NSString *m_iconUrl; // @synthesize m_iconUrl;
@property(retain, nonatomic) NSString *m_alias; // @synthesize m_alias;
- (void).cxx_destruct;
- (void)dealloc;

@end

