//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WCInputTextCacheMgr : NSObject
{
    NSMutableArray *_arrCacheText;
}

- (void).cxx_destruct;
- (void)onServiceMemoryWarning;
- (void)onServiceTerminate;
- (void)onServiceEnterBackground;
- (id)getCacheText:(id)arg1 refCommentItem:(id)arg2;
- (void)cacheText:(id)arg1 refDataItem:(id)arg2 refCommentItem:(id)arg3;
- (void)uncacheText:(id)arg1 refCommentItem:(id)arg2;
- (id)cacheTextKey:(id)arg1 refCommentItem:(id)arg2;
- (void)dealloc;
- (void)saveCacheText;
- (id)init;

@end

