//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IWCOutCallExt.h"
#import "WCOutDialPadDelegate.h"

@class MMTimer, NSString, UILabel, UIView, WCOutDialPad;

@interface WCOutCallingViewController : MMUIViewController <IWCOutCallExt, WCOutDialPadDelegate>
{
    _Bool m_buttonsEnable;
    long long m_lastAddKeyPadTime;
    UILabel *_logLabel;
    UIView *_normalBigView;
    UILabel *_userLabel;
    UILabel *_stateLabel;
    MMTimer *_timerLabel;
    UILabel *_keyPadInputLabel;
    WCOutDialPad *_dialPad;
}

@property(retain, nonatomic) WCOutDialPad *dialPad; // @synthesize dialPad=_dialPad;
@property(retain, nonatomic) UILabel *keyPadInputLabel; // @synthesize keyPadInputLabel=_keyPadInputLabel;
@property(retain, nonatomic) MMTimer *timerLabel; // @synthesize timerLabel=_timerLabel;
@property(retain, nonatomic) UILabel *stateLabel; // @synthesize stateLabel=_stateLabel;
@property(retain, nonatomic) UILabel *userLabel; // @synthesize userLabel=_userLabel;
@property(retain, nonatomic) UIView *normalBigView; // @synthesize normalBigView=_normalBigView;
@property(retain, nonatomic) UILabel *logLabel; // @synthesize logLabel=_logLabel;
- (void).cxx_destruct;
- (void)OnUpdateCallStateWithText:(id)arg1 hasBeAccepted:(_Bool)arg2 isCallEnded:(_Bool)arg3 isError:(_Bool)arg4;
- (void)OnPressedDialPadFunctionBtnWithType:(unsigned long long)arg1;
- (void)OnPressedDialPadKeyWithText:(id)arg1 andKeyCode:(int)arg2;
- (void)dismissSelfAfterSeconds:(float)arg1;
- (void)initViewData;
- (void)configKeyPadBigView;
- (void)configNormalBigView;
- (void)configBlurBackground;
- (void)initView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

