//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUReserverRequest : NSObject
{
    NSString *m_req_key;
    NSString *m_total_fee;
    NSString *m_fee_type;
    NSString *m_bank_type;
    NSString *m_bind_serial;
    NSString *m_cvv;
    NSString *m_pwd;
    unsigned int m_uiTotalFee;
}

@property(nonatomic) unsigned int m_uiTotalFee; // @synthesize m_uiTotalFee;
@property(retain, nonatomic) NSString *m_pwd; // @synthesize m_pwd;
@property(retain, nonatomic) NSString *m_cvv; // @synthesize m_cvv;
@property(retain, nonatomic) NSString *m_bind_serial; // @synthesize m_bind_serial;
@property(retain, nonatomic) NSString *m_bank_type; // @synthesize m_bank_type;
@property(retain, nonatomic) NSString *m_fee_type; // @synthesize m_fee_type;
@property(retain, nonatomic) NSString *m_total_fee; // @synthesize m_total_fee;
@property(retain, nonatomic) NSString *m_req_key; // @synthesize m_req_key;
- (void).cxx_destruct;
- (void)dealloc;

@end

