//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "WCActionSheetDelegate.h"

@class NSString, RichTextView, WCActionSheet;

@interface WCPayPayUBalanceDetailViewController : WCPayBaseViewController <WCActionSheetDelegate>
{
    WCActionSheet *m_actionSheet;
    id <WCPayPayUBalanceDetailViewControllerDelegate> m_delegate;
    RichTextView *richTextView;
}

- (void).cxx_destruct;
- (void)setDelegate:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)onWatchBalanceList;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onOperate;
- (void)viewDidLoad;
- (void)initNavigationBar;
- (void)OnLeftBarButtonDone;
- (void)refreshViewWithData:(id)arg1;
- (void)addQuestionEntrance;
- (id)GetMainCardHeaderView;
- (id)getHeaderView:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

