//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "WCMallAcrivityLoopPageScrollViewDataSourceDelegate.h"

@class NSString, UIButton, WCBaseKeyboardToolBar, WCBaseTextFieldItem, WCMallAcrivityLoopPageScrollView, WCUIPageControl;

@interface WCPayOpenWalletViewController : WCPayBaseViewController <WCMallAcrivityLoopPageScrollViewDataSourceDelegate, ILinkEventExt>
{
    id <WCPayOpenWalletViewControllerDelegate> m_delegate;
    UIButton *footerButton;
    WCMallAcrivityLoopPageScrollView *m_oLoopPageScrollView;
    WCUIPageControl *_bigImagePageControl;
    WCBaseTextFieldItem *m_textFieldPhoneNumberItem;
    WCBaseTextFieldItem *m_textFieldContryCodeItem;
    WCBaseKeyboardToolBar *m_keyboardBar;
}

- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)didChangeToPage:(unsigned int)arg1;
- (int)totalNumOfPage;
- (id)viewForPage:(id)arg1 pageNum:(unsigned int)arg2;
- (void)makeInfoCell:(id)arg1 cellInfo:(id)arg2;
- (void)reloadTableView;
- (void)initNavigationBar;
- (void)OnBindTelephone;
- (void)OnLeftButtonBack;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)getFooterView;
- (id)getCreateOfflinePayView;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

