//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUConfirmOtpRequest : NSObject
{
    NSString *m_otp;
    NSString *m_payu_reference;
}

@property(retain, nonatomic) NSString *m_payu_reference; // @synthesize m_payu_reference;
@property(retain, nonatomic) NSString *m_otp; // @synthesize m_otp;
- (void).cxx_destruct;
- (void)dealloc;

@end

