//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUElementQueryResponse : NSObject
{
    unsigned int m_errCode;
    NSString *m_errMsg;
    NSString *m_bin;
    NSString *m_bank_name;
    NSString *m_issuer_type;
    NSString *m_card_type;
    NSString *m_payu_ref;
}

@property(retain, nonatomic) NSString *m_issuer_type; // @synthesize m_issuer_type;
@property(retain, nonatomic) NSString *m_card_type; // @synthesize m_card_type;
@property(retain, nonatomic) NSString *m_bin; // @synthesize m_bin;
@property(retain, nonatomic) NSString *m_bank_name; // @synthesize m_bank_name;
@property(retain, nonatomic) NSString *m_payu_ref; // @synthesize m_payu_ref;
@property(retain, nonatomic) NSString *m_errMsg; // @synthesize m_errMsg;
@property(nonatomic) unsigned int m_errCode; // @synthesize m_errCode;
- (void).cxx_destruct;
- (void)dealloc;

@end

