//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class UIButton, WCPayTenpaySecureCtrlItem;

@interface WCPayResetPwdBindCardViewController : WCPayBaseViewController
{
    UIButton *m_footerButton;
    WCPayTenpaySecureCtrlItem *m_textFieldItem;
    id <WCPayResetPwdBindCardViewControllerDelegate> m_delegate;
}

- (void).cxx_destruct;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)onNext;
- (void)setDelegate:(id)arg1;
- (void)viewDidLoad;
- (void)initFooterView;
- (void)reloadTableView;
- (void)viewDidLayoutSubviews;
- (void)initNavigationBar;
- (id)init;

@end

