//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayLogicMgr.h"

@interface WCPayLogicMgr (WCPayMockLogicMrg)
- (void)GetWCPayBusinessRequestForPayU:(id)arg1 WXInnerUseDic:(id)arg2 CMDID:(unsigned int)arg3 OutputType:(unsigned int)arg4;
- (void)PayUGenPrePay:(id)arg1;
- (id)_StringToNSData:(id)arg1;
- (void)PayUUpdateSecureCtrlSalt;
- (void)PayUTimeSeedRequest;
- (void)PayUQueryTransferStatusRequest:(id)arg1;
- (void)PayUGetSecretQuestionRequest:(id)arg1;
- (void)PayUGetSecretQuestionRequest;
- (void)PayUElementQueryRequest:(id)arg1;
- (void)PayUGenPreFetchRequest:(id)arg1;
- (void)PayUGenPreSaveRequest:(id)arg1;
- (void)PayURestPinRequest:(id)arg1;
- (void)PayUConfirmSerectAnswerWithId:(id)arg1 answer:(id)arg2 ref:(id)arg3;
- (void)PayULinkUserRequest:(id)arg1;
- (void)PayUTransferCancelRequest:(id)arg1;
- (void)PayUTransferRetrySendMsgRequest:(id)arg1;
- (void)PayUTransferSendCancelMsgRequest:(id)arg1;
- (void)PayUTransferGetUsernameRequest:(id)arg1;
- (void)PayUTransferConfirmRequest:(id)arg1;
- (void)PayUTransferAuthRequest:(id)arg1;
- (void)PayUGenTransferPrepayRequest:(id)arg1;
- (void)PayUSendOtpRequest:(id)arg1;
- (void)PayUSecurityQuestionRequest;
- (void)PayUSaveAuthRequest:(id)arg1;
- (void)PayUReserverRequest:(id)arg1;
- (void)PayUQueryOrderRequest:(id)arg1;
- (void)PayUFetchAuthRequest:(id)arg1;
- (void)PayUDeletePayMethodRequest:(id)arg1;
- (void)PayUCreateUserRequest:(id)arg1;
- (void)PayUConfirmOtpRequest:(id)arg1;
- (void)PayUCheckPinRequest:(id)arg1;
- (void)PayUChangePinRequest:(id)arg1;
- (void)PayUBindQueryRequest:(id)arg1;
- (void)PayUBindQueryRequest;
- (void)PayUAddPayMethodRequest:(id)arg1;
- (void)insideCallBackPayUTimeSeedStatus:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUGetSecretQuestion:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUQueryTransferStatus:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUElementQuery:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUGenPreFetch:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUGenPreSave:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUResetPin:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUConfirmSecretAnswer:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayULinkUser:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUSendCancelMsg:(id)arg1 OnRequst:(id)arg2;
- (void)insideCallBackPayURetrySendMsg:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUTransferGetUsername:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUTransferCancel:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUTransferConfirm:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUTransferAuth:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUGenTransfer:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUSendOtp:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUSecurityQuestion:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUSaveAuth:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUReserver:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUQueryOrder:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUFetchAuth:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUDeletePayMethod:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUCreateUser:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUConfirmOtp:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUCheckPin:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUChangePin:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUBindQueryResponse:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUAddPayMethodResponse:(id)arg1 OnRequest:(id)arg2;
- (void)insideCallBackPayUGenPrepayError:(id)arg1 Request:(id)arg2;
- (void)insideCallBackPayUGenPrepay:(id)arg1 Request:(id)arg2;
@end

