//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUTransferSendCancelMsgResponse : NSObject
{
    NSString *m_retCode;
    NSString *m_retMsg;
}

@property(retain, nonatomic) NSString *m_retMsg; // @synthesize m_retMsg;
@property(retain, nonatomic) NSString *m_retCode; // @synthesize m_retCode;
- (void).cxx_destruct;
- (void)dealloc;

@end

