//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUQueryTransferStatusRequest : NSObject
{
    NSString *m_trans_id;
    NSString *m_receiver_name;
    unsigned int m_invalidate_time;
}

@property(nonatomic) unsigned int m_invalidate_time; // @synthesize m_invalidate_time;
@property(retain, nonatomic) NSString *m_receiver_name; // @synthesize m_receiver_name;
@property(retain, nonatomic) NSString *m_trans_id; // @synthesize m_trans_id;
- (void).cxx_destruct;
- (void)dealloc;

@end

