//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayPayUBalanceDetailViewControllerDelegate.h"

@class NSString;

@interface WCPayPayUBalanceDetailControlLogic : WCPayControlLogic <WCPayPayUBalanceDetailViewControllerDelegate>
{
    int m_eWCPayBalanceDetailControlLogicScene;
}

@property(nonatomic) int m_eWCPayBalanceDetailControlLogicScene; // @synthesize m_eWCPayBalanceDetailControlLogicScene;
- (void)OnPayUBindQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)BackToRootView;
- (void)PayUBalanceDetailFetchMoney;
- (void)PayUBalanceDetailSaveMoney;
- (void)PayUBalanceDetailBack;
- (void)pause;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

