//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCBaseInfoItem.h"

#import "PayUCVVCtrlDelegate.h"
#import "WCPayLogicMgrExt.h"

@class NSString, PayUCVVCtrl, UIImage;

@interface WCPayPayUCVVCtrlItem : WCBaseInfoItem <PayUCVVCtrlDelegate, WCPayLogicMgrExt>
{
    PayUCVVCtrl *m_textField;
    UIImage *m_image;
    unsigned int uiTotalNum;
}

- (void).cxx_destruct;
- (void)autoRemarkKeyBoradType;
- (void)OnGetTenpaySecureCtrlSalt:(id)arg1 Date:(id)arg2 Error:(id)arg3;
- (_Bool)onError:(id)arg1;
- (void)cvvCtrlDidEndEditing:(id)arg1;
- (void)cvvCtrlDidBeginEditing:(id)arg1;
- (void)cvvCtrlShouldChange:(id)arg1;
- (id)getHashData;
- (void)dealloc;
- (id)initWithImage:(id)arg1 TotalNum:(unsigned int)arg2;
- (void)resignFirstResponder;
- (void)becomeFirstResponder;
- (void)clearInput;
- (void)initView:(struct CGRect)arg1;
- (id)getValue;
- (struct CGSize)getSize;
- (long long)getTextLength;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

