//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class WCPayBalanceInfo;

@interface WCPayPayUBalanceView : UIButton
{
    WCPayBalanceInfo *m_info;
}

- (void).cxx_destruct;
- (id)getInfo;
- (void)dealloc;
- (id)initWithBindCardInfo:(id)arg1 Data:(id)arg2;
- (void)initViewWithBindCardInfo:(id)arg1 Data:(id)arg2;

@end

