//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "WCBaseInfoItemDelegate.h"
#import "WCPayLogicMgrExt.h"

@class NSIndexPath, NSMutableArray, NSString, UIButton, WCBaseKeyboardToolBar, WCPayPayUSecureCtrlItem, WCPayValidDateItem;

@interface WCPayPayUFillCardInfoViewController : WCPayBaseViewController <WCBaseInfoItemDelegate, WCPayLogicMgrExt, ILinkEventExt>
{
    UIButton *m_footerButton;
    WCPayPayUSecureCtrlItem *m_cardNumberSecureCtrlItem;
    WCPayValidDateItem *m_pikerValidDateItem;
    WCPayPayUSecureCtrlItem *m_textFieldCVVItem;
    NSMutableArray *m_arrayInfoGroup;
    WCBaseKeyboardToolBar *m_keyboardBar;
    _Bool m_bReadAgreement;
    _Bool m_bSubscribeApp;
    _Bool m_bAutoFilledCardInfo;
    id <WCPayPayUFillCardInfoViewControllerDelegate> m_delegate;
    NSIndexPath *m_selectItemIndex;
    _Bool m_bNeedReloadTableView;
}

@property(readonly, nonatomic) _Bool m_bAutoFilledCardInfo; // @synthesize m_bAutoFilledCardInfo;
- (void).cxx_destruct;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)OnElementQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)refreshViewWithData:(id)arg1;
- (void)clickInfoCellOnMainThread:(id)arg1;
- (void)clickInfoCell:(id)arg1 index:(id)arg2;
- (void)makeInfoCell:(id)arg1 cellInfo:(id)arg2;
- (void)WCBaseInfoItemEndEdit:(id)arg1;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (void)WCBaseInfoItemBeginEditOnMainThread:(id)arg1;
- (void)WCBaseInfoItemBeginEdit:(id)arg1;
- (void)WCBaseInfoItemCancelEdit:(id)arg1;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
- (void)checkData:(id)arg1;
- (_Bool)checkIsEmpty:(id)arg1;
- (void)showDetailTip;
- (void)onNext;
- (_Bool)getData:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)initNavigationBar;
- (void)initFooterView;
- (void)reloadTableView;
- (id)makeHeader:(id)arg1;
- (id)getSectionFromGroup:(id)arg1;
- (void)initInfoTemplate;
- (id)getSectionHeaderView:(id)arg1;
- (void)dealloc;
- (void)setTitle:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

