//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUUserInfo : NSObject
{
    NSString *m_is_reg;
    NSString *m_true_name;
    NSString *m_bind_card_num;
    NSString *m_main_card_bind_serialno;
    NSString *m_transfer_url;
    NSString *m_mobile;
}

@property(retain, nonatomic) NSString *m_mobile; // @synthesize m_mobile;
@property(retain, nonatomic) NSString *m_transfer_url; // @synthesize m_transfer_url;
@property(retain, nonatomic) NSString *m_main_card_bind_serialno; // @synthesize m_main_card_bind_serialno;
@property(retain, nonatomic) NSString *m_bind_card_num; // @synthesize m_bind_card_num;
@property(retain, nonatomic) NSString *m_true_name; // @synthesize m_true_name;
@property(retain, nonatomic) NSString *m_is_reg; // @synthesize m_is_reg;
- (void).cxx_destruct;
- (void)dealloc;

@end

