//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUTransferGetUsernameResponse : NSObject
{
    unsigned int m_errCode;
    NSString *m_errMsg;
    NSString *m_user_name;
    NSString *m_true_name;
    unsigned int m_time_stamp;
    NSString *m_fee;
    NSString *m_desc;
    NSString *m_scene;
    NSString *m_transfer_qrcode_id;
}

@property(retain, nonatomic) NSString *m_transfer_qrcode_id; // @synthesize m_transfer_qrcode_id;
@property(retain, nonatomic) NSString *m_scene; // @synthesize m_scene;
@property(retain, nonatomic) NSString *m_desc; // @synthesize m_desc;
@property(retain, nonatomic) NSString *m_fee; // @synthesize m_fee;
@property(nonatomic) unsigned int m_time_stamp; // @synthesize m_time_stamp;
@property(retain, nonatomic) NSString *m_true_name; // @synthesize m_true_name;
@property(retain, nonatomic) NSString *m_user_name; // @synthesize m_user_name;
@property(retain, nonatomic) NSString *m_errMsg; // @synthesize m_errMsg;
@property(nonatomic) unsigned int m_errCode; // @synthesize m_errCode;
- (void).cxx_destruct;
- (void)dealloc;

@end

