//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

#import "ILinkEventExt.h"
#import "IdleTimerUtilExt.h"
#import "WCActionSheetDelegate.h"
#import "WCPayFacingQRCodeImageViewDelegate.h"

@class NSMutableArray, NSString, RichTextView, UIButton, UIImage, UIView, WCPayFacingQRCodeImageView;

@interface WCPayPayUFacingReceiveQRCodeViewController : WCPayBaseViewController <IdleTimerUtilExt, ILinkEventExt, WCActionSheetDelegate, WCPayFacingQRCodeImageViewDelegate>
{
    UIButton *m_footerButton;
    id <WCPayPayUFacingReceiveQRCodeViewControllerDelegate> m_delegate;
    double _oldBrightness;
    UIView *m_oTotalMoneyView;
    NSMutableArray *m_arrPayerInfoView;
    NSMutableArray *m_arrAnimationedMessageStruct;
    UIImage *m_oQRCodeImage;
    WCPayFacingQRCodeImageView *imageQRCodeBackgroundView;
    RichTextView *balanceRichTextView;
    UIView *m_oTotalMoneyBottomLine;
    NSMutableArray *m_arrPayerBottomLine;
}

- (void).cxx_destruct;
- (void)onIdleTimerUtilVoipQuit;
- (void)OnWCPayFacingQRCodeImageViewSaveQRCodeButtonDone;
- (void)OnWCPayFacingQRCodeImageViewSaveButtonDone;
- (id)getSaveAlbumImageView;
- (void)onLinkClicked:(id)arg1 withRect:(struct CGRect)arg2;
- (void)ShowPayerStartedPayMoneyAnimation:(id)arg1 OnlyChangedOldCell:(_Bool)arg2;
- (void)insertNewView:(id)arg1;
- (void)ShowReceivedMoneyAnimation:(id)arg1;
- (void)EndReceivedMoneyAnimation:(id)arg1;
- (void)RemoveMessageStructAndShowedMoney:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)refreshViewWithData:(id)arg1;
- (void)viewDidBePoped:(_Bool)arg1;
- (void)viewDidBePushed:(_Bool)arg1;
- (void)startAddToBrightness:(id)arg1;
- (void)startDiscountToBrightness:(id)arg1;
- (void)viewDidLoad;
- (void)reloadTableView;
- (void)initNavigationBar;
- (void)initHeaderView;
- (id)getDisplayTruthNameInfo;
- (id)getDisplayNameInfo;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

