//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, WCPayControlData, WCPayPayUElementQueryResponse;

@protocol WCPayPayUFillCardInfoViewControllerDelegate <NSObject>
- (void)PayUFillCardBinResponse:(WCPayPayUElementQueryResponse *)arg1 Error:(NSError *)arg2;
- (void)PayUFillCardInfoReadAgreement;
- (void)PayUFillCardInfoNext:(WCPayControlData *)arg1;
- (void)PayUFillCardInfoCancel;
- (_Bool)PayUNeedShowServiceAppInfo;
@end

