//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayAnswerSecuQueViewControllerDelegate.h"
#import "WCPayPayUPayPwdViewControllerDelegate.h"

@class NSString;

@interface WCPayPayUResetPayPwdLogic : WCPayControlLogic <WCPayAnswerSecuQueViewControllerDelegate, WCPayPayUPayPwdViewControllerDelegate>
{
    NSString *_ref;
}

- (void).cxx_destruct;
- (void)OnChangePinByQuestionResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnConfirmSerectAnswerResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnGetSecretQuestionResponseStatus:(id)arg1 Error:(id)arg2;
- (void)PayUSetPayPwdNext:(id)arg1;
- (void)PayUVerifyPayPwdNext:(id)arg1;
- (_Bool)PayUIsNeedWithHashData;
- (void)PayUPayPwdRightActionBack;
- (void)PayUPayPwdBack;
- (_Bool)isNeedQuestionValueHashed;
- (void)OnWCPayAnswerSecuQueViewControllerBack;
- (void)answerSecQuestionsNext;
- (void)startLogic;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

