//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayPayUCardDetailViewControllerDelegate.h"
#import "WCPayPayUPayPwdViewControllerDelegate.h"

@class NSString;

@interface WCPayPayUCardContorlLogic : WCPayControlLogic <WCPayPayUPayPwdViewControllerDelegate, WCPayPayUCardDetailViewControllerDelegate>
{
}

- (void)OnSetMainCard:(id)arg1 Error:(id)arg2;
- (void)OnPayUBindQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)BackToRootView;
- (void)OnDelPaymentMethodResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnCheckPinResponseStatus:(id)arg1 Error:(id)arg2;
- (void)PayUPayPwdRightActionBack;
- (void)PayUPayPwdBack;
- (_Bool)PayUIsNeedWithHashData;
- (void)PayUVerifyPayPwdNext:(id)arg1;
- (void)CardDetailBack;
- (void)CardDetailRepay:(id)arg1;
- (void)CardDetailExpiredUnbindCard:(id)arg1;
- (void)CardDetailSetMainBankCard:(id)arg1;
- (void)CardDetailUnbindCard:(id)arg1;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

