//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayFillCardInfoViewControllerDelegate.h"
#import "WCPayFillCardNumberViewControllerDelegate.h"
#import "WCPayPayPwdViewControllerDelegate.h"
#import "WCPayPayUFillCardInfoViewControllerDelegate.h"
#import "WCPayPayUPayPwdViewControllerDelegate.h"
#import "WCPayVerifyPayCardViewControllerDelegate.h"

@class JSEvent, NSString;

@interface WCPayPayUAddPayCardLogic : WCPayControlLogic <WCPayFillCardInfoViewControllerDelegate, WCPayFillCardNumberViewControllerDelegate, WCPayPayPwdViewControllerDelegate, WCPayVerifyPayCardViewControllerDelegate, WCPayPayUPayPwdViewControllerDelegate, WCPayPayUFillCardInfoViewControllerDelegate>
{
    int m_uiLogicFinishedStatus;
    int m_uiWCPayAddPayCardLogicScene;
    JSEvent *m_jsEvent;
}

@property(nonatomic) int m_uiWCPayAddPayCardLogicScene; // @synthesize m_uiWCPayAddPayCardLogicScene;
- (void).cxx_destruct;
- (void)EndWCPayAddPayCardLogic:(id)arg1 withDelay:(_Bool)arg2;
- (void)EndWCPayAddPayCardLogic:(id)arg1;
- (void)EndWCPayAddPayCardLogic;
- (void)PayUFillCardInfoReadAgreement;
- (void)PayUFillCardBinResponse:(id)arg1 Error:(id)arg2;
- (void)PayUFillCardInfoNext:(id)arg1;
- (void)PayUFillCardInfoCancel;
- (_Bool)PayUNeedShowServiceAppInfo;
- (void)OnPayUBindQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnAddPaymentMethodResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnElementQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnHandleVerifiedSMSString:(id)arg1;
- (void)OnSetWCPayPasswordInBind:(id)arg1;
- (void)OnBindCardVerifySMS:(id)arg1 Error:(id)arg2;
- (void)OnBindCardVerifyCard:(id)arg1 Error:(id)arg2;
- (void)OnGetBindingCardBin:(id)arg1 AvailableBank:(id)arg2 Error:(id)arg3;
- (void)OnVerifyPayPassword:(id)arg1;
- (void)OnGetBindQueryInfo:(id)arg1 Error:(id)arg2;
- (void)OnTenpayImportBindQuery:(id)arg1 AppInfo:(id)arg2 UsrVerifiedInfo:(id)arg3 Error:(id)arg4;
- (void)OnCheckWCPayJsApiRequest:(id)arg1 Error:(id)arg2;
- (void)onErrorAlertViewDismiss:(id)arg1;
- (void)stopLogicToMyPayCardView;
- (void)stopLogicToRefreshPayCardList;
- (void)PayPwdRightActionBack;
- (void)PayPwdBack;
- (void)SetPayPwdNext:(id)arg1;
- (void)VerifyPayCardAgain:(id)arg1;
- (void)VerifyPayCardNext:(id)arg1;
- (void)VerifyPayCardBack;
- (void)FillCardInfoReadAgreement;
- (void)FillCardInfoNext:(id)arg1;
- (id)getWCPayBindInfo:(id)arg1;
- (void)FillCardInfoCancel;
- (_Bool)NeedShowServiceAppInfo;
- (void)FillCardNumberConfirmWithImage:(id)arg1 cardNumber:(id)arg2 data:(id)arg3;
- (void)FillCardNumberNext:(id)arg1;
- (void)FillCardNumberCancel:(_Bool)arg1;
- (void)VerifyPayPwdNext:(id)arg1;
- (void)OnCheckPinResponseStatus:(id)arg1 Error:(id)arg2;
- (void)PayUVerifyPayPwdNext:(id)arg1;
- (_Bool)PayUIsNeedWithHashData;
- (void)PayUPayPwdRightActionBack;
- (void)PayUPayPwdBack;
- (void)showGiveUpLogicAlert;
- (void)startAddCardLogic;
- (void)stopLogic;
- (void)startLogic;
- (void)dealloc;
- (id)initWithJSEvent:(id)arg1;
- (id)initWithData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

