//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WCPayPayUPaymentMethod;

@interface WCPaypayUSaveAuthResponse : NSObject
{
    unsigned int m_errCode;
    NSString *m_errMsg;
    WCPayPayUPaymentMethod *m_paymentMethod;
    NSString *m_trans_id;
    unsigned int m_response_result;
    _Bool m_redirect;
    NSString *m_gateway_reference;
    NSString *m_gateway_code;
    NSString *m_pay_flag;
    _Bool m_is_force_ajust;
    NSString *m_force_adjust_code;
}

@property(retain, nonatomic) NSString *m_force_adjust_code; // @synthesize m_force_adjust_code;
@property(nonatomic) _Bool m_is_force_ajust; // @synthesize m_is_force_ajust;
@property(retain, nonatomic) NSString *m_pay_flag; // @synthesize m_pay_flag;
@property(retain, nonatomic) NSString *m_gateway_code; // @synthesize m_gateway_code;
@property(retain, nonatomic) NSString *m_gateway_reference; // @synthesize m_gateway_reference;
@property(nonatomic) _Bool m_redirect; // @synthesize m_redirect;
@property(retain, nonatomic) NSString *m_trans_id; // @synthesize m_trans_id;
@property(nonatomic) unsigned int m_response_result; // @synthesize m_response_result;
@property(retain, nonatomic) WCPayPayUPaymentMethod *m_paymentMethod; // @synthesize m_paymentMethod;
@property(retain, nonatomic) NSString *m_errMsg; // @synthesize m_errMsg;
@property(nonatomic) unsigned int m_errCode; // @synthesize m_errCode;
- (void).cxx_destruct;
- (void)dealloc;

@end

