//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel, WCPayPayUPasswordCtrlItem;

@interface WCPayPayUPwdCtrlPanelView : UIView
{
    UIImageView *m_footerTipImageView;
    UILabel *m_footerTip;
    UIView *m_footerView;
    WCPayPayUPasswordCtrlItem *m_textField;
    UILabel *tip;
    double _contentViewY;
}

@property(nonatomic) double contentViewY; // @synthesize contentViewY=_contentViewY;
@property(retain, nonatomic) WCPayPayUPasswordCtrlItem *m_textField; // @synthesize m_textField;
- (void).cxx_destruct;
- (void)dealloc;
- (void)setFooterView:(id)arg1;
- (void)setError:(id)arg1;
- (void)layoutSubviews;
- (id)initWithTip:(id)arg1;

@end

