//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayOrderDetailActivityInfo : NSObject
{
    NSString *m_nsIconUrl;
    NSString *m_nsActivityTitle;
    NSString *m_nsBtnTitle;
    NSString *m_nsActivityUrl;
}

@property(retain, nonatomic) NSString *m_nsIconUrl; // @synthesize m_nsIconUrl;
@property(retain, nonatomic) NSString *m_nsBtnTitle; // @synthesize m_nsBtnTitle;
@property(retain, nonatomic) NSString *m_nsActivityUrl; // @synthesize m_nsActivityUrl;
@property(retain, nonatomic) NSString *m_nsActivityTitle; // @synthesize m_nsActivityTitle;
- (void).cxx_destruct;
- (void)dealloc;

@end

