//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUElementQueryRequest : NSObject
{
    NSString *m_card_number;
}

@property(retain, nonatomic) NSString *m_card_number; // @synthesize m_card_number;
- (void).cxx_destruct;
- (void)dealloc;

@end

