//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayControlLogic.h"

#import "WCPayAnswerSecuQueViewControllerDelegate.h"
#import "WCPayConfirmOptViewControllerDelegate.h"
#import "WCPayLogicMgrExt.h"
#import "WCPayOpenWalletViewControllerDelegate.h"
#import "WCPayPayUPayPwdViewControllerDelegate.h"

@class NSString;

@interface WCPayOpenWalletLogic : WCPayControlLogic <WCPayOpenWalletViewControllerDelegate, WCPayConfirmOptViewControllerDelegate, WCPayAnswerSecuQueViewControllerDelegate, WCPayPayUPayPwdViewControllerDelegate, WCPayLogicMgrExt>
{
    _Bool m_isNeedOneWayHashInSecuQue;
}

- (void)OnCreateAccountResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnLinkUserResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnListSecurityQuestionResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnConfirmSerectAnswerResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnGetSecretQuestionResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnConfirmOtpResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnSendOtpResponseStatus:(id)arg1 Error:(id)arg2;
- (void)OnPayUBindQueryResponseStatus:(id)arg1 Error:(id)arg2;
- (void)PayUSetPayPwdNext:(id)arg1;
- (void)PayUPayPwdRightActionBack;
- (void)PayUPayPwdBack;
- (_Bool)PayUIsNeedWithHashData;
- (_Bool)isNeedQuestionValueHashed;
- (void)OnWCPayAnswerSecuQueViewControllerBack;
- (void)answerSecQuestionsNext;
- (void)OnAnswerSecurityQuestionBack;
- (void)OnAnswerSecurityQuestion;
- (void)VerifyPayCardAgain:(id)arg1;
- (void)VerifyPayCardNext:(id)arg1;
- (void)VerifyPayCardBack;
- (void)OnConfirmOpt:(id)arg1;
- (void)OnBindTelephone;
- (void)OpenWalletBack;
- (void)EndOpenWalletLogic;
- (void)stopLogic;
- (void)startLogic;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

