//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCPayBaseViewController.h"

@class UIButton, WCBaseKeyboardToolBar, WCPayPayUQuestionItem, WCPayPayUSecureCtrlItem;

@interface WCPayAnswerSecuQueViewController : WCPayBaseViewController
{
    id <WCPayAnswerSecuQueViewControllerDelegate> m_delegate;
    UIButton *footerButton;
    WCBaseKeyboardToolBar *m_keyboardBar;
    WCPayPayUSecureCtrlItem *m_AnswerSecureCtrlItem;
    WCPayPayUQuestionItem *m_questionSelectItem;
}

- (void).cxx_destruct;
- (void)setDelegate:(id)arg1;
- (void)WCBaseInfoItemEndEdit:(id)arg1;
- (void)WCBaseInfoItemBeginEdit:(id)arg1;
- (void)WCBaseInfoItemPressReturnKey:(id)arg1;
- (void)answerSecQuestionsNext;
- (void)initNavigationBar;
- (void)viewDidLayoutSubviews;
- (void)clickInfoCell:(id)arg1 index:(id)arg2;
- (void)makeInfoCell:(id)arg1 cellInfo:(id)arg2;
- (void)reloadTableView;
- (void)WCBaseInfoItemEditChanged:(id)arg1;
- (id)getFooterView;
- (void)viewDidLoad;
- (void)dealloc;

@end

