//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WCPayPayUChangePinRequest : NSObject
{
    NSString *m_old_pin;
    NSString *m_new_pin;
}

@property(retain, nonatomic) NSString *m_new_pin; // @synthesize m_new_pin;
@property(retain, nonatomic) NSString *m_old_pin; // @synthesize m_old_pin;
- (void).cxx_destruct;
- (void)dealloc;

@end

