//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WCRedEnvelopesControlLogic.h"

#import "WCFestivalRedEnvFinishViewDelegate.h"
#import "WCFestivalRedEnvReceiveHomeViewDelegate.h"
#import "WCFestivalRedEnvShareViewDelegate.h"
#import "WCPayLogicMgrExt.h"
#import "WCRedEnvelopesMultiSelectContactsViewControllerDelegate.h"
#import "WCRedEnvelopesSessionSelectViewControllerDelegate.h"

@class NSString, WCFestivalRedEnvFinishView, WCFestivalRedEnvReceiveHomeView, WCFestivalRedEnvShareView;

@interface WCRedEnvelopesEnterpriseControlLogic : WCRedEnvelopesControlLogic <WCFestivalRedEnvReceiveHomeViewDelegate, WCFestivalRedEnvShareViewDelegate, WCFestivalRedEnvFinishViewDelegate, WCRedEnvelopesMultiSelectContactsViewControllerDelegate, WCRedEnvelopesSessionSelectViewControllerDelegate, WCPayLogicMgrExt>
{
    WCFestivalRedEnvReceiveHomeView *m_oHomeView;
    WCFestivalRedEnvShareView *m_oShareView;
    WCFestivalRedEnvFinishView *m_oFinishView;
}

- (void).cxx_destruct;
- (void)closeAnimationWindowAndShowDetailView:(id)arg1;
- (void)showDetailView;
- (void)onMultiSelectContactReturn:(id)arg1;
- (void)OnAsyncBizSubcribeResponse:(id)arg1 Error:(id)arg2;
- (void)WCFestivalRedEnvFinishViewToShare;
- (void)WCFestivalRedEnvFinishViewBack;
- (void)WCFestivalRedEnvShareViewToFinish;
- (void)WCFestivalRedEnvShareViewBack;
- (void)WCFestivalRedEnvReceiveHomeViewOpenList;
- (void)WCFestivalRedEnvReceiveHomeViewOpenRedEnvelopes:(_Bool)arg1;
- (void)WCFestivalRedEnvReceiveHomeViewBack;
- (void)OnNotifyNoShareEnterpriseRedEnvelopesResponse:(id)arg1 Error:(id)arg2;
- (void)OnSendShareEnterpriseRedEnvelopesResponse:(id)arg1 Error:(id)arg2;
- (void)OnOpenEnterpriseRedEnvelopesResponse:(id)arg1 Error:(id)arg2;
- (void)OnSelectMutilContactsButton;
- (void)OnSelectSessionReturn:(id)arg1;
- (void)OnSelectSessionCancel:(id)arg1;
- (void)OnSelectSession:(id)arg1 SessionSelectController:(id)arg2;
- (void)dismissCurrentSendShareRedEnvelopesView;
- (void)OnSendShareRedEnvelopes;
- (void)startLogic;
- (void)stopLoading;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

