//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class UIButton, UIImageView, UIView;

@interface WCRedEnvelopesMadeHBSuccessView : MMUIView
{
    id <WCRedEnvelopesMadeHBSuccessViewDelegate> m_delegate;
    UIImageView *m_backgroundView;
    UIButton *openRedEnvelopesButton;
    _Bool m_bEndAnmation;
    UIView *oRedView;
    UIView *oTopHeaderView;
}

- (void).cxx_destruct;
- (void)removeView;
- (void)endAnimation;
- (void)showAnimation;
- (void)stopReceiveAnimation;
- (void)startReceiveAnimation;
- (void)OnSendHBDone;
- (void)OnCancelButtonDone;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

@end

