//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUILabel, UIImageView, UILabel;

@interface WCRedEnvelopesGreetingSenderHomeView : MMUIView
{
    id <WCRedEnvelopesGreetingSenderHomeViewDelegate> m_delegate;
    UIImageView *m_backgroundView;
    MMUILabel *numLable;
    UILabel *m_descTitleLable;
    UILabel *m_statusLabel;
    UIImageView *m_receivedIconView;
    _Bool m_bEndAnmation;
}

- (void).cxx_destruct;
- (void)removeView;
- (void)endAnimation;
- (void)showAnimation;
- (void)OnCancelButtonDone;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2 TotalFee:(long long)arg3 Wish:(id)arg4 StatusMess:(id)arg5 NotShowIcon:(_Bool)arg6;

@end

