//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIView.h"

@class MMUILabel, UIButton, UIImageView, UILabel, ZCWScrollNumView;

@interface WCRedEnvelopesGreetingReceiveView : MMUIView
{
    id <WCRedEnvelopesGreetingReceiveViewDelegate> m_delegate;
    UIImageView *m_backgroundView;
    UIButton *openRedEnvelopesButton;
    UIImageView *openAnimationImageView;
    ZCWScrollNumView *numView;
    MMUILabel *numLable;
    _Bool m_bScrollNum;
    UILabel *m_descTitleLable;
    UILabel *m_statusLabel;
    UIImageView *m_receivedIconView;
    _Bool m_bEndAnmation;
}

- (void).cxx_destruct;
- (void)removeView;
- (void)showGreeting;
- (void)showNumAnimation;
- (void)endAnimation;
- (void)showAnimation;
- (void)OnCancelButtonDone;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2 TotalFee:(long long)arg3 Wish:(id)arg4 HeadUrl:(id)arg5 NickName:(id)arg6 StatusMess:(id)arg7 ScrollNum:(_Bool)arg8 NotShowIcon:(_Bool)arg9;

@end

