//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMRefreshTableFooterView.h"

@class NSString, UIActivityIndicatorView, UILabel;

@interface WCTimeLineFooterView : MMRefreshTableFooterView
{
    UIActivityIndicatorView *m_activityIndicatorView;
    UILabel *m_label;
    unsigned int m_lineViewWidth;
    NSString *m_normalText;
    NSString *m_loadingText;
}

@property(retain, nonatomic) NSString *m_loadingText; // @synthesize m_loadingText;
@property(retain, nonatomic) NSString *m_normalText; // @synthesize m_normalText;
@property(nonatomic) unsigned int m_lineViewWidth; // @synthesize m_lineViewWidth;
@property(retain, nonatomic) UILabel *m_label; // @synthesize m_label;
@property(retain, nonatomic) UIActivityIndicatorView *m_activityIndicatorView; // @synthesize m_activityIndicatorView;
- (void).cxx_destruct;
- (void)onStateOfNoData:(id)arg1;
- (void)onStateOfNoMoreData:(id)arg1;
- (void)onStateOfLoading;
- (void)onStateOfNormal;
- (void)resetStatus:(int)arg1;
- (void)fitIPadClassicStyle;
- (void)useMMSettingStyle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

