//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray;

@protocol WCTimelineDelegate
- (void)onTimelineAdDataChangedWithAdded:(NSArray *)arg1;
- (void)onNoMoreTimelineData;
- (void)onTimelineDataChangedWithAdded:(NSArray *)arg1 andChanged:(NSArray *)arg2 andDeleted:(NSArray *)arg3;
@end

