//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMUIViewController.h"

#import "IMsgExt.h"
#import "PBMessageObserverDelegate.h"
#import "UIScrollViewDelegate.h"
#import "scrollViewDelegate.h"

@class MMScrollView, NSMutableSet, NSString, UIButton, UIImageView, UILabel, UIView;

@interface WhatsnewViewController : MMUIViewController <UIScrollViewDelegate, PBMessageObserverDelegate, scrollViewDelegate, IMsgExt>
{
    id <whatsnewViewDelegateEx> m_delegate;
    MMScrollView *m_scrollView;
    UIButton *m_btnEnter;
    UIImageView *m_imageViewBackGround;
    UIView *m_viewLoading;
    UILabel *m_loadingTip;
    _Bool m_bShowResult;
    _Bool m_bGetQRCode;
    NSMutableSet *m_arrSvrID;
    UIView *m_qrCodeView;
    UIImageView *m_qrCodeBackgroundView;
    UIImageView *m_qrCodeImageView;
    UILabel *m_qrCodeTip;
    UIView *m_recieveFeeView;
}

@property(nonatomic) __weak id <whatsnewViewDelegateEx> m_delegate; // @synthesize m_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)OnGetNewXmlMsg:(id)arg1 Type:(id)arg2 MsgWrap:(id)arg3;
- (void)OnNotifyAddFacingReceiveMoneyPayerInfo:(id)arg1;
- (id)genRecieveFeeView:(id)arg1;
- (id)handleWCPayFacingReceiveMoneyMsg:(id)arg1;
- (_Bool)checkShouldHandleId:(long long)arg1;
- (void)MessageReturn:(id)arg1 Event:(unsigned int)arg2;
- (void)startLoadUserData;
- (_Bool)hasGetQRCode;
- (void)viewDidLoad;
- (void)hideStatusBar;
- (void)animationShowQRCode;
- (void)showEnterBtn;
- (_Bool)showQRCode;
- (void)showLoadView;
- (void)initView;
- (void)initPages;
- (void)initEnterButton;
- (void)initScrollView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)touchesBegan_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved_ScrollView:(id)arg1 withEvent:(id)arg2;
- (void)enterWechat;
- (void)stopShowWhatsNew;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

