//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WXGUploadFileInformation : NSObject
{
    NSString *_mailAddress;
    NSString *_filePath;
    NSString *_fileDescription;
}

+ (id)uploadFileInformationWithXMl:(struct XmlReaderNode_t *)arg1;
@property(copy, nonatomic) NSString *fileDescription; // @synthesize fileDescription=_fileDescription;
@property(copy, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(copy, nonatomic) NSString *mailAddress; // @synthesize mailAddress=_mailAddress;
- (void).cxx_destruct;

@end

