//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIScrollViewDelegate.h"

@class MMTimer, NSMutableArray, NSMutableDictionary, NSString, UILabel, UIScrollView;

@interface WXTalkHeadListView : UIView <UIScrollViewDelegate>
{
    NSMutableArray *_memberItemList;
    UIScrollView *_scrollView;
    UILabel *_tipsLabel;
    NSMutableDictionary *_tipsArray;
    UILabel *_memberCount;
    MMTimer *_timer;
    NSMutableArray *_tempDelArray;
}

- (void).cxx_destruct;
- (void)setMemberCount:(unsigned int)arg1;
- (void)reset;
- (void)removeTipsForOrderAndUpdate:(int)arg1;
- (void)setTipsAndUpdate:(id)arg1 forOrder:(int)arg2;
- (void)doUpdateStrategy;
- (void)updateTipsLabel:(id)arg1 TextColor:(id)arg2;
- (void)clearEnterExitTips;
- (void)noBodyTalking;
- (id)usernameToDisplayName:(id)arg1;
- (void)doTimerFadeInFadeOutAnimation:(_Bool)arg1;
- (void)someBodyTalking:(id)arg1;
- (_Bool)delMember:(id)arg1;
- (_Bool)addMember:(id)arg1;
- (void)updateItemViewPosition;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

